### ISSUE TITLE
Support for Private Sessions

### ISSUE THREAD

**Issue by luizribeiro** [fondberg/spotcast#100]
Thanks for all the work on Spotcast!

Is it possible to add support for playing a playlist as a Private Session?

Main reason being I play a playlist for waking up every morning, but Spotify keeps suggesting me that playlist a ton now because I end up listening to it every day :P

**Comment by fondberg** [comment]
Not that I'm aware of. If you find something in their APIs please tell me and we can open a feature ticket for it

**Comment by fondberg** [comment]
Closing this as it can't be done to the best of my knowledge
