### ISSUE TITLE
Exceeded 30 redirects

### ISSUE THREAD

**Issue by goose2600** [fondberg/spotcast#102]
Last weeks I had a problem while executing the spotcast.start service, before it used to works flawless, untill I start getting a too many redirects error.

The custom component (v3.1.1) is installed via HACS on Home Assistant version 0.111.4.
Could someone please help me?

Here is the Home Assistant log:
`Logger: homeassistant.components.websocket_api.http.connection.140401782279824`
`Source: custom_components/spotcast/__init__.py:85` 

`Exceeded 30 redirects.`

`Traceback (most recent call last):`
`File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130,`
`in handle_call_service`
`    connection.context(msg),`
  `File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call`
`    task.result()`
`  File "/usr/src/homeassistant/homeassistant/core.py", line 1299, in _execute_service`
`    await self._hass.async_add_executor_job(handler.func, service_call)`
`  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run`
`    result = self.fn(*self.args, **self.kwargs)`
`  File "/config/custom_components/spotcast/__init__.py", line 166, in start_casting`
`    access_token, expires = get_spotify_token(sp_dc=dc, sp_key=key)`
`  File "/config/custom_components/spotcast/__init__.py", line 85, in get_spotify_token`
`    data = st.start_session(sp_dc, sp_key)`
 ` File "/usr/local/lib/python3.7/site-packages/spotify_token.py", line 19, in start_session`
`    headers=headers, cookies=cookies)`
`  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get`
`    return self.request('GET', url, **kwargs)`
`  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request`
`    resp = self.send(prep, **send_kwargs)`
`  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 665, in send`
`    history = [resp for resp in gen] if allow_redirects else []`
`  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 665, in <listcomp>`
`    history = [resp for resp in gen] if allow_redirects else []`
`  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 166, in resolve_redirects`
`    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)`
`requests.exceptions.TooManyRedirects: Exceeded 30 redirects.`

**Comment by fondberg** [comment]
It seems like you had some problem connecting to the auth URL to spotify. Did it go away? If not, can you see if it works with a normal browser session to open.spotify.com

**Comment by goose2600** [comment]
Fixed with 3.2.1 update
