### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by notpurum** [fondberg/spotcast#105]
I have the HA 0.111 and the latest Spotcast but every morning I get this error:

```
Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.7/site-packages/pychromecast/socket_client.py:414
First occurred: 8:00:02 (3 occurrences)
Last logged: 8:13:36

[(192.168.0.32):42204] Failed to connect, retrying in 5.0s
```

If I activate my GHM's with the voice the spotcast starts working properly. But after a night of playing nothing they somewhy seem to be unreachable. 
I tried `device_name `and `entity_id`. The `sensor.chromecast_devices` state is `ok` and there are my devices in the attributes.

**Comment by fondberg** [comment]
This is not a problem with spotcast. It is rather with how pychromecast has stored the ip for your device and your device has changed its ip.

**Comment by notpurum** [comment]
Well, you're probably right. The only thing I found out is that the spotcast can't start music only on a cast group. The speakers separately keep working. Will try to find the reason
