### ISSUE TITLE
Cannot install via HACS

### ISSUE THREAD

**Issue by iroger** [fondberg/spotcast#115]
I tried to install spotcast on latest home assistant via HACS v1.2.2.

But: spotcast is not listed

However when I try to add 'https://github.com/fondberg/spotcast' to custom repositories I get an error that 'fondberg/spotcast' exists in the store.

?

**Comment by fondberg** [comment]
This tracker is for issues with spotcast. You seem to have problems with hacs which should be asled on the forum
