### ISSUE TITLE
sensor spamming logs

### ISSUE THREAD

**Issue by Alfiegerner** [fondberg/spotcast#118]
Thanks very much for the quick turnaround on the pychromecast integration problems recently, very much appreciated.

Could we please make the logging in sensor.py set to debug instead of info?  I have set this in my local code but would be good to remove the spamming.

**Comment by fondberg** [comment]
Sure, Can you make a PR?

**Comment by Alfiegerner** [comment]
Thanks for doing, and apologies should have done PR, still learning oss protocols.
