### ISSUE TITLE
Home Assistant 114.0.0 - no module named `spotipy`

### ISSUE THREAD

**Issue by jmpavlec** [fondberg/spotcast#122]
I used the Home Assistant Configuration checker for version 114.0.0 to see if the upgrade would be successful and it gave me an error related to spotcast:

```
INFO:homeassistant.util.package:Attempting install of spotipy==2.12.0
Failed config
  General Errors: 
    - Component error: spotcast - No module named 'spotipy'
```

I didn't see any breaking changes mentioning this from Home Assistant. I also tried updating the [manifest.json](https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/manifest.json) to depend on home assistant 114.0.0 but that also didn't work. I'm not a python dev otherwise I'd dig into it myself.

Are the dependencies inherited from HA? Is it possible it is trying to initialize spotcast before the `spotipy` library is installed?

**Comment by angarok** [comment]
This is a false positive, Spotcast works in 114.0. The configuration checker says the same if you check it against 113.3 as well. Might be that it has problems checking custom/HACS components.
