### ISSUE TITLE
Spotify Features

### ISSUE THREAD

**Issue by davidrustingha** [fondberg/spotcast#124]
I recently came across a thing called 'Spotify Audio Features'. It gives the user information like the tempo of the song, the genre etc.
I have been researching the working of the API and how I could obtain that data but, as I have zero experience writing in python or any other code, I have no idea what I'm doing.

However, I know that the spotcast integration uses the API and the authorization. Would it be possible to add that data to the state_attributes of a spotcast sensor?

**Comment by fondberg** [comment]
It would not be the right place for this. I would suggest trying to get this functionality in the main spotify integration
