### ISSUE TITLE
Playback stops after 1 hour

### ISSUE THREAD

**Issue by MagicMicky** [fondberg/spotcast#126]
Hello!

It seems to have been mentioned on the internet (found at least two reference) but I couldn't find even a closed issue related to this. Sorry if it was already shared and mentionned here.

So, about after one hour when we start music using spotcast, the music just simply stops. According to some of @fondberg [comments](https://community.home-assistant.io/t/spotcast-custom-component-to-start-playback-on-an-idle-chromecast-device/114232/164) it seems to be related to `pychromecast` and that the token is expired after 1 hour.

What would be the approach to extend/refresh this token? Is there also a way that no matter if the token expires, it doesn't stop the playback from the chromecast?

You probably have investigated this already, I would love to hear about what you found, and maybe help dig a little deeper to see how I can help.

**Comment by fondberg** [comment]
It is tje first open issue  #13

**Comment by fondberg** [comment]
Read my findings in that issue

**Comment by MagicMicky** [comment]
Arg thanks, thought it was a different issue based on title. Will go through it.
