### ISSUE TITLE
Google home mini lost in ether

### ISSUE THREAD

**Issue by Wriman** [fondberg/spotcast#127]
After i update HA 0.113.2 my google home mini is lost in my Homeassistant
i try #spotcast and after they come back again 
after if i update spotcast same.
i use docker compose
the homeassistant dont write new error in homeassistant log, but the spotcast is working.. but my google home mini is lost if i add config spotcast things.

**Comment by fondberg** [comment]
Hello.
Can you turn on debug for spotcast in the logger  for HA configuration and send the output?

**Comment by fondberg** [comment]
Closing due to lack of info
