### ISSUE TITLE
Service will not start - cannot find device

### ISSUE THREAD

**Issue by squireblackdens** [fondberg/spotcast#133]
Hi there
Installed Spotcast through HACS, authorised with spotify fine but cannot call service as any device I select "cannot be found". Have tried all variations of entity_id, device_name, friendly name  etc... as detailed in earlier issues but nothing / no combination works. All the devices can be seen and played to fine by other services.

Typical error log:

Logger: homeassistant.components.websocket_api.http.connection.547811645616
Source: custom_components/spotcast/__init__.py:445
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:22:05 (6 occurrences)
Last logged: 21:29:14

Could not find device with name Sonos 5
Could not find device with name Kitchen
Could not find device with name media_player.kitchen
Could not find device with name kitchen
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 138, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1335, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1374, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 299, in start_casting
    spotify_cast_device = SpotifyCastDevice(
  File "/config/custom_components/spotcast/__init__.py", line 403, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/config/custom_components/spotcast/__init__.py", line 445, in getChromecastDevice
    raise HomeAssistantError("Could not find device with name {}".format(device_name))
homeassistant.exceptions.HomeAssistantError: Could not find device with name Sonos 5

Same problem with all media devices (chromecast or sonos) and all variations of name etc...

Running on a fresh install of HA - 0.116.2 on Pi3+, 

rch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.5
supervisor | 247
timezone | Europe/London
version | 0.116.2
virtualenv | false

Have tired uninstall / reinstall but no difference.

Thanks

**Comment by fondberg** [comment]
Hi! Either ry and use the spotify developer console and list spotify connect devices or use the sensor to see the bames of your chrome cast devices

**Comment by stefsims** [comment]
I had the same issue with my new Nest Audio speaker. My old Nest Home Minis worked fine.
Then I found out I had named the speaker differently in the Google Home app and in Home Assistant entity name override.
Given the same name. It works.

**Comment by stefancvetkovic** [comment]
I have the same issue. Im using Denon AVR integration for HA, and I changed entities, and therefore it changed my names for 2 zones, now Im getting this error. How to solve it without restoring old names?

**Comment by fondberg** [comment]
Use device_name instead of entity_id

**Comment by stefancvetkovic** [comment]
I am using device_name
https://i.imgur.com/2L94wIz.png
https://i.imgur.com/Z2lkp1G.png

**Comment by fondberg** [comment]
remove entity_id
