### ISSUE TITLE
Feature Request: Set starting volume

### ISSUE THREAD

**Issue by justincrosby** [fondberg/spotcast#135]
Sorry, not sure where to post this but here goes.

I'd like to be able to set the volume via a call to spot cast using the Spotify API. I have tried using media_player.volume_set immediately after but it takes awhile for hass (possibly chromecast API?) to update the media player state so the volume doesn't take. I tried hacking the spotcast code to set the volume after starting the playlist and it works a treat; music starts at the specified volume with no delay at all.

I could take a crack at coding this properly and opening a PR but wanted to gage willingness to incorporate this either way.

**Comment by fondberg** [comment]
As long as it is an optional paramater it is ok. And a PR is always welcome

**Comment by fondberg** [comment]
Closing. Feel free to opn a PR
