### ISSUE TITLE
error with 0.117.0 release of home assistant

### ISSUE THREAD

**Issue by pinkywafer** [fondberg/spotcast#136]
my repo is validated by travis-ci.  building against home Assistant 0.117.0 gives the following error:
```
 homeassistant.packages.spotcast.spotcast: 
    - Package spotcast setup failed. Component spotcast No module named 'plexapi'
```
removal of spotcast allows the build to pass and no errors are raised.

**Comment by pinkywafer** [comment]
link to my configuration of spotcast: https://github.com/pinkywafer/Home-Assistant_Config/blob/master/packages/media_players/spotcast.yaml

**Comment by pinkywafer** [comment]
The add-on 'check home assistant configuration' returns:
```
Testing configuration at /tmp/config
Failed config
  homeassistant.packages.spotcast.spotcast: 
    - Package spotcast setup failed. Component spotcast No module named 'spotipy'
    - sensor: [source /tmp/config/packages/media_players/spotcast.yaml:9]
        - platform: spotcast
      spotcast: [source /tmp/config/packages/media_players/spotcast.yaml:1]```

**Comment by pinkywafer** [comment]
My testing shows this is caused by missing resources in the manifest. I'll open PR to fix shortly

**Comment by fondberg** [comment]
Please leave it as i intentionally removed spotipy to use the same as HA uses.

**Comment by pinkywafer** [comment]
Currently, spotipy, pychromecast, plexapi and plexwebsocket are all flagged as missing. 

Spotipy is still imported directly in __init__.py.

I assume that the reason it is failing the config check now is due to a change in home Assistant 0.117.0. I believe that these libraries are not included any longer by default, and are only installed when required. This error has only occured since the release of 0.117.0

**Comment by elyobelyob** [comment]
So, what needs to be done to fix this? I can't use HACS, my configuration is showing as invalid ("Component error: spotcast - No module named 'plexapi' ") and I have a persistent booting message ("Home Assistant is starting, not everything will be available until it is finished").

**Comment by pinkywafer** [comment]
@elyobelyob I have edited my custom_components/spotcast/manifest.json file and all now works again.  You can do the same by copying mine from https://github.com/fondberg/spotcast/pull/137/commits/0671ae30704a8eb60436ae48177325cc2ca0ae47

**Comment by elyobelyob** [comment]
@pinkywafer thanks for that ... it's always such a risk upgrading ... now I just need to fix my tradfri implementation.

**Comment by ciB89** [comment]
got the same issue

**Comment by pinkywafer** [comment]
Further information and steps to reproduce:
run the official addon: "Check Home Assistant Configuration"
check the logs:
first run (failed due to lack of spotipy):
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[16:52:21] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:52:21] INFO: Setup udev devices
[16:52:24] INFO: Don't worry, this temporary installation is not overwriting your current one.
[16:52:24] INFO: Installing Home Assistant: latest...
[16:52:24] INFO: Please be patient, this might take a few minutes...
[16:53:17] INFO: Installed Home Assistant 0.117.1
[16:53:17] INFO: Making a copy of your configuration for checking...
[16:54:19] INFO: Checking your configuration against this version...
[16:57:19] ERROR: The configuration check did not pass!
[16:57:19] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Failed config
  homeassistant.packages.spotcast.spotcast: 
    - Package spotcast setup failed. Component spotcast No module named 'spotipy'
    - sensor: [source /tmp/config/packages/media_players/spotcast.yaml:9]
        - platform: spotcast
      spotcast: [source /tmp/config/packages/media_players/spotcast.yaml:1]
        accounts: [source /tmp/config/packages/media_players/spotcast.yaml:4]
          emma: [source /tmp/config/packages/media_players/spotcast.yaml:5]
            sp_dc: REDACTED
            sp_key: REDACTED
        sp_dc: REDACTED
        sp_key: REDACTED

Successful config (partial)
[16:57:19] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
Add spotipy to resources.
2nd run log (failed due to lack of pychromecast):
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[17:06:47] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:06:48] INFO: Setup udev devices
[17:06:51] INFO: Don't worry, this temporary installation is not overwriting your current one.
[17:06:51] INFO: Installing Home Assistant: latest...
[17:06:51] INFO: Please be patient, this might take a few minutes...
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
aiohttp 3.6.2 requires multidict<5.0,>=4.5, but you'll have multidict 5.0.0 which is incompatible.
[17:07:33] INFO: Installed Home Assistant 0.117.1
[17:07:33] INFO: Making a copy of your configuration for checking...
[17:07:49] INFO: Checking your configuration against this version...
[17:11:02] ERROR: The configuration check did not pass!
[17:11:02] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Failed config
  homeassistant.packages.spotcast.spotcast: 
    - Package spotcast setup failed. Component spotcast No module named 'pychromecast'
    - sensor: [source /tmp/config/packages/media_players/spotcast.yaml:9]
        - platform: spotcast
      spotcast: [source /tmp/config/packages/media_players/spotcast.yaml:1]
        accounts: [source /tmp/config/packages/media_players/spotcast.yaml:4]
          emma: [source /tmp/config/packages/media_players/spotcast.yaml:5]
            sp_dc: REDACTED
            sp_key: REDACTED
        sp_dc: REDACTED
        sp_key: REDACTED

  General Errors: 
[17:11:02] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
add pychromecast to resources
3rd run log(failed due to lack of plexapi):
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[17:14:19] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:14:19] INFO: Setup udev devices
[17:14:22] INFO: Don't worry, this temporary installation is not overwriting your current one.
[17:14:22] INFO: Installing Home Assistant: latest...
[17:14:22] INFO: Please be patient, this might take a few minutes...
[17:15:11] INFO: Installed Home Assistant 0.117.1
[17:15:11] INFO: Making a copy of your configuration for checking...
[17:16:06] INFO: Checking your configuration against this version...
[17:18:53] ERROR: The configuration check did not pass!
[17:18:53] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Failed config
  homeassistant.packages.spotcast.spotcast: 
    - Package spotcast setup failed. Component spotcast No module named 'plexapi'
    - sensor: [source /tmp/config/packages/media_players/spotcast.yaml:9]
        - platform: spotcast
      spotcast: [source /tmp/config/packages/media_players/spotcast.yaml:1]
        accounts: [source /tmp/config/packages/media_players/spotcast.yaml:4]
          emma: [source /tmp/config/packages/media_players/spotcast.yaml:5]
            sp_dc: REDACTED
            sp_key: REDACTED
        sp_dc: REDACTED
        sp_key: REDACTED

  General Errors: 
grep: write error: Broken pipe
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
Add plexapi to resources.
4th run log (failed due to lack of plexwebsocket):
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[17:51:47] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:51:48] INFO: Setup udev devices
[17:51:50] INFO: Don't worry, this temporary installation is not overwriting your current one.
[17:51:50] INFO: Installing Home Assistant: latest...
[17:51:50] INFO: Please be patient, this might take a few minutes...
[17:52:39] INFO: Installed Home Assistant 0.117.1
[17:52:39] INFO: Making a copy of your configuration for checking...
[17:53:18] INFO: Checking your configuration against this version...
[17:56:15] ERROR: The configuration check did not pass!
[17:56:15] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Failed config
  homeassistant.packages.spotcast.spotcast: 
    - Package spotcast setup failed. Component spotcast No module named 'plexwebsocket'
    - sensor: [source /tmp/config/packages/media_players/spotcast.yaml:9]
        - platform: spotcast
      spotcast: [source /tmp/config/packages/media_players/spotcast.yaml:1]
        accounts: [source /tmp/config/packages/media_players/spotcast.yaml:4]
          emma: [source /tmp/config/packages/media_players/spotcast.yaml:5]
            sp_dc: REDACTED
            sp_key: REDACTED
        sp_dc: REDACTED
        sp_key: REDACTED

  General Errors: 
grep: write error: Broken pipe
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
Add plexwebsocket.
5th run - success!

I can only assume that plex being required is related to the newly added ability to stream plex to cast devices in HA.

It may be that the config may work for some people if other components which use these resources are loaded first, but this cannot be guaranteed.

also, please note that my PR added resources, not dependencies.  I remember needing to remove resources which are loaded automatically by a base home assistant install, but it appears that these are no longer loaded by default

**Comment by fondberg** [comment]
How do you secure the HA core version of spotipy and pychromecast are installed and not spotcast versions?

It was a maintenance nightmare when i had them in the manifest.json and now it is only the checl that fails but im not breaking core everytime they upgrade a dep

**Comment by pinkywafer** [comment]
Ok, so I've been doing a bit more investigation.  I'm not sure which libs you had in requirements previously, but in my anniversaries integration, the issue with requirements was due to libs being included as part of the python release instead of "add-on" libs.  AFAIAW the config check home assistant addon works the same way as my travis CI and my github actions checkrun for the current version.  These all work by doing a python install of core on linux, not a full docker / supervised install etc, and all fail as is as I believe none of the libs in my PR are installed by default in that install method.  I haven't tried yet (but will do if I get a chance!), but I expect that anyone who has a python install of core on linux will not be able to use the integration without the requirements I have added.  Note also that I have not specified versions for the requirements, so if they are already installed, there shouldn't be a conflict

**Comment by fondberg** [comment]
HA Core will install its dependencies before any custom components deps. That means that if Core wants pychromecast version X.9 and spotcast wants X.8 it will overwrite the deps for all of HA. That was the issue before and I agrees wit core devs that I remove the deps from spotcast that are duplicates seeing as they are already installed and will get automatically updated.

I understand that the checker only checks each component of its own but as python doesn't allow for multiple version of a library version conflicts are common

**Comment by pinkywafer** [comment]
That is true, but this P.R. does not specify a version, so what happens in this case?  Is the latest version installed if available, or is the already installed version used?

Has anyone tested if the component fails on a python install (Vs supervised)?

**Comment by rohankapoorcom** [comment]
> How do you secure the HA core version of spotipy and pychromecast are installed and not spotcast versions?
> 
> It was a maintenance nightmare when i had them in the manifest.json and now it is only the checl that fails but im not breaking core everytime they upgrade a dep

@fondberg: I think we can fix this by adding the `cast` integration to the[ `after_dependencies`](https://developers.home-assistant.io/docs/creating_integration_manifest/#after-dependencies) in the manifest file. This will make sure that the `cast` integration is installed (with it's version of `pychromecast` and all of it's `after_dependencies` like plex. See https://github.com/home-assistant/core/blob/dev/homeassistant/components/cast/manifest.json

```
{
  "domain": "spotcast",
  "name": "Start Spotify on chromecast",
  "documentation": "https://github.com/fondberg/spotcast",
  "requirements": [
    "spotify_token==1.0.0"
  ],
  "homeassistant": "0.113.0",
  "dependencies": [
  ],
  "after_dependencies": [
     "cast"
  ],
  "codeowners": [
    "@fondberg"
  ]
}
```


I'm having similar validation problems using Github Actions for my configuration and in my quick testing this fixed the problem. I'll make a PR.

**Comment by fondberg** [comment]
@rohankapoorcom great! 
Didn't know about that one. 
We need to add whatever the media_player_spotify is called as well to get spotipy.

**Comment by rohankapoorcom** [comment]
@fondberg Yes - I added spotify as well in https://github.com/fondberg/spotcast/pull/144
