### ISSUE TITLE
Possibility to "Transfer Playback" even when there is nothing currently playing

### ISSUE THREAD

**Issue by almostserious** [fondberg/spotcast#14]
Transfer Playback works great when something is already playing (or was playing very recently).
However, if there is no active session, nothing will start when transfer playback is sent.

The behaviour of Google Home when i ask to play Music from Spotify is that it will always continue on where i last stopped. Even if there is a long time between the last time i listened to something on Spotify.

Is it possible to copy this behaviour?

**Comment by fondberg** [comment]
Oh. This is a slightly more advanced use case that I think deserves it's own feature issue ticket. 
The logic is right now is asking the spotify web api if there is something playing and if True then transfer otherwise not. 

If you can dig out which API call that takes the last playback I think we. An add it

**Comment by almostserious** [comment]
https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/
This seems promising. Only one of either context_uri or uris can be specified. If neither is present, calling /play will resume playback.

**Comment by fondberg** [comment]
This is what is done already and it takes the URI sent in. First resuming playback from the last played we need some history api.

Or am I misunderstanding your use case? Can you describe the use case in detail?

**Comment by almostserious** [comment]
I understood the Spotify reference like this: If no context URI, or normal URI is given, then it will simply resume playback where it last stopped. So its not needed to know where the user last stopped.

Use case would be:
1. Listening to Spotify in the Car.
2. Stop Playback @ arrival.
3. Some time goes by.
4. Arrive Home - Trigger Resume Playback
5. Play resumes on new device exactly where the Spotify stopped in the Car.

This is how it works when simply asking Google Home to Play Music from Spotify.

Question is: Will Spotify be able to handle it automatically? Or do we need the send the URI of the "Track or Playlist" we listened before, and also the context URI to select the correct offset? i.e.: Start Playback of Playlist "XY" @ Position "5"

Within the normal Spotify component, if i just press play it will also simply resume whatever it was playing before. It also works with the spotcast component for a short amount of time. I have not yet found out after what time period it times out.

Dirty workaround could be to simply continue & pause playback first on a different speaker, and then call the spotcast component shortly after.

**Comment by fondberg** [comment]
Aha. Understand. I think we can easily test with starting spotify and omitting the context-uri and see if it picks up. That would be sweet. 
Something I would like is some kind of randomness as well with playing from a random position in a random playlist but that is very much different from this.

**Comment by almostserious** [comment]
Yes i just did that :) Works perfectly. So before i call the Spotcast component, i do a service call for media_player.select_source and put it to another spotify client. This wakes up spotify without playing it anywhere. Then Spotcast can transfer the playback.  Theoretically also the random function could be called at this stage. However, this would only work after skipping to the next track once.

**Comment by fondberg** [comment]
note: the feature would be to transfer even if nothing is playing, that is remove check for something playing

**Comment by kleinc80** [comment]
PR #62 tackles this in an easy way (easy means little change to the code).

**Comment by kleinc80** [comment]
> Randomness/offset

Offset has been added in 2.8.0, @almostserious !

**Comment by fondberg** [comment]
will release soon

**Comment by rhgiter** [comment]
thanks for this , but after the update I cant get trasfer to work. ?  does this look right ? i have it on another location with a different speaker. with same automation. but it starts a new music number instead of resume it 

account: freya
entity_id: media_player.badevaerelse
force_playback: true
offset: 1
random_song: true
shuffle: true
uri: 'spotify:playlist:7qVdbj9nAMyffB7kxVJwnF'

**Comment by fondberg** [comment]
Try both true and false on force_playback. I don't remember what it should be for a transfer.
Also check your logs to look for errors

**Comment by rhgiter** [comment]
Thanks   but I can't get it to work.  No log errors.     music plays fine , but no transfer...

**Comment by jhhernan** [comment]
Hi! First of all, it`s a great feature. I have two issues:
1. There is no info in my sensor, it`s always empty (devices_json: []) It updates regularly but is has no info on it.
2. Im using force_playback=false but it always resume (plays) the music even though the music is paused in the previous device.

**Comment by fondberg** [comment]
In some cases Spotify doesn't permit transfer. 

@kleinc80 can you shed some light on how you got it work seeing as you are the one that did the change?

**Comment by kleinc80** [comment]
Hi @jhhernan,

If you provide an uri it will start to play in all cases.
If you don't provide an uri **and** use force_playback=false it will check for the current playback:
```
            current_playback = client.current_playback()
            if current_playback is not None:
                _LOGGER.debug('Current_playback from spotipy: %s', current_playback)
                force_playback = True
```
I haven't checked it myself but it could be current_playback is not null if you are pausing. Could you check that for us by increasing the log level and looking what the logs from the piece of code above look like?

Thanks!
 Christian

**Comment by jhhernan** [comment]
Sorry. Kind of lost. Where do I change the log level? You`re asking for the home assistant log or another log?

Thanks!

**Comment by kleinc80** [comment]
Yeah, right. HA Core's logger integration should do: https://www.home-assistant.io/integrations/logger/

**Comment by fondberg** [comment]
Did you get this to work @jhhernan ?

**Comment by fondberg** [comment]
Closing as this is supported and documented
