### ISSUE TITLE
Feature request: AirPlay support

### ISSUE THREAD

**Issue by kimme1024** [fondberg/spotcast#146]
As I'm trying to use HA to control my Spotify playback I found spotcast.
However my receiver (Yamaha RX-V675) only supports AirPlay instead of Spotify Connect so I'm searching for an option to make my receiver appear in the list of possible speakers.
I don't know it would be possible for you to implement this in de future?
If not, no problem of course!

**Comment by fondberg** [comment]
Airplay is different that chromecast and it is not possible to add support for it in spotcast. Sorry
