### ISSUE TITLE
Gapless playback or cross fade 

### ISSUE THREAD

**Issue by will-l-h** [fondberg/spotcast#149]
I use this to cast pink noise or nature sounds and while I can find some tracks that are an hour or more long, it would be great if gapless playback and/or crossfade was supported for looping a track without the interruption that currently comes up.

**Comment by fondberg** [comment]
Could you explain more what you mean? Is this something that would be an attribute to the service call?

**Comment by fondberg** [comment]
I looked in their API and it is not supported to set cross fade or gapless play from the Web API. It is a client playback setting apparantly
