### ISSUE TITLE
Status of media_player.home_mini does not change upon starting a playback

### ISSUE THREAD

**Issue by kriss1897** [fondberg/spotcast#152]
Calling `spotcast.start` with relevant data, and the playback starts. But the media_player (speaker) state is not updated. Also cannot control the playback with Google Assistant or Device Controls. The only way to stop/control playback is from spotify app or spotify card.

**Comment by fondberg** [comment]
State is not spotcast fault. That needs to be reported to core HA media_player spotify.

The controls needs to be reported to Google. You can use the Spotify apis to control it so it is not spotcast fault
