### ISSUE TITLE
Unable to install package spotify_token==1.0.0:

### ISSUE THREAD

**Issue by psamp3** [fondberg/spotcast#153]
Logger: homeassistant.util.package
Source: util/package.py:95
First occurred: 7:38:24 PM (1 occurrences)
Last logged: 7:38:24 PM

Unable to install package spotify_token==1.0.0: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xb4bb9d18>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/spotify-token/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xb4bb9bb0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/spotify-token/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xb4bb9a78>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/spotify-token/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xb4bb9a60>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/spotify-token/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xb4bb9910>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/spotify-token/ ERROR: Could not find a version that satisfies the requirement spotify_token==1.0.0 (from versions: none) ERROR: No matching distribution found for spotify_token==1.0.0 WARNING: You are using pip version 20.2.4; however, version 20.3 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

**Comment by fondberg** [comment]
Can't reproduce this. Try again because it seems like a network issue
