### ISSUE TITLE
allow hard-coding of speaker IP address (ignore mDNS auto-discover)

### ISSUE THREAD

**Issue by keiranharris** [fondberg/spotcast#156]
Hi, not sure if this is possible. I might be quite the corner case here, but here goes anyway..... 

I am running HASS inside of docker. My networking design inside of docker does NOT expose the HASS container to the outside world (i.e. no --net=host), and all ingress traffic comes in via NGINX first (another docker container) acting as a reverse proxy. This works great! except it breaks just this component. 

I assume the problem is the mDNS announce packets from speakers aren't making to the container in my setup. These announce packets look like: 
   speakers-> 224.0.0.251:5353  (udp). 

Have tried all docker networking variants to get this to work. No dice. 

So.... .what I was wondering, would you consider the feature request to allow us to hard-code a given speaker IP address in the yaml, rather than relying on the auto-discover from the mDNS packets on the local LAN?  

thanks in advance! 
Keiran.

**Comment by keiranharris** [comment]
Got a workaround going (avahi container injecting mDNS from real world into docker world). For anyone else that stumbles into this situation in future

See >>> https://github.com/flungo-docker/avahi/issues/2

I can see my speakers again!

**Comment by DarthSmeg** [comment]
I had the same issue, and your post helped me! Thanks!

I was a bit confused where you got the "--opt parent=ens3" from, as I could not see that interface name anywhere in your screenshots, but used the name if my wifi-device and it worked right away :D

**Comment by keiranharris** [comment]
Great to hear! Yup for me ens3 is the NIC which points into my inside real network (10.1.3.x LAN). Sounds like you sorted it. Glad it helped you too.

**Comment by fondberg** [comment]
If you are talking about chromecast then i would say it needs support in pychromecast because I only reuse the already discovered devices in HA

**Comment by keiranharris** [comment]
Yeah they are chromecast speakers yup. But all good i have a workaround, and in fact the “workaround” is probably the *correct* way to do things. So yup, ignore this, but hopefully the raising of the issue will help others find the same way to do “fix” this.

**Comment by hmmbob** [comment]
I think this has been implemented in HA with this PR:

https://github.com/home-assistant/core/pull/47232

**Comment by keiranharris** [comment]
Awesome thanks for looping back and telling me @hmmbob ! This will allow me to dismantle an arguably over baked setup i have right now. Stupid question though- i can see the PR was merged march 2nd. How can i find what mainline release of HASS this is included? (Github question more than anything else)

**Comment by hmmbob** [comment]
I'd bet on 2021.4, given the date of merge and the fact that's new functionality. The changelog will be a good point to check - I don't know another way too 😄

**Comment by fondberg** [comment]
I'm closing this as I don't want to have special cases for Cast devices. They cause too much trouble
