### ISSUE TITLE
Spotify Connect device not listed

### ISSUE THREAD

**Issue by marcianito** [fondberg/spotcast#157]
Hey,

First of all thanks for your 2 awesome projects with spotcast and the lovelace spotify card! I am using those and am amazed!
I have a question I haven't found much information about in the net.
I have several Spotify Connect devices in my WLAN, one of them is my phone with Spotify app installed. But I also have another server running a snapcast-librespot device. This is listed and works when selecting from my phone Spotify app but is NOT listed within HA (e.g. drop down menu from spotify card).
Am I missing something? Do I have to manually configure this device?
All I have is the ip from the Pi running the snapcast-librespot connect service and its device name (as shown in spotify app).

Any hints or advices as also explanations are more than welcome!

Thanks already and keep up this great work! :)

**Comment by fondberg** [comment]
Librespot needs to be configured with username and password otherwise it is not a true connect device
