### ISSUE TITLE
[FR] - sonos speaker usage

### ISSUE THREAD

**Issue by jaburges** [fondberg/spotcast#165]
The spotify card / spotcast combo is Killer! Nice work.
If I already have sonos integrated, and its showing up as a media_player in HA, is there a way to add those devices manually to the device list?

**Comment by jaburges** [comment]
Is the spotify connect list generated from somewhere outside my network or inside my network? not sure if it is still the case, but Spotify connect only works if it can see the devices on the LAN. 
I can verify the sonos devices show up in the sonos app as "Spotify Connect" devices, but not seeing them in the spotcast device list :( 

any thoughts?

**Comment by fondberg** [comment]
Sonos uses it own protocol so it can't be supported with chromecast

**Comment by fondberg** [comment]
Closing. Feel free to open a PR

**Comment by jaburges** [comment]
> Sonos uses it own protocol so it can't be supported with chromecast

Is this local or cloud based @fondberg as sonos devices show up as spotify sources when on the LAN.
