### ISSUE TITLE
Setting shuffle to false doesn't deactivate it

### ISSUE THREAD

**Issue by TommiPio** [fondberg/spotcast#166]
Hi, yesterday I noticed that passing "shuffle": True to the service activate perfectly the shuffle mode, but I couldn't find a way to toggle it off, nor with "shuffle": false nor by toggling it again with true value. 

Is it possible to make it togglable in some way?

**Comment by fondberg** [comment]
You can turn it off on an ongoing playback using the builtin spotidy integration in HA.
For new sessions you can omit shuffle in the service call. _should_ work I think....
