### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'spotcast'

### ISSUE THREAD

**Issue by GuyKh** [fondberg/spotcast#169]
On HomeAssistant 2021.3.0:

```
No 'version' key in the manifest file for custom integration 'spotcast'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'spotcast'
```

https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes outlines the information as for why

**Comment by fondberg** [comment]
Hi! Been sick. I will have a look at this soon. What exactly is required?

**Comment by fondberg** [comment]
https://github.com/fondberg/spotcast/releases/tag/v3.4.7
