### ISSUE TITLE
Cant start spotcast on chromecast device.

### ISSUE THREAD

**Issue by joshix3m** [fondberg/spotcast#182]
Version Homeassistant:  2021.4.3
Spotcast:  v.3.5.2

Stopped working on latest update:

Trying to run script to start playback on Google Mini

```
wakeup_spotify_oliver:
  alias: Kjør vekkesang for Oliver
  sequence:
  - service: spotcast.start
    data:
      entity_id: media_player.rommet_til_oliver
      uri: spotify:playlist:4oAD9NGqlOj87mbkMko52b
      random_song: true
      start_volume: 70
  mode: single
```

I have tried switching from entity_id to device_name with same issue:

Log error as follows:

Logger: homeassistant
Source: custom_components/spotcast/__init__.py:564
First occurred: 10:51:58 (3 occurrences)
Last logged: 12:39:55

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 392, in _async_run
    return await self.script.async_run(variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1195, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1519, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 377, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(client)
  File "/config/custom_components/spotcast/__init__.py", line 564, in getSpotifyDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not iterable
```

**Comment by DONRozeboom** [comment]
Following

**Comment by MagicMicky** [comment]
Can you try to:
* Uninstall spotcast, remove current credentials and configuration
* Uninstall spotify integration, remove current credentials and configuration
* Create a new app on the Spotify Developer console (https://developer.spotify.com/dashboard/applications)
* Reinstall Spotify with the new credentials (follow https://www.home-assistant.io/integrations/spotify/ onboarding)
* Reinstall spotcast, with new credentials (follow this repo onboarding)

This ended up fixing this exact issue for me (see: https://github.com/fondberg/spotcast/issues/174#issuecomment-817341138)

**Comment by mcfly2283** [comment]
For me, renewing Spotify-Integration with new Application and Credentials from Spotify-Dev fixed that Problem immediately.

**Comment by DONRozeboom** [comment]
> Can you try to:
> 
> * Uninstall spotcast, remove current credentials and configuration
> * Uninstall spotify integration, remove current credentials and configuration
> * Create a new app on the Spotify Developer console (https://developer.spotify.com/dashboard/applications)
> * Reinstall Spotify with the new credentials (follow https://www.home-assistant.io/integrations/spotify/ onboarding)
> * Reinstall spotcast, with new credentials (follow this repo onboarding)
> 
> This ended up fixing this exact issue for me (see: [#174 (comment)](https://github.com/fondberg/spotcast/issues/174#issuecomment-817341138))

Interestingly enough, that worked. Which is strange, because I didn't even have the Spotify integration installed. But cheers for the quick tip mate.

**Comment by joshix3m** [comment]
I also got it working when installing the Spotify-integration. Been using spotcast whitout this integration for quite som time. Something changed that made it a requirement?

Anyway. Got it working :)

**Comment by fondberg** [comment]
Yes! We now need the devices from spotify media player as it has the correct scopes in its token.

**Comment by robtesch** [comment]
Can we please update the docs to specify that the spotify integration is now required?

**Comment by hmmbob** [comment]
The great thing of open-source: you can do this too!

https://github.com/fondberg/spotcast/blob/master/README.md

**Comment by robtesch** [comment]
> The great thing of open-source: you can do this too!
> 
> https://github.com/fondberg/spotcast/blob/master/README.md

Yes yes, I know, but seeing as I haven't even made this fix/change yet I don't want to put the wrong instructions in there. Once I've done so I will submit a PR.

**Comment by robtesch** [comment]
PR submitted

**Comment by parlov** [comment]
Don't forget to "register" your chrome cast device into your home assistant system. That solved my problem
