### ISSUE TITLE
KeyError: 'spotcast'

### ISSUE THREAD

**Issue by Spankythemusical** [fondberg/spotcast#192]
HA - 2021.4.4
Spotcast - 3.5.2

Spotcast will no longer load.  I have not made any changes or integration additions within the past week, just the upgrade of HA.  

This are the errors that are shown on the log page:

```
Logger: homeassistant.setup
Source: setup.py:308
First occurred: 1:23:09 PM (1 occurrences)
Last logged: 1:23:09 PM

Unable to prepare setup for platform spotcast.sensor: Unable to set up component.
```

```
Logger: homeassistant.setup
Source: custom_components/spotcast/__init__.py:170
First occurred: 1:23:09 PM (1 occurrences)
Last logged: 1:23:09 PM

Error during setup of component spotcast
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/setup.py", line 241, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/spotcast/__init__.py", line 170, in setup
    conf = config[DOMAIN]
KeyError: 'spotcast'
```

I did a reinstall of Spotcast, but the errors remain.  Any ideas?

**Comment by fillwe** [comment]
Same issue here after 2021.4.4 upgrade

**Comment by fondberg** [comment]
I can't reproduce this. Make sure you have updated spotcast to the latest

**Comment by Spankythemusical** [comment]
HACS goes as far as 3.5.2.  I manually installed 3.5.3, but received the same errors.  

If I downgrade to 3.4.7, I go back to receiving the `ImportError: cannot import name 'KNOWN_CHROMECAST_INFO_KEY' from 'homeassistant.components.cast.media_player'` error

**Comment by hmmbob** [comment]
How does your Spotcast configuration look like in configuration.yaml?

**Comment by Spankythemusical** [comment]
Well color me embarrassed!  I guess I commented out the spot cast entry in my configuration.yaml due to the last issue.  Never went back to uncomment after the upgrade.  I will hang my head in shame and show myself to the door.

thank you for your help with this.
