### ISSUE TITLE
`get_spotify_devices` does not handle multiple account

### ISSUE THREAD

**Issue by maxenced** [fondberg/spotcast#200]
[get_spotify_devices](https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/__init__.py#L120) is not able to filter on a per-account basis. Thus, when using multiple accounts, [websocket_handle_player](https://github.com/fondberg/spotcast/blob/5c746da55684feb3bf311f9700be62bc57d7dc9d/custom_components/spotcast/__init__.py#L236) will return the same informations no matter which `account` parameter is sent.

This breaks spotify card when using multiple accounts.

Not sure what would be the best way to filter account here. We can access the `me` properties from spotify entity, but not sure how to match with account. 

Happy to test/submit a PR if you have any idea about how we could filter ?

**Comment by fondberg** [comment]
This is a known issue after using the devices from core Spotify

**Comment by maxenced** [comment]
Good to know it known. Still, can I help to fix that ? Looks like the key is to match the correct account from core spotify. Not sure how this can be done ?

**Comment by fondberg** [comment]
Can you have several accounts for the core spotify player? If so we can solve it otherwise it will not work and needs to get removed in spotcat

**Comment by hmmbob** [comment]
I am using 3 accounts in Core Spotify. In the debug logs I posted on another issue thread, you can see all three actually show up.

**Comment by maxenced** [comment]
Not sure what you call core spotify, if it's https://www.home-assistant.io/integrations/spotify/ then yes, multiple account are well supported (and you get one media_player entity for each)

**Comment by nolenjohan** [comment]
I could not use second account with 3.5.6 so I backed to 3.5.2 and now also the second account works fine. I have two Spotify accounts and nine Chromecasts, everything seems to be working fine now.

**Comment by jonasjeeliasson** [comment]
> I could not use second account with 3.5.6 so I backed to 3.5.2 and now also the second account works fine. I have two Spotify accounts and nine Chromecasts, everything seems to be working fine now.

Same for me. Using two accounts works fine on 3.5.2. I've got two spotify media players, and configured two accounts in spotcast. Using together with spotify-card works well.

**Comment by fondberg** [comment]
So basically someone needs to map a spotcast username to the correct core spotify entity.  Any ideas?

**Comment by hmmbob** [comment]
Well, it makes sense to use the same name in both places. This is what I find in .storage/core.config_entities:

```json
             {
                "entry_id": "e907a3399494fa660d80beba856ecc48",
                "version": 1,
                "domain": "spotify",
                "title": "Hmmbob",   # This is the name of the core Spotify config
                "data": {
                    "auth_implementation": "spotify",
                    "token": {
                        "access_token": "redacted",
                        "token_type": "Bearer",
                        "expires_in": 3600,
                        "refresh_token": "redacted",
                        "scope": "playlist-read-private playlist-read-collaborative user-modify-playback-state user-library-read user-follow-read user-read-playback-state user-read-recently-played user-read-playback-position user-read-private user-top-read",
                        "expires_at": redacted
                    },
                    "id": "222nd5tac52l5qarrtzrujcxx", # this matches the 'username' in the spotify web interface
                    "name": "Hmmbob" # this shows in the top right in the sportify web interface
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "cloud_poll",
                "unique_id": "222nd5tac52l5qarrtzrujcxx", # again, this matches my username
                "disabled_by": null
            },
```

**Comment by maxenced** [comment]
the match on username should do the trick. If we want to simply filter on entity name, the default entity name for spotify integration seems to be `media_player.spotity_<username>`

**Comment by hmmbob** [comment]
Yet I wouldn't rely on the `media_player.spotity_<username>` name though, as it can be easily renamed to something else. If we are matching accounts between Spotcast and core Spotify, it has to be based on the `id`, `name` or `unique_id` fields marked above, in my humble opinion.

`name` appears to be most user friendly, yet `unique_id` is most robust. We'll have to update the docs on how to find that `unique_id` though, as it isn't stored in any of the cookies I found.
