### ISSUE TITLE
Syntax error in __init__.py

### ISSUE THREAD

**Issue by lytryx** [fondberg/spotcast#203]
Hi, first thanks for sharing the work, it's great
Just comment on a syntax error that the integration has reported to me, in case it helps someone.

 "syntax error in line 562 of __init__.py"
![image](https://user-images.githubusercontent.com/48161459/116278991-4e3d5d00-a787-11eb-8347-e17f711f1625.png)

I changed ":" to "=" and it started working correctly.

TKS

**Comment by hmmbob** [comment]
That operator is introduced in Python 3.8, which is also the minimum python version Home Assistant supports. Recommend to update your Python installation.

**Comment by lytryx** [comment]
Yes, I have it pending.. thanks for the recommendation.

TKS
