### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by andreaso19** [fondberg/spotcast#21]
Hi! 

Thanks so much for the awesome component BUT
I can't finish the install. I manage to get the files into the custom folder, and a succesful restart. afterwards when I edit the config I can't access hass, and have to delete the component and restart. 

Thanks in advance from a total noobie...

**Comment by fondberg** [comment]
Can you attach the relevant log lines where hass fails to start?

**Comment by andreaso19** [comment]
after 5 reinstalls I seemed to get it working. Plz close.
