### ISSUE TITLE
Feature Request: add media_position and media_position_updated 

### ISSUE THREAD

**Issue by jokerigno** [fondberg/spotcast#213]
Hi,

as described in the object I ask you if you can add media_position and media_position_updated to a future release.

Moreover it would be great to add somehow visibility of the user that triggered spotcast to restart music with same account.

Thank you

**Comment by fondberg** [comment]
is this same as position_ms offset to start the playback?

**Comment by fondberg** [comment]
Is the first request the same as #163 ?
The second you can get from the HA core spotify media player if you set it up with all your accounts.
Spotcast doesn't store any state so it is the wrong place for it
