### ISSUE TITLE
[Feature Request] Expose Spotify Connect devices

### ISSUE THREAD

**Issue by amitkeret** [fondberg/spotcast#216]
Thank you for this component, it's extremely useful!

It would be helpful to have an exposed `sensor.spotify_connect_devices` entity, much like `sensor.chromecast_devices`.
Having the ability to fetch this list, including each device's Spotify unique ID would be useful.

My goal: to be able to fetch a combined list of all devices (Connect and Chromecast) with their Spotify unique IDs, and feed that back as `data: spotify_unique_id: []` to an action call `service.spotcast`.

Thank you

**Comment by LifeBandit666** [comment]
Hey, Check out this I posted on Reddit, might help https://redd.it/ni1gw1

**Comment by amitkeret** [comment]
Thanks @LifeBandit666 
I've looked into that solution before :) Unfortunately, it seems these IDs are not persistent; they change every day or so.
I've previously configured an action with one of these IDs, it worked initially and then stopped working once the ID has changed on Spotify's backend.

**Comment by fondberg** [comment]
You don't need the IDs. device_name will look first at your spotify connect devices and only if it is missing will it look for chromecast devices.

Why do you need the spotify_device_id?

**Comment by LifeBandit666** [comment]
device_name never worked for me fondberg, that's why I went down the rabbit-hole to find the Spotify connected IDs. and amitkeret my solution gives you exactly what you're asking fondberg for. It's still working for me a week later for my Chromecast and Raspotify devices.

**Comment by fondberg** [comment]
Unless you have named your device weirdly it should work.
Also if you enable debug logging you will see a line called "get_spotify_devices" which contain all the spotify devices for that account as received by their API

**Comment by LifeBandit666** [comment]
I've gone back and tried again with device names, and managed to get it working no trouble. 

It seems the Spotify device ID (the numbers referenced in my Reddit post and here) only work if they're one of the last 3 devices used by Spotify. It must use the same developer API referenced in my post. 

Device names on the other hand seem to work (so far) as long as Spotify can see them on the network. Mine drop in and out sometimes. 

Not sure why the names didn't work before but it seems a better method (so far anyway).

Thanks for this, it was pretty cool before with just my Chromecasts, but now I can cast Spotify anywhere with a Lovelace button or automation.

**Comment by fondberg** [comment]
Closing this as it works as wxpected
