### ISSUE TITLE
Spotcast Broken after updating to 2021.6.4

### ISSUE THREAD

**Issue by ranrinc** [fondberg/spotcast#222]
**Describe the bug**

* [x] Using the latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**
It fails to run and the error log showed problem which is not present in previous version 2021.6.3

**Environment (please complete the following information):**
 - HA version: [ 2021.6.4 ]
 - spotcast version: [ 3.6.10 ]

**Additional context**
error log
```
File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 51, in setup
    spotcast_controller = SpotcastController(hass, sp_dc, sp_key, accounts)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 158, in __init__
    accounts["default"] = OrderedDict([("sp_dc", sp_dc), ("sp_key", sp_key)])
TypeError: 'NoneType' object does not support item assignment
```

**Comment by rexer78** [comment]
I have the same problem, I'm returned to the previus version 3.5.10 and all work fine.

**Comment by wannesmarynen** [comment]
if you are willing to fix it yourself you could go to the filespotcast controller and replace the function __init__ with this:

    def __init__(self, hass, sp_dc, sp_key, accounts): 
        if accounts:
            self.accounts = accounts
        self.accounts["default"] = OrderedDict([("sp_dc", sp_dc), ("sp_key", sp_key)])
        self.hass = hass

that fixed it for me

**Comment by fondberg** [comment]
Released new version
