### ISSUE TITLE
Spotcast can't start after

### ISSUE THREAD

**Issue by javiges** [fondberg/spotcast#227]
**Describe the bug**

* [x ] Using latest version of spotcast
* [ x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x ] Using latest stable version of Home Assistant
* [ x] I have Spotify Premium
* [ x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**

2021-06-13 21:59:12 ERROR (MainThread) [homeassistant.setup] Error during setup of component spotcast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 51, in setup
    spotcast_controller = SpotcastController(hass, sp_dc, sp_key, accounts)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 160, in __init__
    accounts["default"] = OrderedDict([("sp_dc", sp_dc), ("sp_key", sp_key)])
TypeError: 'NoneType' object does not support item assignment

**Environment (please complete the following information):**
 - HA version: [2021.6.4 ]
 - spotcast version: [3.6.12 ]

**Configuration**
Add your configuration

**Additional context**

**Comment by javiges** [comment]
Logger: homeassistant.setup Source: custom_components/spotcast/spotcast_controller.py:160 Integration: spotcast (documentation, issues) First occurred: 21:59:12 (1 occurrences) Last logged: 21:59:12  Error during setup of component spotcast Traceback (most recent call last):   File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component     result = await task   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run     result = self.fn(*self.args, **self.kwargs)   File "/config/custom_components/spotcast/__init__.py", line 51, in setup     spotcast_controller = SpotcastController(hass, sp_dc, sp_key, accounts)   File "/config/custom_components/spotcast/spotcast_controller.py", line 160, in __init__     accounts["default"] = OrderedDict([("sp_dc", sp_dc), ("sp_key", sp_key)]) TypeError: 'NoneType' object does not support item assignment

**Comment by jonathanrobichaud4** [comment]
I have the same issue

**Comment by wannesmarynen** [comment]
@fondberg i added the check if the accounts is not null but i just get skipped for some reason very weird i can not explain it it should work

**Comment by javiges** [comment]
I have returned to version 3.5.10 which is the last one that works, until we wait for a solution, great job, surely you will fix it soon

**Comment by wannesmarynen** [comment]
i think i found it just testing it locally and then i will make the pull request for the fix

**Comment by javiges** [comment]
perfect, everything fixed in the last update, thanks team, throughout the day I will test it
