### ISSUE TITLE
Spotcast stops playing after approximately 1 hour

### ISSUE THREAD

**Issue by XalaTheShepard** [fondberg/spotcast#237]
Dear all, 

I am currently running Spotcast version 3.6.14 and version 2021.07.3 of HA, but this issue also occurs in older versions of both.
The Spotify integration is installed in Home Assistant and I use only one account.
After approximately casting Spotify via Home Assistant to my Google Home, the music stops playing. 
I have no issues restarting a playlist, but always after approximately one hour of playing the casting stops.
When I check the logs for the reason the casting stops, no error or warning message is shown.
According to the information I have gathered, the reason might be due because the Spotify token needs to be refreshed hourly.
Is this something that can be solved?

Many thanks for the feedback. 

Kind regards

**Comment by ASNNetworks** [comment]
This can't be solved and has been addressed multiple times. Should be mentioned in the ReadMe. The token expires after one hour, which means the music stops and you need to call the service again. When you start listening, it generates a token that is valid for one hour. It won't generate a new one if you stop and start within the hour as far as I know. So this is why sometimes it might feel less than an hour (if you start, play for 10min and then stop for 20, and then play again, you have 30min playback left till token expires and it stops).

Fondberg has mentioned there is no way around this at the moment the way the Spotify API works.

**Comment by skipishere** [comment]
Lots of information about this in issue #13

**Comment by fondberg** [comment]
https://github.com/fondberg/spotcast/issues/13
