### ISSUE TITLE
Transfert playback only add another device

### ISSUE THREAD

**Issue by thib5** [fondberg/spotcast#25]
Hi ! your component is awesome I try to achieve this since a have a google home ( like 3 year ago ) 

I have a lite automation that allow me to switch music between device. but let say the music is playing in the kitchen and I want to switch it to the bedroom then It will play in the bedroom AND in the kitchen ... is it normal ? this is my automation : ( I have the same automation for every google home that I can select with a input select )

- alias: transfer_playbackChambre_GH
  trigger:
    platform: state
    entity_id: input_select.spot_device
    to: 'Bedroom GoogleHome'
  action:
  - service: spotcast.start
    data:
      device_name: 'Bedroom GoogleHome'
      transfer_playback: true

**Comment by fondberg** [comment]
That is weird... unless you have a cast group you have created which you cast to...

Which version of HA and the component are you running? It might be related to a dependency.

**Comment by fondberg** [comment]
have you solved it?

**Comment by neomvll** [comment]
> That is weird... unless you have a cast group you have created which you cast to...
> 
> Which version of HA and the component are you running? It might be related to a dependency.

Hi, I have a cast group in my google home(3 for now) and everytime I try change the playback to group, the music pauses. 
So changing between google home devices is working very well, but not in a group.
Any tip?
