### ISSUE TITLE
Question about config

### ISSUE THREAD

**Issue by augustocdias** [fondberg/spotcast#253]
In this section of the docs:

```
ignore_fully_played (optional) true or false, true to ignore already fully played episodes (defaults to false and play the latest released episode)
```
Does that mean that false will only play the latest episode and true will play all already played ones?

**Comment by icarome** [comment]
False will mean that it will play the latest released episode regardless of it had been already fully played or not. 
True will play the latest episode that hasn't been played yet. Regardless of which option you choose the spotify will play through the episodes
