### ISSUE TITLE
looking for co-maintainers. 

### ISSUE THREAD

**Issue by fondberg** [fondberg/spotcast#254]
If you think you can help out with testing and releasing plz add a comment below.
Tldr I have for personal reasons right now not the time for the tlc needed for this project

**Comment by kylepotts** [comment]
I don't mind helping. I'm a bit busy myself at the moment but could help contribute where I can.

**Comment by Darkfull-Dante** [comment]
I'm also interested

**Comment by fondberg** [comment]
Great! I'll add you so you! releasing simple in github after a merge to master with new release number

**Comment by Darkfull-Dante** [comment]
Hi @fondberg, appart from the `make bump` do you have a particular workflow for updates that you would like to keep? I could work on documentation to future proof a procedure.

**Comment by fcusson** [comment]
closing since impossible for me to add co-maintainer
