### ISSUE TITLE
Support for Daily Mix and other "Made For You" playlists

### ISSUE THREAD

**Issue by DarkFox** [fondberg/spotcast#26]
I tried to play one of my Daily Mix playlists (using the method described here to convert the URI: https://community.spotify.com/t5/Other-Partners-Web-Player-etc/Daily-Mix-URL-URI/td-p/1603513 ), but got an error that the URI was unsupported.

Is this something that's possible to add support for? I use my generated playlists a lot. :)

**Comment by fondberg** [comment]
What format and what api is used? Is it a context playback like playlists? If so, did you try using the suggestion on your link with spotify:station:user:<user>:cluster:<id>?

**Comment by DarkFox** [comment]
I used the spotcast.start service to start it with this data:

```
{
  "entity_id": "media_player.kokken_mini",
  "uri": "spotify:station:user:jwax76ge2kmnf6i8stafzjs7y:cluster:63CKJupWvSUWEP0hvDltks"
}
```

This is the resulting error:

```
http status: 400, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=5042a72e5b994534acf73d47303db32b:
 Non supported context uri

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 121, in _internal_call
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.spotify.com/v1/me/player/play?device_id=5042a72e5b994534acf73d47303db32b

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1150, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1174, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 200, in start_casting
    play(client, spotify_device_id, uri, random_song)
  File "/config/custom_components/spotcast/__init__.py", line 115, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 948, in start_playback
    return self._put(self._append_device_id("me/player/play", device_id), payload=data)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 190, in _put
    return self._internal_call('PUT', url, payload, kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 126, in _internal_call
    headers=r.headers)
spotipy.client.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=5042a72e5b994534acf73d47303db32b:
 Non supported context uri
```

**Comment by fondberg** [comment]
Is it working if you use the lir dev console and if so which api works?
It seems.the context uri method is the one which borks out the request...

**Comment by fondberg** [comment]
I think I know what is wrong... The link you sent is very old and spotify has consolidated everything into tracks and playlists for their URIs. 
Read more here https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/

Bottomline is that it is already supported. If you in https://open.spotify.com/browse/featured click the title of for instance "Discover Weekly" it will bring you to a three dot menu which allows you to copy the URL. 
<img width="571" alt="Screenshot 2019-08-09 at 16 16 34" src="https://user-images.githubusercontent.com/10739838/62785570-33155000-bac1-11e9-9e74-9d85e4c14038.png">

This URL will contain an ID at the end which you use in the URI sent to spotcast
Example:
copied link: https://open.spotify.com/playlist/XYZXYZ123
spotcast URI: spotify:playlist:XYZXYZ123

This means it is already supported today so I'm closing this now
