### ISSUE TITLE
Cookie process

### ISSUE THREAD

**Issue by freekeys** [fondberg/spotcast#270]
Hello, my cookies have just expired after 12 months and I’m struggling to get new ones. I’m following the process as per the docs (which I think is the same as a year ago) in Chrome developer tools but there is no sp_key and sp_dc cookie coming up. Anyone know if this process has changed? Thanks!

**Comment by hmmbob** [comment]
I tried this just moments ago, and instructions are fine - cookies are in the exact space they are supposed to be.

**Comment by freekeys** [comment]
Thanks - just tried the non-incognito way and it’s worked for me!
