### ISSUE TITLE
device_state_attributes deprecated implementation

### ISSUE THREAD

**Issue by amitkeret** [fondberg/spotcast#273]
**Describe the bug**
During bootup, the following deprecated configuration generates this warning:
```
Entity sensor.chromecast_devices (<class 'custom_components.spotcast.sensor.ChromecastDevicesSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.playlists_sensor (<class 'custom_components.spotcast.sensor.ChromecastPlaylistSensor'>) implements device_state_attributes. Please report it to the custom component author.
```

* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**

**Environment (please complete the following information):**
 - HA version: 2021.12
 - spotcast version: 3.6.21

**Comment by hmmbob** [comment]
Fix already in https://github.com/fondberg/spotcast/pull/271, waiting to get merged and released
