### ISSUE TITLE
No more Devices and playlist after upgrade HA to core-2021.12.0

### ISSUE THREAD

**Issue by Electronlibre2012** [fondberg/spotcast#274]
**Describe the bug**

* [ x]  Using latest version of spotcast
* [ x ] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [ x ] Using latest stable version of Home Assistant
* [ ] I have Spotify Premium
* [ x ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**

No more devices in the list and no more playlists after update to Home Assistant  core-2021.12.0

Update for sensor.chromecast_devices fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/sensor.py", line 51, in update
    chromecasts = [
  File "/config/custom_components/spotcast/sensor.py", line 56, in <listcomp>
    "model_name": cast_info.model_name,
AttributeError: 'ChromecastInfo' object has no attribute 'model_name'

**Environment (please complete the following information):**
 - HA version: [ 2021.12.0 ]
 - spotcast version: [ v3.6.21 ]

**Configuration**
spotcast:
  sp_dc: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  sp_key: xxxxxxxxxxxxxxxxxxxxxxxx

**Additional context**
fail after upgrade of last update of HA core-2021.12.0

**Comment by hmmbob** [comment]
Fix probably in https://github.com/fondberg/spotcast/pull/271, waiting to get merged and released

**Comment by Electronlibre2012** [comment]
thanks @hmmbob for your fast reply!

i thought it was already release with 2021.12.0...misanderstanding sorry...i wait no problem...

have a good day

**Comment by hmmbob** [comment]
It's rather easy to apply those fixes yourself locally, if you'd like.

**Comment by LooneyN** [comment]
Please tell us how. I love spotcast and use it extremly often. Can't wait for an official update :D
