### ISSUE TITLE
AFTER UPGRADE core_2021.11.5 Problems with  Spotcast 

### ISSUE THREAD

**Issue by giugit** [fondberg/spotcast#275]
Logger: homeassistant.helpers.entity
Source: custom_components/spotcast/sensor.py:56
Integration: Spotcast (documentation, issues)
First occurred: 11:45:13 (101 occurrences)
Last logged: 13:25:14

Update for sensor.chromecast_devices fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/sensor.py", line 51, in update
    chromecasts = [
  File "/config/custom_components/spotcast/sensor.py", line 56, in <listcomp>
    "model_name": cast_info.model_name,
AttributeError: 'ChromecastInfo' object has no attribute 'model_name'

*Describe the bug**

* [ ] Using latest version of spotcast
* [ ] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [ ] Using latest stable version of Home Assistant
* [ ] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**

**Environment (please complete the following information):**
 - HA version: [ ]
 - spotcast version: [ ]

**Configuration**
Add your configuration

**Additional context**

**Comment by Darkfull-Dante** [comment]
Hi @giugit, can you confirm if problem persist after v3.6.22

**Comment by hmmbob** [comment]
This should have been fixed with 3.6.22 indeed

**Comment by giugit** [comment]
> Hi @giugit, can you confirm if problem persist after v3.6.22

Problem Solved!
