### ISSUE TITLE
Component error: spotcast

### ISSUE THREAD

**Issue by ciscogomes2001** [fondberg/spotcast#28]
i install it via hacs then restarted and after that i add the lines to the configuration.yaml
and when e make the Configuration validation e get this error:

Component error: spotcast - Requirements for spotcast not found: ['fondberg-spotipy==2.4.5-dev2'].

**Comment by fondberg** [comment]
That is weird. Död you try restarting home assistant?

**Comment by ciscogomes2001** [comment]
What do you mean? Restart home assistant and ignoring this error?

**Comment by fondberg** [comment]
I was just trying to help. As this component doesn't install it's own dependencies this bug should probably be reported elsewhere.
If the issue still remains after a restart of home assistant the issue must be with your setup somehow.

**Comment by dzegarra** [comment]
I had a similar problem. The error I was getting was:

```
docker exec homeassistant python -m homeassistant --script check_config --config /config
Testing configuration at /config
INFO:homeassistant.util.package:Attempting install of spotify_token==0.1.2
ERROR:homeassistant.util.package:Unable to install package spotify_token==0.1.2: ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/spotify_token.py'
Consider using the `--user` option or check the permissions.

WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Failed config
  General Errors: 
    - Component error: spotcast - Requirements for spotcast not found: ['spotify_token==0.1.2'].
```

I solved adding the option `--user 0` to the `docker exec` command. That way pip could have write access to the dir `/usr/local/lib/python3.7/site-packages/`.
