### ISSUE TITLE
Add playlist random selection from category

### ISSUE THREAD

**Issue by fcusson** [fondberg/spotcast#280]
@maxenced, I open this issue to continue discussion on the ongoing development of the random selection from category functionnality

**List of function to add the country tag**
- [x] album_tracks (spotipy)
- [x] category_playlists (spotipy)
- [x] get_playlist (self, currently hard-coded)
- [x] search (spotipy)
- [x] show_episodes (spotipy)

**Comment by Darkfull-Dante** [comment]
One element I would like to see changed is that we need to do more input validation.

I've been working on my side on validating the country and category provided by the user. I haven't tested it yet, but I came up with this:
```python
# validate category and country are valid entries
    if country not in spotify_client.country_codes:
        _LOGGER.error(f"{country} is not a valid country code")
        return None
    
    if category not in spotify_client.categories(country=country, limit=limit):
        _LOGGER.error(f"{category} is not a valid category")
        return None
```

The country validation should work without problem, but I am looking for a more robust way of validating the category existence. I know I shouldn't use the provided limit since it's for the playlists in the category, not the categories themselfs.

**Comment by maxenced** [comment]
Hey @Darkfull-Dante , I didn't expect such involvement in my issue, what a good surprise :) 
I can't see any better way to validate category than what you're doing

**Comment by Darkfull-Dante** [comment]
@maxenced I just made a push, I found a way to validate more cleanly the category. Spotify API still limit the client.categories to 50 entries so we'll have to limit ourself to that. In testing, if we find that it is limiting, we could do a warning log only and not bother with validating the category, but that could cause tracebacks which I would really like to avoid as much as possible.

**Comment by Darkfull-Dante** [comment]
I had to do a PR to think of a much better way to handle the validation. I replaced the method with a try catch instead. Does a much cleaner job and doesn't rely on a limited subset of categories

**Comment by maxenced** [comment]
Hello there ! 
What's the next step to get this into master / released ?

**Comment by Darkfull-Dante** [comment]
I am currently blocked at adding the country functionality to the sensor. I have a semi working code on my own repo. I will try to push it in the project branch soon so we could test it (appart from the sensor)

**Comment by Darkfull-Dante** [comment]
@maxenced, I might have finally found a way to get the country code in the sensor, it was the missing part of the puzzle. I'm finalizing testing and I'll push another PR tomorrow.

Does your setup let you clone a repo in your homeassistant environnement? If so, it could be a good thing you test the functionnality to make sure it lives up to your original PR.

**Comment by maxenced** [comment]
Sorry for the late reply, tested and lgtm, thanks for the work !
