### ISSUE TITLE
Additional instructions to find Spotify device ID

### ISSUE THREAD

**Issue by truhponen** [fondberg/spotcast#288]
Section "Find Spotify Device ID" in README.md (https://github.com/fondberg/spotcast#find-spotify-device-id) could describe alternative method to get device IDs.

Additional method that I used:
If user has Spotify developer account, they can get their device IDs with developer console's "Get Available Devices" API-test (https://developer.spotify.com/console/get-users-available-devices/)

**Comment by fcusson** [comment]
@truhponen if you want you can submit a PR explaining the process in the documentation. Otherwise, I'll check to add it in the future
