### ISSUE TITLE
Broken on Home Assistant 0.99b0

### ISSUE THREAD

**Issue by SeanPM5** [fondberg/spotcast#29]
I just installed the Home Assistant 0.99b0 and Spotcast was broken. It seemed to have also caused an invalid config on the core "cast" integration too.

```
2019-09-12 13:10:12 ERROR (MainThread) [homeassistant.config] Unable to import cast: cannot import name 'APP_HOME_ASSISTANT' from 'pychromecast.config' (/usr/local/lib/python3.7/site-packages/pychromecast/config.py)
2019-09-12 13:10:12 ERROR (MainThread) [homeassistant.setup] Setup failed for cast: Invalid config.
```
and when I checked my config in "Server Control" panel it appears Spotcast was the cause:

`Package spotcast setup failed. Component spotcast No module named 'pychromecast.controllers.homeassistant'`

In the beta channel of Discord somebody told me a fix:

```
Froz Today at 4:59 PM
@Sean I edited the manifest.json for spotcast to use pychromecast 4.0.1 and it fixed the problem
```

Just wanted to report this asap so you could maybe roll out an update before the stable version releases in under a week.

**Comment by fondberg** [comment]
Thanks. I guess the moves around the modules in core... I'm busy atm so hopefully someone could help out creating a fix for it. Otherwise it will need to wait a while

**Comment by jokerigno** [comment]
Issue persist in 0.99x:

```
Package spotify setup failed. Component spotcast No module named 'pychromecast.controllers.homeassistant'
Platform error sensor.spotcast - No module named 'pychromecast.controllers.homeassistant'
```

**Comment by cben0ist** [comment]
Just confirming the same issue on 0.99 release:
`Component error: spotcast - No module named 'pychromecast.controllers.homeassistant'
Platform error sensor.spotcast - No module named 'pychromecast.controllers.homeassistant'`

**Comment by bendikrb** [comment]
I have pushed a fix to this in the PR I already had open (#27).

**Comment by bendikrb** [comment]
Fixed in 28469f5 (#27 / #30). Perhaps mark this as resolved @fondberg?

**Comment by Annors83** [comment]
Hi. 
I have updated to Spotcast 2.2 and HACS 0.14.2 and HASSIO 0.99 (all latest possible installations) and when I want to restart the server I get "Config error. See dev-info panel for details." in the Notifications tab and then "Component error: spotcast - No module named 'pychromecast.controllers.homeassistant'" in the Developer tools Log.

(Before updating HACS and Spotcast, it all worked fine. 

I have doublechecked manifest.json and it states pychromecast version 4.0.1.

**Comment by bendikrb** [comment]
@Annors83 Try uninstalling spotcast from HACS, and then install again. Manifest.json may well state 4.0.1 - but it sounds like it hasn't gotten installed. A proper restart of hassio may also do the trick, if you haven't tried that already.

**Comment by Annors83** [comment]
Thanks @bendikrb! A reboot did the trick!
I was uneasy of doing a reboot, since I couldn't restart the server without errors :)

**Comment by fondberg** [comment]
Closing. Reboot is required because the way ha works with deps
