### ISSUE TITLE
Casting to groups is not working.

### ISSUE THREAD

**Issue by phr0z** [fondberg/spotcast#3]
Casting to groups is not working. 

Tracked here: https://github.com/balloob/pychromecast/issues/292

**Comment by phr0z** [comment]
Hi,

I think spotipy only returns a list of available devices through this Spotify API
https://api.spotify.com/v1/me/player/devices
https://developer.spotify.com/console/get-users-available-devices/

So if the app is launched properly on the Chromecasts group Spotify should register these devices and return this value.

I did see that when starting the cast from my iPhone the device_id returned from Spotify API is in caps whilst regular devices values are returned in lower cases.

Might it be that the namespace differs?

**Comment by phr0z** [comment]
I think I actually solved it.

Will upload example soon. :-)

**Comment by phr0z** [comment]
example here: https://github.com/phr0z/pychromecast/blob/master/examples/spotify_example_group.py

It does seem like it initializes another application in fact 531A4F84

For now I only seem to be able to playback single tracks uri's. It throws an error when i specify playlist uri.
Might be spotipy, too tired to continue right now. :-)

Please try.

**Comment by phr0z** [comment]
Experimental fork here with added support for group:
https://github.com/phr0z/spotcast

#c5ed888

**Comment by fondberg** [comment]
Nice. I'll give it a try later today!

**Comment by fondberg** [comment]
@phr0z bummer but I get totally flaky results with the app id not set around 2 out of 3 attempts.
I think a more robust solution with checking the chromecast devices in the group and look for one of them in the list of devices returned from the spotify `client.devices()` call. For me it seems my device `Kök` always becomes master. Maybe simply because alphabetically `Kök` is before `Vardagsrum`. If I take the device id of `Kök` it works all the time...

WDYY?

**Comment by fondberg** [comment]
Just saw this... https://github.com/balloob/pychromecast/pull/294

**Comment by phr0z** [comment]
Updated my fork with support for the new Spotify Controller.
https://github.com/phr0z/spotcast/commit/8d94d2d43b595d4e2b90f431a7dffedbf59d271e

Also added a new feature, transfer playback which lets you switch to your chromecast devices seamlessly. :)

Let me know if you want me to create a pull request.

**Comment by fondberg** [comment]
Fixed in master

**Comment by fondberg** [comment]
@phr0z missed the transfer functionality. Wouldn't it be better is we check if there is a playback and transfer automatically? Please open a PR and we can discuss!
Thanks for your help and efforts!

Ha en grym dag
