### ISSUE TITLE
dc and key not defined

### ISSUE THREAD

**Issue by derwotograf** [fondberg/spotcast#301]
**Configuration check failed**
adding the sp_dc and sp_key to the configuration file makes the configuration check fail.

* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Environment (please complete the following information):**
 - Installation type: [HA_OS]
 - HA version: [core-2022.2.9]
 - spotcast version: [3.6.25]

**Logs**
`2022-02-22 15:52:02 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2941973600] Received invalid command: spotcast/accounts`

`Error loading /config/configuration.yaml: Secret xxx not defined`

**Configuration**
## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.98
arch | armv7l
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4860
Installed Version | 1.23.0
Stage | running
Available Repositories | 989
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 58.9 GB
disk_used | 6.8 GB
healthy | true
supported | true
board | odroid-xu4
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.4.4), NGINX Home Assistant SSL proxy (3.1.1), File editor (5.3.3), Let's Encrypt (4.12.0), Samba share (9.5.1), MariaDB (2.4.0), Spotify Connect (0.10.0), Plex Media Server (2.7.4), SSH & Web Terminal (10.0.2), Mosquitto broker (6.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 4
views | 7
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Additional context**

**Comment by hmmbob** [comment]
And how did you add it? Can you copy-paste it here? (make sure to redact the actual keys)

**Comment by derwotograf** [comment]
thanks for the reply. how did I add what exactly? HACS integration? installed via HACS.

**Comment by hmmbob** [comment]
The two keys to the configuration.yaml file - sorry for not wording that better.

**Comment by derwotograf** [comment]
so sorry, my bad. thanks for the hint though 👍 
I did not specify it at all in the secrets.yaml
