### ISSUE TITLE
Casting via the media browser fails because of invalid URI

### ISSUE THREAD

**Issue by Skeletorjus** [fondberg/spotcast#306]
After selecting a track to play in the media browser (amazing feature, by the way), the playback fails because the received URI is using wrong formatting. See log.

* [X] Using latest version of spotcast
* [X] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [ ] Using latest stable version of Home Assistant
* [X] I have Spotify Premium
* [X] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Environment (please complete the following information):**
 - Installation type: [Supervised]
 - HA version: [2022.3.0b5]
 - spotcast version: [3.6.26]

**Configuration**
```
spotcast:
  sp_dc: !secret spotcast_dc
  sp_key: !secret spotcast_key
```
f4cfc6d8f2c411ea968e791d9a657c65

**Additional context**
Log (partly sanitized)
```
2022-03-01 09:42:02 DEBUG (SyncWorker_2) [custom_components.spotcast.spotcast_controller] setting up with  account default
2022-03-01 09:42:02 DEBUG (SyncWorker_2) [custom_components.spotcast.spotcast_controller] expires: 1646126988 time: 1646124122.887227
2022-03-01 09:42:02 ERROR (SyncWorker_2) [custom_components.spotcast.helpers] [spotify://00000000000000000000000000000000/spotify:track:4HlVUapocBDBqkPtET2knz] is not a valid URI. The format should be [Spotify.<type>.<unique_id>]
2022-03-01 09:42:02 ERROR (SyncWorker_2) [custom_components.spotcast] Invalid URI provided, aborting casting
```

**Comment by hmmbob** [comment]
Will be fixed by #305

**Comment by fcusson** [comment]
v3.6.27 has been released with #305 fixes

**Comment by soundslikeluke** [comment]
I have updated to v3.6.27 and casting using URI is still not working

**Comment by fcusson** [comment]
@soundslikeluke, this issue was about failing to cast using the media browser. Your comment seems to indicate you tried to cast using a URI directly. Could you provide more information on the issue you're facing? If  it is not regarding the media browser, We could open a separate issue regarding that and work from there.

**Comment by fcusson** [comment]
@soundslikeluke after testing, the problem referred in this issue doesn't replicate. Please open another issue with more details with the behavior you are facing and what you did to get there. We will try to help you as much as we can.
