### ISSUE TITLE
No sp_key and sp_dc cookies on open.spotify.com

### ISSUE THREAD

**Issue by JamieEC** [fondberg/spotcast#309]
# Bug Ticket

## Describe the bug

* [ ] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [Container]
 - HA version: [2022.3.3]
 - spotcast version: [Unsure]

## Configuration

Add your configuration

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

## Additional context

Within open.spotify.com, I do not see the above cookes. I am sure I am missing something. 
![image](https://user-images.githubusercontent.com/48264520/158061927-4a4825fd-41b4-416a-ae12-12161dd7b244.png)

**Comment by fcusson** [comment]
Hi @JamieEC, might be a stupid question, but I prefer I ask before going further. You are logged in Spotify on the browser while you attempted to get your key?

**Comment by JamieEC** [comment]
Oh no I am not! I swear I was, my apologies.
Thank you!
