### ISSUE TITLE
Selecting Cast Device Difficult on Mobile

### ISSUE THREAD

**Issue by manuelh19** [fondberg/spotcast#313]
Selecting a Casting device has become super difficult on mobile since a recent update. Before you clicked on the button, saw the list of devices, you could select from. Now displaying the list of devices seems to be a hover action, which is near impossible to trigger on either my phone or Dashboard Tablet.

**Comment by fcusson** [comment]
Spotcast doesn't deal with UI, we only provide the backend service. Could you provide more details, like screenshot so we could help you get help from the correct project?

**Comment by manuelh19** [comment]
Ahhh sorry, my bad. Was a problem of the lovelace card. Needs spotcast to work, therefore my stupid head always thought spotcast was the card. Sorry again, but thanks for the quick response
