### ISSUE TITLE
How to join other speakers?

### ISSUE THREAD

**Issue by prbtt** [fondberg/spotcast#317]
I have spotcast installed and I have 4 sources as of now: 3 echo dots and my Home Assistant instance with spotify connect.
When i change sources it stopts playing on the previous source. I'd like to know if there is a service that allows me to dinamically join and unjoin those 4 sources. Keep in mind I don't have those sources as media players in home assistant, is this the issue?

**Comment by fcusson** [comment]
Yes it will be an issue, spotcast can only talk to spotify connect entity, it cannot group them.

Google home let's you group speaker together and then exposes that speaker group as an entity to Spotify, I supposed Amazon has something similar, but you won't be able to group device from different ecosystem.

Spotify will accept one stream on one device per user and is a limitation from there end. There might be a solution, but this is out of scope of this project.
