### ISSUE TITLE
Stop playing spotify

### ISSUE THREAD

**Issue by TheCazz** [fondberg/spotcast#32]
Maybe is something easy I have miss but I can now play spotify with service:spotcast.start.
But how do I stop it, there is no service:spotcast.stop?

**Comment by pawel334** [comment]
Did you try using google cast integration?

**Comment by senoadiw** [comment]
You can use `media_player.media_stop` or `media_player.turn_off` service on the chromecast media_player entity.

**Comment by TheCazz** [comment]
Ahh I did not know that I can use media_player.media_stop :)

Thanks
