### ISSUE TITLE
Integration error: spotcast - Integration 'spotcast' not found.

### ISSUE THREAD

**Issue by schumi2004** [fondberg/spotcast#325]
# Bug Ticket

## Describe the bug

Just installed the Spotcast integration using HACS rebooted, added config to configuration.yaml and reboot failed.

* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS]
 - HA version: [Home Assistant Core 2022.5.3
Home Assistant Supervisor 2022.05.1
Home Assistant OS 7.6]
 - spotcast version: [tried 3.6.29 and master]

## Configuration

single account config as described in readme.

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

## Service Call

n/a

## Additional context

n/a

**Comment by ktmaran** [comment]
I am having the same issue. Same configuration and versions.

**Comment by fcusson** [comment]
@schumi2004 I'm not following the version you stayed you used.

If you installed from HACS, the current version is 3.6.29

**Comment by schumi2004** [comment]
> @schumi2004 I'm not following the version you stayed you used.
> 
> If you installed from HACS, the current version is 3.6.29

You are right, made a typo.
It is indeed 3.6.29 but i also tried master which i'm currently on.

For the rest i don't know what happend but after several restarts en config change modifications (disabling/enabling) spotcast config it suddenly worked.

**Comment by fcusson** [comment]
Ok I will try to investigate.

@schumi2004 was your HACS install recent? There might have been problems getting files from the Github API if that was the case.

**Comment by schumi2004** [comment]
@fcusson  No, it's running for several years already (RPi3 + external HDD)
I did receive a HACS update recently.

**Comment by Joooost** [comment]
@schumi2004 I had the same problem, my solution was:

1.  Remove Spotcast via HACS and comment the spotcast entries in the configuration.yaml.
2. Restart Home Assistant
3. Install Spotcast and reboot
4. Uncomment spotcast entries in the configuration.yaml and reboot

After that everything worked again for me.
