### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by tjuel** [fondberg/spotcast#326]
# Bug Ticket

## Describe the bug

Unknown. I've never been able to get Spotcast to operate successfully. I have an operational Spotify Integration and have setup Spotcast appropriately according to the documentation. 

* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS]
 - HA version: [2022.5.5]
 - spotcast version: [3.6.29]

## Configuration

sp_dc and sp_key are correct and have been copy and pasted multiple times to see if it corrects the issue.

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

## Additional context

Found the issue when attempting a service call "Google Home Resume" Script found here: https://community.home-assistant.io/t/script-to-resume-google-cast-devices-after-they-have-been-interrupted-by-any-action/383896

> Logger: homeassistant
> Source: custom_components/spotcast/spotcast_controller.py:187
> Integration: Spotcast ([documentation](https://github.com/fondberg/spotcast), [issues](https://github.com/fondberg/spotcast/issues))
> First occurred: 1:11:31 PM (1 occurrences)
> Last logged: 1:11:31 PM
> 
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 428, in _async_run
>     return await self.script.async_run(script_vars, context)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
>     await asyncio.shield(run.async_run())
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
>     await self._async_step(log_exceptions=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
>     self._handle_exception(
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
>     raise exception
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
>     await getattr(self, handler)()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 919, in _async_if_step
>     await self._async_run_script(if_data["if_then"])
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1025, in _async_run_script
>     await self._async_run_long_action(
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 644, in _async_run_long_action
>     long_task.result()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
>     await asyncio.shield(run.async_run())
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
>     await self._async_step(log_exceptions=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
>     self._handle_exception(
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
>     raise exception
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
>     await getattr(self, handler)()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 892, in _async_choose_step
>     await self._async_run_script(script)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1025, in _async_run_script
>     await self._async_run_long_action(
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 644, in _async_run_long_action
>     long_task.result()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
>     await asyncio.shield(run.async_run())
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
>     await self._async_step(log_exceptions=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
>     self._handle_exception(
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
>     raise exception
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
>     await getattr(self, handler)()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
>     await service_task
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1670, in _execute_service
>     await self._hass.async_add_executor_job(
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/spotcast/__init__.py", line 190, in start_casting
>     spotify_device_id = spotcast_controller.get_spotify_device_id(
>   File "/config/custom_components/spotcast/spotcast_controller.py", line 200, in get_spotify_device_id
>     spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
>   File "/config/custom_components/spotcast/spotcast_controller.py", line 187, in _getSpotifyConnectDeviceId
>     for device in devices_available["devices"]:
> TypeError: 'NoneType' object is not subscriptable

**Comment by fcusson** [comment]
Does a standard service call works or only the custom script?

**Comment by tjuel** [comment]
@fcusson, negative. I used Developer Tools and tried calling:

`service: spotcast.start
data:
  entity_id: media_player.tom
  start_volume: 10
`
I received `failed to call service spotcast.start. Unknown error`

**Comment by fcusson** [comment]
You might have the same problem than #327. Would you be confortable activating debug log and providing the log so I can look into it?

**Comment by tjuel** [comment]
@fcusson, it looks like it's throwing two errors in the logs when a service call is run.

`This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/spotcast/spotcast_controller.py:187
Integration: Spotcast (documentation, issues)
First occurred: 9:17:08 AM (1 occurrences)
Last logged: 9:17:08 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1670, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 190, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 200, in get_spotify_device_id
    spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 187, in _getSpotifyConnectDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable
`
**AND**

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/spotcast_controller.py:187
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:17:08 AM (1 occurrences)
Last logged: 9:17:08 AM

[547937560128] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 626, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1670, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 190, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 200, in get_spotify_device_id
    spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 187, in _getSpotifyConnectDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not subscriptable
`

**Comment by fcusson** [comment]
@tjuel both are related to the same thing. Spotcast is unable to find devices that are spotify connect capable.

How did you attempt the device call, with the device name, entity_id or spotify_id?

**Comment by tjuel** [comment]
Hello @fcusson, I believe the scirpt I'm using has failsafes that can pull from device name, entity_id, or spotify_id depending on what variables are available/provided. I'm using a shared script that appears to be working for a majority of users except for me and have implemented it as described in the author's implementation description.

**Comment by Jleagle** [comment]
Also getting this, using entity_id

**Comment by fcusson** [comment]
Should be resolved in `v3.7.0`. Please reopen if sitll present
