### ISSUE TITLE
wp_access_token error

### ISSUE THREAD

**Issue by fredamn76** [fondberg/spotcast#34]
I cannot play music anymore. I'm using version v2.2 of Spotcast and Home Assistent 0.99.3.

I get the following error using services under developertools in Home Assistent and using spotify-card.

`Log Details (ERROR)
Sun Sep 29 2019 17:33:52 GMT+0200 (centraleuropeisk sommartid)
"name='wp_access_token', domain=None, path=None"
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 162, in start_casting
    access_token, expires = get_spotify_token(username=user, password=pwd)
  File "/config/custom_components/spotcast/__init__.py", line 85, in get_spotify_token
    data = st.start_session(username, password)
  File "/usr/local/lib/python3.7/site-packages/spotify_token.py", line 70, in start_session
    access_token, expiration_date = _get_access_token(session, cookies)
  File "/usr/local/lib/python3.7/site-packages/spotify_token.py", line 42, in _get_access_token
    access_token = response.cookies['wp_access_token']
  File "/usr/local/lib/python3.7/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='wp_access_token', domain=None, path=None"`

This is added to configuration.yaml

> spotcast:
> 
 >   username: myusername
 >   password: mypassword
 >   accounts:
 >     fredrik:
 >       username: myusername
 >       password: mypassword
 >     philip:
 >       username: myusername2
 >       password: mypassword2
 > 

custom-cards:spotify-card

> > client_id: mycliendid
> limit: 25
> random_song: true
> transfer_playback: true
> type: 'custom:spotify-card'

**Comment by todfox** [comment]
I also have the same issue.

**Comment by trevormiller6** [comment]
I have this issue too.

**Comment by heqirong** [comment]
I have this issue too.

**Comment by crankin91** [comment]
Same issue

**Comment by Catt00** [comment]
Have the same issue as well.

**Comment by moejetz** [comment]
Same here.

**Comment by pezmannen** [comment]
Same here

**Comment by fondberg** [comment]
Oh no! If I am correct this means Spotify changed the way a browser token is received. That is bad as this library uses the unofficial way to get a token because it is required for chromecast devices.
I will need to investigate this...

**Comment by Fabfian0493** [comment]
same here

**Comment by camfred** [comment]
Same.

**Comment by petergp** [comment]
Looks like Spotify has changed their authentication so `wp_access_token` no longer is return as a cookie after logging in as defined in https://github.com/enriquegh/spotify-webplayer-token/blob/c8ebf5811640cc78eb560ac725cb7d944c63f400/spotify_token.py#L42
It looks like they instead use a bunch of cookies set when doing a POST to

**Comment by petergp** [comment]
Looks like Spotify has changed their authentication so `wp_access_token` no longer is return as a cookie after logging in as defined in https://github.com/enriquegh/spotify-webplayer-token/blob/c8ebf5811640cc78eb560ac725cb7d944c63f400/spotify_token.py#L42 which spotcast depends on. Confirmed that by sniffing looking at the traffic when logging into https://accounts.spotify.com/login
It looks like they instead use a bunch of cookies (sp_ac, sp_key and sp_dc). I’m not sure if they existed before too and if any of them has the value of the access token. This will have to be investigated more. I can try to find time in a few days if @fondberg doesnt beat me to it.

I assume its not possible to obtain a full access token using any official APIs, @fondberg?

**Comment by fabiopedrosa** [comment]
Tried using a regular access_token through the OAuth official procedure, but those don't work for casting to chromecast.

**Comment by fondberg** [comment]
That is correct. The access token from the normal web oath api is too weak for this (lacks scope).

Unless they have changed the way a token is sent to a chromecast device as well the only thing to do is to do what @petergp says... reverse engineer the new login and either update the spotify-token library or create a new one.
Right now my newborn baby and my work pretty much occupies me fulltime I wont have time until the weekend for this. So if someone figures out the call flow to get the token it would be very appreciated

**Comment by fabiopedrosa** [comment]
I had a quick look and it seems the access_token is generated in the javascript, somewhere in https://open.scdn.co/static/vendor.a8787467.js 
I wasn't able to find how the cookie vars are used for that, there's `sp_ac` which looks similar to how lengthy a token would be.

Anyway, I was able to create a workaround so I avoid going through the JS code, but its not really efficient:
1) login using the POST to `https://accounts.spotify.com/login`
2) use a headless selenium browser to open `https://open.spotify.com/browse` with the cookies injected
3) by using https://github.com/wkeeling/selenium-wire I was able to check the ajax requests done by the page, and just retrieve the `Authorization` header
4) pass that token to the controlled. for `expiresIn` I just use 3600, since that's not in the SPA requests.

I'm cool with sharing this solution, but I'd really appreciate a proper fix by finding the right way to generate the access_token from the given cookies.

**Comment by AlexLadd** [comment]
[Here](https://gist.github.com/AlexLadd/db3d09b204d6c59787ad85d26c412b33) is a modification of spotify_token that has worked for me. I am not sure if this is the proper way to access the token but this version has been working consistently for the past few days. Hope it can be of some help. I am using it in an [Appdaemon app](https://github.com/AlexLadd/Appdaemon-Spotify-Player) that is inspired by spotcast that makes recommendations and plays music to a Spotify connected device if anyone is interested in trying it out.

Thank you for the great project!

**Comment by fabiopedrosa** [comment]
@AlexLadd that's awesome, thanks. Indeed a more sane approach.

**Comment by fondberg** [comment]
@alexladd I wonder if the token is powerful enough for chromecast but it is worth a try!

@fabiopedrosa using selenium will not work I'm afraid as it involves quite a bit if other headless browser headaches

**Comment by jensweimann** [comment]
> [Here](https://gist.github.com/AlexLadd/db3d09b204d6c59787ad85d26c412b33) is a modification of spotify_token that has worked for me. I am not sure if this is the proper way to access the token but this version has been working consistently for the past few days. Hope it can be of some help. I am using it in an [Appdaemon app](https://github.com/AlexLadd/Appdaemon-Spotify-Player) that is inspired by spotcast that makes recommendations and plays music to a Spotify connected device if anyone is interested in trying it out.
> 
> Thank you for the great project!

Thanks, it works! Here is the file:

[__init__.zip](https://github.com/fondberg/spotcast/files/3685506/__init__.zip)

**Comment by Victoor** [comment]
It works! Make a PR or something :wink:

**Comment by fondberg** [comment]
I haven't tested it yet, new born takes too much time...
if you create a PR it would be good to at least keep this function in a separate file

**Comment by todfox** [comment]
@jensweimann I am getting an error. 

2019-10-03 11:54:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140253235638928] http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play&device_id=046aecdade5745599a256846415f16bd:
 error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 121, in _internal_call
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player/play&device_id=046aecdade5745599a256846415f16bd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 245, in start_casting
    play(client, spotify_device_id, uri, random_song)
  File "/config/custom_components/spotcast/__init__.py", line 160, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 913, in start_playback
    return self._put(self._append_device_id("me/player/play", device_id), payload=data)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 190, in _put
    return self._internal_call('PUT', url, payload, kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 129, in _internal_call
    -1, '%s:\n %s' % (r.url, 'error'), headers=r.headers)
spotipy.client.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play&device_id=046aecdade5745599a256846415f16bd:
 error

**Comment by Juice2019** [comment]
@bendikrb fix works great! Thanks.

**Comment by crankin91** [comment]
Fix worked perfectly for me. Thanks all

**Comment by fredamn76** [comment]
I have replaced the original file __init__.py and uploaded spotify_token.py  to spotcast directory. However it does not work. What am i doing wrong?

**Comment by freakshock88** [comment]
> I have replaced the original file **init**.py and uploaded spotify_token.py to spotcast directory. However it does not work. What am i doing wrong?

Just replacing the init.py with the one jensweimann posted worked for me! Thanks :)

**Comment by fredamn76** [comment]
> > I have replaced the original file **init**.py and uploaded spotify_token.py to spotcast directory. However it does not work. What am i doing wrong?
> 
> Just replacing the init.py with the one jensweimann posted worked for me! Thanks :)

Thank you. I will try that.

**Comment by fredamn76** [comment]
I can confirm that jensweimanns solution works for me aswell. 

However i cannot get it to work with https://github.com/custom-cards/spotify-card

**Comment by todfox** [comment]
> t(self._appe

After I pulled/installed the latest and recreated the docker image. It now works! Thanks.

**Comment by todfox** [comment]
> @jensweimann I am getting an error.
> 
> 2019-10-03 11:54:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140253235638928] http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play&device_id=046aecdade5745599a256846415f16bd:
> error
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 121, in _internal_call
> r.raise_for_status()
> File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
> raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player/play&device_id=046aecdade5745599a256846415f16bd
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
> connection.context(msg),
> File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
> await asyncio.shield(self._execute_service(handler, service_call))
> File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
> await self._hass.async_add_executor_job(handler.func, service_call)
> File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
> result = self.fn(*self.args, **self.kwargs)
> File "/config/custom_components/spotcast/**init**.py", line 245, in start_casting
> play(client, spotify_device_id, uri, random_song)
> File "/config/custom_components/spotcast/**init**.py", line 160, in play
> client.start_playback(**kwargs)
> File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 913, in start_playback
> return self._put(self._append_device_id("me/player/play", device_id), payload=data)
> File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 190, in _put
> return self._internal_call('PUT', url, payload, kwargs)
> File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 129, in _internal_call
> -1, '%s:\n %s' % (r.url, 'error'), headers=r.headers)
> spotipy.client.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play&device_id=046aecdade5745599a256846415f16bd:
> error

After I pulled/installed the latest and recreated the docker image, it now works! Thanks.

**Comment by fondberg** [comment]
Just released v2.3. Thanks @AlexLadd and @bendikrb for your efforts!

**Comment by aminammari** [comment]
> I had a quick look and it seems the access_token is generated in the javascript, somewhere in https://open.scdn.co/static/vendor.a8787467.js
> I wasn't able to find how the cookie vars are used for that, there's `sp_ac` which looks similar to how lengthy a token would be.
> 
> Anyway, I was able to create a workaround so I avoid going through the JS code, but its not really efficient:
> 
> 1. login using the POST to `https://accounts.spotify.com/login`
> 2. use a headless selenium browser to open `https://open.spotify.com/browse` with the cookies injected
> 3. by using https://github.com/wkeeling/selenium-wire I was able to check the ajax requests done by the page, and just retrieve the `Authorization` header
> 4. pass that token to the controlled. for `expiresIn` I just use 3600, since that's not in the SPA requests.
> 
> I'm cool with sharing this solution, but I'd really appreciate a proper fix by finding the right way to generate the access_token from the given cookies.

i found this easy way to get access token https://generic.wg.spotify.com/creator-auth-proxy/v1/web/token?client_id=6cf79a93be894c2086b8cbf737e0796b

**Comment by aminammari** [comment]
buy me coffe if it works
