### ISSUE TITLE
Spofify no longer setting sp_key cookie

### ISSUE THREAD

**Issue by lanrat** [fondberg/spotcast#350]
# Bug Ticket

## Describe the bug

I recently changed my Spotifiy password which logged out all sessions and invalidated all cookies, requiring me to re-login on my desktop and get new cookies for spotcast.

However after logging back in, Spotify set the `sp_dc` cookie, but not the `sp_key` cookie. It looks like perhaps Spotify changed the way their session cookies may work?

* [X] Using latest version of spotcast
* [X] Using latest stable version of Home Assistant
* [X] I have setup the Spotify integration in Home Assistant
* [X] I have Spotify Premium
* [ ] I am using multiple accounts
* [ ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see README)
* [X] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: Container
 - HA version: 2022.8.7
 - spotcast version: v3.6.30

## Configuration

N/A. Missing Cookies, unable to setup

## Service Call

N/A.

## Additional context

Screenshot of cookies after logging into open.spotify.com

<img width="595" alt="Screen Shot 2022-09-07 at 12 50 02 PM" src="https://user-images.githubusercontent.com/164192/188964464-ef62f4cc-6446-43ab-b162-a1b58cdf27af.png">

**Comment by fcusson** [comment]
@lanrat  just created a new session on a private browser session and the sp_key was created on that session. Can you try logging out and back in and see if it resolves the problem.

I was able to replicate this behavior on multiple login and logout

**Comment by Filipe-sudo** [comment]
Can confirm also getting both sp_dc and sp_key. 
Unfortunately in my case can't get the integration to work.. After putting the sp_dc and sp_key in config.yaml like instructed HA won't finish the config validation, just spins indefinitely. Removing the the config.yaml entries gets the validation to work again.

**Comment by hmmbob** [comment]
> Can confirm also getting both sp_dc and sp_key. Unfortunately in my case can't get the integration to work.. After putting the sp_dc and sp_key in config.yaml like instructed HA won't finish the config validation, just spins indefinitely. Removing the entries from config.yaml gets the validation to work again.

typically this flow works:

- Install spotcast through HACS (or the manual copying of files, as described in readme)
- Restart Home Assistant
- Add config in configuration.yaml
- Restart Home Assistant once again

**Comment by lanrat** [comment]
I logged out and back in and this time `sp_key` was set. No idea why it was missing last time.

<img width="220" alt="Screen Shot 2022-09-08 at 2 22 44 PM" src="https://user-images.githubusercontent.com/164192/189228321-a2df17ef-fcf6-4826-b98e-40981f458212.png">

Thanks for the support!
