### ISSUE TITLE
Spotcast stops working

### ISSUE THREAD

**Issue by skank01** [fondberg/spotcast#353]
Is this integration still maintained?
No updates so far, and to look at the ammount of issues here..
I'm having troubles too.
Running latest HA OS on rpi4
I get these errors
Update for sensor.playlists_sensor fails
Traceback (most recent call last):
  File "/config/custom_components/spotcast/spotcast_controller.py", line 157, in get_spotify_token
    ).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/config/custom_components/spotcast/spotcast_controller.py", line 177, in start_session
    raise TokenError()
custom_components.spotcast.spotcast_controller.TokenError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/sensor.py", line 116, in update
    resp = self.hass.data[DOMAIN]["controller"].get_playlists(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 315, in get_playlists
    client = self.get_spotify_client(account)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 214, in get_spotify_client
    return spotipy.Spotify(auth=self.get_token_instance(account).access_token)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 149, in access_token
    self.ensure_token_valid()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 145, in ensure_token_valid
    self.get_spotify_token()
  File "/config/custom_components/spotcast/spotcast_controller.py", line 164, in get_spotify_token
    raise HomeAssistantError("Could not get spotify token.")
homeassistant.exceptions.HomeAssistantError: Could not get spotify token.

It worked before, not sure when it stopped working...

**Comment by fcusson** [comment]
@skank01 

> Is this integration still maintained?
> No updates so far, and to look at the ammount of issues here..

Well last update was 13 days ago and 5 of the issues are enhancements, 13 issues is really not a high number for an open source project especially when you collapse duplicates.

You deleted a critical information from your message:

> Als in my media browser, all my spotify accounts are gone...

Please do not delete information, not as critical as that. If you made an error or if the problem resolved itself, comments saying that this portion is working but you still have the issue.

With the little information I have, it seems it is your Spotify integration that is broken, it's a dependency of the project. Make sure the Spotify integration is working and that you can see playback details when starting music from Spotify directly. If you still have the problem by then please provide more details.

Please edit the issue using the template we provide (a copy will be provided in the next comment) and don't delete templates provided by the developper. We need that information, especially the actual version number you are running, don't say latest, someone looking at this issue in a year could think this issue is up to date while it's not.

**Comment by fcusson** [comment]
```markdown
# Bug Ticket

## Describe the bug

A clear and concise description of what the bug is.

* [ ] Using latest version of spotcast
* [ ] Using latest stable version of Home Assistant
* [ ] I have setup the Spotify integration in Home Assistant
* [ ] I have Spotify Premium
* [ ] I am using multiple accounts
* [ ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see README)
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core]
 - HA version: [ ]
 - spotcast version: [ ]

## Configuration

Add your configuration

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

## Additional context

Add any other context about the problem here.
```

**Comment by fcusson** [comment]
Hi @skank01,

Have you been able to review my message? We would need the additional details to be able to work on your ticket.

If we are without answers for more than 7 days, I will have to close the issue for inactivity.

**Comment by skank01** [comment]
Yes,
I made progress as well...
I am using latest  version of spotcast and HA (HA OS)
I have setup spotify integration and i do have premium
I am using multiple accounts (for me, my wife, and 2 kids)

The problem with the webbrowser isnt there, i made a mistake.
However i'm still having issues... but only with my spotify account.
The one of my wife and kids, still work.
I think the problem is only with my token , found this also:
Spotify Skank: afspelen: Error executing script. Error for call_service at pos 1: Could not get spotify token

**Comment by hmmbob** [comment]
`[ ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see README)`

☝🏻

**Comment by skank01** [comment]
> "[ ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see README)"
> 
> ☝🏻

Jup its fixed after i renewed.
IS this something i have to redo every year?

**Comment by hmmbob** [comment]
Yep.

And, to be frank: if you just would have left the template in the issue when you created it, and followed all steps mentioned in it, you would have fixed this yourselves within minutes. The template is there for a reason...

**Comment by skank01** [comment]
My apoligies, ur right!
