### ISSUE TITLE
First Call fails

### ISSUE THREAD

**Issue by danielducu** [fondberg/spotcast#355]
Calling service spotcast.start on an echo device after being idle for a few hours will drop an error. Immediately after a few seconds calling the service again will play correctly. Why and is there a fix ?

service: spotcast.start
data:
  spotify_device_id: xxxx_amzn_1
  uri: spotify:playlist:0e1JeLwDtqSJzK3bpAKQzB
  start_volume: 15

===========

[547126164064] Error handling message: Unknown error (unknown_error)
10:24:48 – (ERROR) Home Assistant WebSocket API (custom integration)

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=2a6213e8-2944-49db-b26e-d9e19e3dd437_amzn_1: Not found., reason: None
10:24:48 – (ERROR) Spotcast (custom integration)

HTTP Error for PUT to https://api.spotify.com/v1/me/player/play?device_id=2a6213e8-2944-49db-b26e-d9e19e3dd437_amzn_1 with Params: {} returned 404 due to Not found.
10:24:47 – (ERROR) Spotcast (custom integration)

**Comment by jkoestner** [comment]
This is a long shot, but what fixed this issue? I'm running into this same issue. It almost seems like the device wakes up
