### ISSUE TITLE
Better Search implementation needed

### ISSUE THREAD

**Issue by dreamtheater39** [fondberg/spotcast#362]
The current implementation makes very bad choices. Searching for comfortably numb by pink floyd plays some random artist's rendition etc. The reason being - most cover songs have the artist name as the song title and finds a higher match ratio compared to the original song by the original artist (based on the current best match implementation)

**Comment by dreamtheater39** [comment]
After looking at spotify's documentation - the search endpoint's searchType parameter can have multiple inputs separated by commas which provides a more accurate search result.

So, if my search string is "comfortably numb pink floyd" - my searchType should be "track,artist" to let spotify know both of these are in the search string. And this gives the top result - which means there is no necessary to do a "bestMatch" algorithm of your own

**Comment by dreamtheater39** [comment]
Submitted a pull request which fixes this
https://github.com/fondberg/spotcast/pull/363

**Comment by whoinow** [comment]
I also would like to see this merged for more accurate searching.

**Comment by whoinow** [comment]
I took care of the conflicts in my fort and added a bit more functionality to it as well. In my fork, I fixed up the artistName implementation and also added playlist searching.

**Comment by jaswalters** [comment]
> I took care of the conflicts in my fort and added a bit more functionality to it as well. In my fork, I fixed up the original artistName PR for current base code and also added playlist searching. I can squash the commits and see about getting a PR in.

Any luck? This would be a GREAT fix to the search issue.

**Comment by burch-hrci** [comment]
@fcusson This seems to have gotten worse very recently.

**Comment by fcusson** [comment]
forgot to close ticket after merging the PR
