### ISSUE TITLE
Component spotcast Integration 'spotcast' not found.

### ISSUE THREAD

**Issue by covertbert** [fondberg/spotcast#37]
When installing the custom_component manually and trying to set a config I get the following error:

` - Package spotcast setup failed. Component spotcast Integration 'spotcast' not found.`

I believe this is related to an update to HA that you may not have accounted for.

**Comment by fondberg** [comment]
I can't reproduce this on my dev environment or production.
Can you provide more information

**Comment by covertbert** [comment]
> I can't reproduce this on my dev environment or production.
> Can you provide more information

I cloned the repo and copied `spotcast` into `custom_components`. Then I tried to reference `spotcast` in my config and ran the `hassio homeassistant check` command, which results in that error.

I google the error and it seems that it's usually thrown when a component hasn't been updated to conform with the new `custom_components` structure.

Are you testing it on an up-to-date version of Home Assistant?

**Comment by fondberg** [comment]
There must be something in your setup that causes this. Can you removed the component and make sure the directory is deleted as well in custom,_components and then install again?
If it still don't van you provide a directory listing of the spotcast directory in custom components?

**Comment by fondberg** [comment]
Closing because lack of feedback

**Comment by vdbrink** [comment]
This happends when you first set the spotcast settings in your configuration.yaml before you installed the spotcast integration and restarted HA.

**Comment by cluttmann** [comment]
@vdbrink helped a lot, thanks!

First install --> then restart --> only then add the following to configuration.yaml

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

**Comment by pgross41** [comment]
This info would be helpful in the instructions. I had to restart twice: 

1. Copy into custom_components
2. Restart Home Assistant
3. Add config to configurations.yaml
4. Restart Home Assistant

Now the service is available to use!

**Comment by lucvanloon** [comment]
Please add the above comment from @pgross41  to the docs. This is very important.

**Comment by Tahutipai** [comment]
> Please add the above comment from @pgross41 to the docs. This is very important, especially because the error provided by Home Assistant is very generic and doesn't hint to having to restart prior to adding the configurations to the yaml file.

agreed
