### ISSUE TITLE
Failed to call service spotcast.start. Could not get spotify token.

### ISSUE THREAD

**Issue by Jese44** [fondberg/spotcast#370]
# Bug Ticket

## Describe the bug
After setting spotify integration and spotcast via HACS (bots successfully) when calling for the service from developer tools the error message stated in the title comes around. I've done installation 3 times and same error comes around.

* [X] Using latest version of spotcast
* [X] Using latest stable version of Home Assistant
* [X] I have setup the Spotify integration in Home Assistant
* [ ] I have Spotify Premium
* [ ] I am using multiple accounts
* [X] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see README)
* [X] I'm attaching relevant logs with level debug for component spotcast (see README)
* [X] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|
 - HA version: [ 2023.1.2]
 - spotcast version: [V3.6.30 ]

## Configuration
configuration.yaml:

````yaml
#spotcast
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
````

## Service Call

````yaml
service: spotcast.start
data:
  device_name: media_player.kitchen_nest_mini
  uri: spotify:playlist:5XOo5gb0jBm1cxMMfvIkDw?si=99d053c4f53a47e8
````

## Additional context

Home Assistant 2023.1.2
Supervisor 2022.12.1
Operating System 9.3
Frontend 20230104.0 - latest

log:

````log
2023-01-12 13:55:43.250 DEBUG (SyncWorker_10) [custom_components.spotcast.spotcast_controller] setting up with account default
2023-01-12 13:55:43.363 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Could not get spotify token.
2023-01-12 13:55:43.368 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547492229280] Error handling message: Could not get spotify token. (unknown_error) from 192.168.1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
````

**Comment by adabelleleiram** [comment]
Also got this error this morning

**Comment by adabelleleiram** [comment]
> Also got this error this morning. I have Premium and multiple accounts though

Refreshed my sp_dc and sp_key values, that did the trick

**Comment by fcusson** [comment]
@Jese44 are you sure you fully renewed your tokens the error message is usually sent when then token expired.

**Comment by Jese44** [comment]
I just renewed them to be sure:

- "rotated" the client secret
- removed spotify integration (incl. credientials)
- re-added integration succesfully with new secret
- re-started HA
- went to incognito spotify to take new sp_dc and key
- added them to the secrets.yaml
- restarted HA 
- tried service call --> same token error

**Comment by Jese44** [comment]
So... something fun, my pihole seems to block smth that is required to retrieve token for spotify..... :D 
well this was step forward, now this system doesn't want to play music in either of my google devices.... but this ticket can be closed since problem seemed to be pi-hole!

**Comment by fcusson** [comment]
@Jese44, If you can find the dn causing the problem, can you add it to this ticket. It would be useful information for future troubleshooting

**Comment by Jese44** [comment]
It's long gone, but i guess (if the domain list is chronological) it was this "open.spotify.com" which had came from random blocklist before to my blocks :)
and i figured out the "unable to find device" i had to use the name that was not in homeassistant, but which was in i.e. google home app. the "real name" described everywhere did not ring any bells on me and accidentally found and tried the one more name:
in HA: "Kitchen nest mini" & "media_player.kitchen_nest_mini"
In google home: "Kitchen speaker" <-- this one did the thing
