### ISSUE TITLE
Spotcast + Xbox + TuneIn

### ISSUE THREAD

**Issue by Ario80** [fondberg/spotcast#371]
Hi,

This is my first post so apologies in advance for possible inconsistencies. 

I'm using spotcast with Xbox to play Spotify media. Successfully. I would like to have "one click" auto play of selected TuneIn station via Xbox. Is that even possible?
Cheers!

**Comment by fcusson** [comment]
Hi @Ario80 , spotcast is only ment to manage Spotify playback. We do not have intention to provide support for other webmedia services.

More over, TuneIn does not provide an API for enduser, so an integration wouldn't be trivial to implement.
