### ISSUE TITLE
Could not find device *** from hass.data

### ISSUE THREAD

**Issue by wicol** [fondberg/spotcast#374]
# Bug Ticket

## Describe the bug
I renamed my speaker in HA ("Los högtalare" -> "Los speaker" - I run ghome in swedish, HA in english). The friendly name doesn't match the friendly name of the cast device anymore, and so no matching device can be found when initiating playback.

## Environment

 - Installation type: [Core]
 - HA version: [2023.1.7]
 - spotcast version: [3.6.30]

## Configuration

````yaml
action:
    service: spotcast.start
    data: >
      {
        "entity_id": "media_player.los_room_speaker",
        "uri": "spotify:playlist:7Acn4kaBSl30NJw",
        {% if states("media_player.los_room_speaker") != "playing" %}
        {# only set volume if we're not already playing #}
        "start_volume": 28,
        {% endif %}
      }
````

## Logs

* normal|debug

````log
2023-02-03 11:27:16.534 DEBUG (SyncWorker_4) [custom_components.spotcast.spotcast_controller] Chromecast devices: [..., ChromecastInfo(cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.0.44', 8009)), ServiceInfo(type='mdns', data='JBL-Link-Music-84eff5f199c7c56662cacbfa821eedbe._googlecast._tcp.local.'), ServiceInfo(type='host', data=('[::ffff:c0a8:2c]', 8009))}, uuid=UUID('84eff5f1-99c7-c566-62ca-cbfa821eedbe'), model_name='JBL Link Music', friendly_name='Los högtalare', host='[::ffff:c0a8:2c]', port=8009, cast_type='audio', manufacturer='HARMAN International Industries'), is_dynamic_group=None), ...]
2023-02-03 11:27:16.534 DEBUG (SyncWorker_4) [custom_components.spotcast.spotcast_controller] cast info: None
2023-02-03 11:27:16.535 ERROR (SyncWorker_4) [custom_components.spotcast.spotcast_controller] Could not find device Los speaker from hass.data
````

## Additional context

Relevant code: https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/spotcast_controller.py#L75

Not sure what attributes are available on the media_player object but would it be possible to match on IP instead of friendly name?

**Comment by fcusson** [comment]
@wicol.

Please activate the debug log. We will need that to troubleshoot. I'm fairly certain about the cause of the problem, but I nned to check the cast device found name that the helpers.get_cast_devices function returns before troubleshooting more.

**Comment by fcusson** [comment]
@wicol, also please update spotcast, you are not using an up to date version of the integration. The changes in 3.6.31 shouldn't impact the portion you are having problem with, but still, we should make sure you are up to date.

**Comment by wicol** [comment]
> @wicol.
> 
> Please activate the debug log. We will need that to troubleshoot. I'm fairly certain about the cause of the problem, but I nned to check the cast device found name that the helpers.get_cast_devices function returns before troubleshooting more.

That would be the log rows I included in my initial post :)
The first of them comes from https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/spotcast_controller.py#L70
..which is the output from `helpers.get_cast_devices`.
(I redacted other devices but included the one we're talking about)

> Bassically, what chromecast does when using the `entity_id` is that we extract the friendly name of the device from the entity and then try to map it to a chromecast device. The only thing I am not certain since I haven't looked into this portion of the code recently is if the chromecast device name that we compare to your ha device name comes directly from Google (which is my guess) or Home Assistant.
> 
> If it's the first, you will have problem if you don't match Home Assistant's Friendly Name and Chromecast's friendly name. If you want to keep that missmatch in your instance, you would have to either use the device name (with the chromecast friendly name, not the HA one) or use Spotify ID, which is more involved, but more reliable usually.

That's exactly what's happening. Good point though - I could refer to it by it's chromecast-friendly-name instead of entity_id. I'll give it a go with using the spotify_device_id too.

**Comment by wicol** [comment]
Oh actually this isn't a Spotify Connect device - just a cast device, so I take it `spotify_device_id` isn't an option?

**Comment by fcusson** [comment]
> That would be the log rows I included in my initial post :)
> The first of them comes from

My bad, checked too fast this morning was sure they were only error logs, not debug. 

> Oh actually this isn't a Spotify Connect device - just a cast device, so I take it spotify_device_id isn't an option?

In your case, the spotify_device_id will not work, because we need to first wake the google device, otherwise it's not available within Spotify API and we need to know the google friendly name of the device before being able to do that.

I also dig into the code and yes, when you provide an entity_id, we simply go and get the device name from HA and then try to communicate to the google api with it.

Can you confirm if using the device name worked even with the mismatch, because, there might still be problem when trying to send a wake command before doing the rest.

**Comment by wicol** [comment]
> Can you confirm if using the device name worked even with the mismatch, because, there might still be problem when trying to send a wake command before doing the rest.

Yep, just tried it and it works. And this way I get to keep my renamed friendly name in HA at least which is nice.
Is there any other attribute available on the media_player entity that could be used for the match? Like IP, MAC..?

**Comment by fcusson** [comment]
Saddly, no, this is a limitation in the way we interact with the GoogleCast API. We have to provide a device name. You don't need the home assistant device name and google name to be the same, but if they mismatch, you need to provide a device name and make it match the google name.

If you need them to mismatch, I would suggest you find a way to map home assistant name (or entity_id) to google names.

Saddly, not much I can do from this project, I will close the ticket for now
