### ISSUE TITLE
RANDOM SONG ON PLAYLIST NOT WORKING

### ISSUE THREAD

**Issue by LostName1** [fondberg/spotcast#383]
I am trying to make an automation with the Spotcast service, but even if I turn on "Random Song. Starts the playback at a random position in the playlist or album." It always plays the first song of the playlist, is there anyway to avoid this problem? Thanks!

**Comment by fcusson** [comment]
Hi @LostName1, we have a bug report template for a reason. Don't delete a form that a dev gives you to help him help you.

Please edit your ticket with the relevant information from [this link](https://raw.githubusercontent.com/fondberg/spotcast/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by fcusson** [comment]
Information requested from reporter 2 weeks ago without response. Closing the ticket
