### ISSUE TITLE
select multiple device for multiroom

### ISSUE THREAD

**Issue by marcdaure** [fondberg/spotcast#389]
Is it possible to define multiple device to enable a multiroom solution.
if yes what is the syntax?
thanks for your help

**Comment by fcusson** [comment]
@marcdaure, this must be done from the media player side itself. Spotify API doesn't manage groups. The casting protocol must impliment it's own solution and expose the group of speaker as a spotify connect device. The Spotify Connect API has a icon dedicated to groups, but in reality it doesn't do anyhting special it just sends the media stream to the endpoint of the device and lets the casting solution take care of the rest.

For chromecast device, this is achievable by creating media groups in the google home app. Other solution can leverage the `media_player.join` from Home Assistant which would let you create a media player group directly in Home Assistant and let HA manage the Single-Input -> Multiple-Ouptput. Saddly, google chromecast devices are not compatible with the join feature.

So, multiple ways to that, but not really within the scope of `Spotcast`.

**Comment by marcdaure** [comment]
Hi Felix,

Thanks a lot your quick and precise answer. I will manage this with multiple groups defined in google assistant.

Le 26 mars 2023 à 17:52, Felix Cusson ***@***.***> a écrit :

﻿

@marcdaure<https://github.com/marcdaure>, this must be done from the media player side itself. Spotify API doesn't manage groups. The casting protocol must impliment it's own solution and expose the group of speaker as a spotify connect device. The Spotify Connect API has a icon dedicated to groups, but in reality it doesn't do anyhting special it just sends the media stream to the endpoint of the device and lets the casting solution take care of the rest.

For chromecast device, this is achievable by creating media groups in the google home app. Other solution can leverage the media_player.join from Home Assistant which would let you create a media player group directly in Home Assistant and let HA manage the Single-Input -> Multiple-Ouptput. Saddly, google chromecast devices are not compatible with the join feature.

So, multiple ways to that, but not really within the scope of Spotcast.
