### ISSUE TITLE
Call value of HA input helper as Spotify URI

### ISSUE THREAD

**Issue by niallperks** [fondberg/spotcast#394]
I have a single button that triggers an automation to play music, however I want to be able to change the playlist based on time of day.
I've created an input helper and automations to change the value of the input helper to a valid URI for the spotcast service to call, however when saving the yaml and checking on it after it has a null value

This is the yaml I'm inputting

> service: spotcast.start
> data:
>   limit: 20
>   force_playback: false
>   random_song: true
>   repeat: "off"
>   shuffle: true
>   offset: 0
>   ignore_fully_played: false
>   uri: {{ states('input_text.spotifychill') }}
>   device_name: Home Speaker Group
>   start_volume: 15

This is what is looks like after saving

> service: spotcast.start
>     data:
>       limit: 20
>       force_playback: false
>       random_song: true
>       repeat: "off"
>       shuffle: true
>       offset: 0
>       ignore_fully_played: false
>       uri:
>         "[object Object]": null
>       device_name: Home Speaker Group
>       start_volume: 15

The value of the input helper is just `spotify:playlist:id`

![image](https://github.com/fondberg/spotcast/assets/35839988/616dd8bd-88d7-43a9-9efd-c94ae2304fd7)

Is there anywhere for the script to pull this value?

**Comment by niallperks** [comment]
## Environment

 - Installation type: [HA_OS]
 - HA version: [2023.6.3]
 - spotcast version: [3.7.0]

**Comment by fcusson** [comment]
This isn't related to spotcast but with home assistant  directly. I would suggest you open a thread in the forum.

I will close the ticket
