### ISSUE TITLE
Spotcast broke since Spotify changed password

### ISSUE THREAD

**Issue by sewershagger** [fondberg/spotcast#404]
# Bug Ticket

## Describe the bug

Spotify forced me to reset my password. Since the password has changed, spotcast stopped working (expectedly).

Since updating the spotify password, I fixed the Spotify integration and have put in both new SP keys into the config file and restarted home assistant. 

I get the error 'Failed to call service spotcast/start. connection lost'

Everything was working fine until the password changed. Am I missing any steps in order to get it back up and running after a password reset? Other than the new SP keys and updating the spotify integration (which is working), what else do I need to update?

I have made no other changed to home assistant or my spotify devices (speakers), only the password change.

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [* ] Using latest version of spotcast
* [ ] Using latest stable version of Home Assistant
* [* ] I have setup the Spotify integration in Home Assistant
* [ *] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ *] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core]
 - HA version: [2023.7 ]
 - spotcast version: [up to date ]

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
<insert configuration here>

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
<insert the yaml of the service call here>
````

## Logs

* normal|debug

````log
<please insert any relevent logs here>
````

## Additional context

<Add any other context about the problem here.>

**Comment by aliaghil** [comment]
I have the same issue, so I am commenting here to chase this topic.

**Comment by fcusson** [comment]
problem is due to #398 not your change of password. closing for duplicate
