### ISSUE TITLE
Text input > search request > play

### ISSUE THREAD

**Issue by jboesh** [fondberg/spotcast#407]
Hi, is it possible that I can search for a song in Spotify based on text input (is a helper)?  and play if something is found?  Could that possibly be linked in the Spotcast start service?  specifically this one: search.

` A Search request to the Spotify API.  Will play the most relevant search result`.

So what would be nice is that I type a song in a text helper and the spotcast service will search and play the music. With help of an automation I guess

Thanks!

**Comment by fcusson** [comment]
Yes that is exactly what search is for. Simply don't provide any URI
