### ISSUE TITLE
[Feature Request] Option to only play 1 song

### ISSUE THREAD

**Issue by Timmiej93** [fondberg/spotcast#410]
I guess this is gonna be pretty specific to my use case, but who knows.

I would love a toggle that lets you set "one song only" mode. A local media outlet has their latest news bulletins on Spotify in a playlist, so I can very easily use spotcast to play the most recent bulletin. Unfortunately, after that one is done, some random music starts. I would prefer the player to just go back to the "off" state, so I can sense that in HA and cast the next bit of media to it. Is that at all possible?

**Comment by martinsteinorth** [comment]
I just came across the exact same requirement. I have multiple podcast shows and would like to listen to the most recent episode of each of these shows to build an automation for a news routine.

**Comment by fcusson** [comment]
@Timmiej93 that wouldn't really be possible in a useful way. Spotcast loses context after sending a play request.

That's something you should deal with yourself in an automation directly.
