### ISSUE TITLE
spotcast stopped working (404) code -1

### ISSUE THREAD

**Issue by frelev** [fondberg/spotcast#42]
Running latest version spotcast  and Hass it stopped working for me.
When executing:
```
device_name: Kök
uri: 'spotify:playlist:37i9dQZF1DX3yvAYDslnv8'
random_song: true
repeat: track
```

I get an error message:
![image](https://user-images.githubusercontent.com/14004609/71771139-c77fc380-2f36-11ea-8a08-3ea41315909b.png)

Any idea?

**Comment by frelev** [comment]
Can it be that my password is starting with a reserved character (@) 
I´m not able to save this in configuration.yaml or secrets.yaml without capsuling it with either ' or "
Example

```
spotcast:
  username: !secret spotify_username
  password: '@ABC123'
```
How is this first character handled by the login script?

**Comment by fondberg** [comment]
Did it use to work with that password and the only thing that changed was an update of home assistant?

Can you add debug to the logger for the component and send me attach a log when it fails?

**Comment by fondberg** [comment]
Looking at the screenshot it seems like this is actually a spotify-card question and the error message suggests that the device is not found by spotify-api at their side.
Closing this.
