### ISSUE TITLE
Could not get spotify token

### ISSUE THREAD

**Issue by midunker** [fondberg/spotcast#421]
Hi, I had a working spotcast integration since month and I didn’t change anything.
Suddenly I got an error message:

`Failed to call service spotcast.start. Could not get spotify token.`

And the log entry:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:301
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 8:20:28 PM (2 occurrences)
Last logged: 8:20:31 PM

[547603782336] Error handling message: Could not get spotify token. (home_assistant_error) ... from ... (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36)
```

The Spotify Integration is working. I tested it in isolation.
I also refreshed the sp_key and sp_dc token in the spotcast config.
I still get this error and I don’t understand where it comes from.

Any ideas?

**Comment by SvenSvenApfel** [comment]
Got the same, did the same!

**Comment by Rafaille** [comment]
Same issue here. Spotify website refuses to open in incognito mode so I am unable to renew my token. I suspect this is an intended move from their part. Any idea of a workaround?

**Comment by SvenSvenApfel** [comment]
Spotify in Incognito works for me.

**Comment by vmartinv** [comment]
I was able to get a new sp_key and sp_dc. For some reason my device_id also changed. Once restarted, casting worked without issues.

**Comment by Rafaille** [comment]
Sorry about the late reply. My initial attempt to visit spotify website was on my phone (desktop mode), I was a bit too naive. I can confirm that the method to get the sp values still work (on a computer browser!).
For some reason these values had changed and updating them in spotcast did the trick.
Everything is back in order, apologies for the false alarm.

**Comment by XDKTOOR** [comment]
Hi @Rafaille!
I think I am having a similar issue with the spotcast integration ([see here](https://www.reddit.com/r/homeassistant/comments/1cilhra/comment/l2fcqox/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)).
Which steps did you specifically follow to get around this error? 
I am open to any suggestions.

**Comment by XDKTOOR** [comment]
@Rafaille 
Oh, okay. Glad it worked out for you. Sadly, I got the error although using my pc.
![Spotcast failed to call service spotcast start_could not get spotify token](https://github.com/fondberg/spotcast/assets/166228007/f95a518a-840f-4fca-b35f-edd7eb3a4ce4)

**Comment by Rafaille** [comment]
Are you sure you used private mode on your browser and quit the page without logging out?

**Comment by XDKTOOR** [comment]
@Rafaille Just to clarify: I need to visit the Spotify Developer Portal in incognito mode, retrieve the sp_dc and ps_key and then close the page without logging out? What kind of secret cheat code is this? :D

**Comment by fcusson** [comment]
Not the developer portal you need to login to spotify and get the cookie details from there
