### ISSUE TITLE
Maintainer passed away, donation button still active

### ISSUE THREAD

**Issue by paull27** [fondberg/spotcast#425]
The original maintainer Niklas Fondberg sadly passed away in June 2022, as stated on his _buy me a coffee_ page (also confirmed by a funeral notice through google search).

I propose to remove the original _buy me a coffee_ link/ to update it to the new maintainers. The website offered me a refund because I only noticed afterwards.

**Comment by JPT62089** [comment]
That is so sad to hear :( My condolences to @fondberg friends and family.

Since the maintainer has deceased, what does that mean for the project moving forward as far as this repository? Will it be forked to a new official repository?

**Comment by IIIdefconIII** [comment]
kinda got something working:
![image](https://github.com/user-attachments/assets/5ea5902b-cb68-4c96-aa45-5c246b95422d)

**Comment by IIIdefconIII** [comment]
![image](https://github.com/user-attachments/assets/bfb04041-af55-4a48-b8a1-99276bee2038)

**Comment by fcusson** [comment]
Was keeping the ticket active for people to see. Closing now to not stay in the active ticket list
