### ISSUE TITLE
2024.3.0b1 Failed to call service spotcast/start. SpotifyController.launch_app.<locals>.callback() takes 0 positional arguments but 2 were given

### ISSUE THREAD

**Issue by FrancoLoco** [fondberg/spotcast#429]
when casting with ha beta i get:

Failed to call service spotcast/start. SpotifyController.launch_app.<locals>.callback() takes 0 positional arguments but 2 were given

**Comment by hmmbob** [comment]
Yeah, I just came over to report this here as well.

Looking for more information, I noticed that `pychromecast` 14.0 had some breaking changes - and this is probably one of the breaking items:

https://github.com/home-assistant-libs/pychromecast/releases/tag/14.0.0

**Comment by mattred33** [comment]
Same issue as soon as I updated to 2024.3.

**Comment by mhoogenbosch** [comment]
Yes, for me too

When checking with developer tools to check config:

```
Configuration warning
Component error: spotcast - cannot import name 'LaunchError' from 'pychromecast.error' (/usr/local/lib/python3.12/site-packages/pychromecast/error.py)
```

Version running: 2024.3.0b3

**Comment by fcusson** [comment]
There is a few refactoring that we will have to do to make it work, mainly callbacks must be done with keywords arguments now and we are using positional at the moment and some errors have moved.

**Comment by FrancoLoco** [comment]
> v3.7.2 was just released. This is no longer an issue with this version on my end. Can you confirm? @FrancoLoco

Wow, quick fix, trying right away

**Comment by FrancoLoco** [comment]
> v3.7.2 was just released. This is no longer an issue with this version on my end. Can you confirm? @FrancoLoco

Yes, it's working number 1, great job thanks! :)

**Comment by mhoogenbosch** [comment]
Same goes for me, no more errors.

**Comment by hmmbob** [comment]
Yep, confirmed fixed.
