### ISSUE TITLE
Support Spotify API keys

### ISSUE THREAD

**Issue by williamson10** [fondberg/spotcast#43]
Any chance of this project supporting Spotify API keys? I'd rather store those than my user/pass combo plus I already have them stored for the [Spotify component](https://www.home-assistant.io/integrations/spotify/).

**Comment by fondberg** [comment]
Unfortunately not. The whole reason for the plugin is to use the more powerful token received using web login to initiate playback on chromecast

**Comment by fondberg** [comment]
Closing this
