### ISSUE TITLE
Setup failed for custom integration 'spotcast': Unable to import component: cannot import name 'LaunchError' 

### ISSUE THREAD

**Issue by LuisFRPE** [fondberg/spotcast#433]
# Bug Ticket

## Describe the bug
Setup failed for custom integration 'spotcast': Unable to import component: cannot import name 'LaunchError' from 'pychromecast.error' (/usr/local/lib/python3.12/site-packages/pychromecast/error.py)

Spotcast is seen as unknown in the most recent stable version of Home Assistant 

Home Assistant

Core
2024.3.0
Supervisor
2024.02.1
Operating System
12.0
Frontend
20240306.0

## Troubleshooting

Logger: homeassistant.setup
Source: setup.py:296
First occurred: 8:19:32 AM (1 occurrences)
Last logged: 8:19:32 AM

Setup failed for custom integration 'spotcast': Unable to import component: cannot import name 'LaunchError' from 'pychromecast.error' (/usr/local/lib/python3.12/site-packages/pychromecast/error.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 296, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 894, in async_get_component
    comp = self.get_component()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 921, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/spotcast/__init__.py", line 61, in <module>
    from .spotcast_controller import SpotcastController
  File "/config/custom_components/spotcast/spotcast_controller.py", line 20, in <module>
    from .spotify_controller import SpotifyController
  File "/config/custom_components/spotcast/spotify_controller.py", line 15, in <module>
    from pychromecast.error import LaunchError
ImportError: cannot import name 'LaunchError' from 'pychromecast.error' (/usr/local/lib/python3.12/site-packages/pychromecast/error.py)

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [x] Using latest version of spotcast
* [x] Using latest stable version of Home Assistant
* [x] I have setup the Spotify integration in Home Assistant
* [x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [x] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core]
 - HA version: [ ]
 - spotcast version: [ ]

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
<insert configuration here>

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
<insert the yaml of the service call here>
````

## Logs

* normal|debug

````log
<please insert any relevent logs here>
````

## Additional context

<Add any other context about the problem here.>

**Comment by fcusson** [comment]
Hi @LuisFRPE you didn't provide the spotcast version you are using. I see you marked that you are using the latest version of spotcast, but we are no longer using `pychromecast.LauchError` in the newest version, which leads me to believe you have an outdated version.

Can you please confirm what is the current version of spotcast on your system. I tested on my side with a 2024.3 container and everything works without problem.

**Comment by LuisFRPE** [comment]
Thanks for the reply! It was indeed at 3.7.1. I have updated now to 3.7.3
and will test it. Really appreciate your help on this!

Felix Cusson ***@***.***> escreveu (domingo, 10/03/2024 à(s)
21:41):

**Comment by fcusson** [comment]
closing due to no update from user

**Comment by pgross41** [comment]
I had the issue, found this, updating spotcast fixed it... thanks!
