### ISSUE TITLE
Can't skip or go next song

### ISSUE THREAD

**Issue by maos999** [fondberg/spotcast#436]
# Bug Ticket

## Describe the bug

When playing song from a playlist It won't go to the next song and only playing one song then stop 

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [ x] Using latest version of spotcast
* [ x] Using latest stable version of Home Assistant
* [ x] I have setup the Spotify integration in Home Assistant
* [ x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ x] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [Core]
 - HA version: [2024.3.1 ]
 - spotcast version: [ 3.7.3]

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
<insert configuration here>

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
<insert the yaml of the service call here>
````

## Logs

* normal|debug

````log
<please insert any relevent logs here>
````

## Additional context

<Add any other context about the problem here.>

**Comment by fcusson** [comment]
@maos999 are to calling the playlist or the song when providing the URI?

**Comment by maos999** [comment]
I was calling the song hehe 
My bad, user mistake... 

I have disabled the URI and enabled the force playback. 
Work like expected now thanks
Keep up the good work!
