### ISSUE TITLE
pychromecast: failed to connect.

### ISSUE THREAD

**Issue by tobimori** [fondberg/spotcast#44]
Could not find anything similiar on the net so I'm posting this as an issue here:
When running spotcast.start with an existing device (as per sensor) or using the lovelace component pychromecast logs the following:

`ERROR (Thread-239) [pychromecast.socket_client] [record[a,in-unique,f1fadb91-446e-6e5a-e5d8-668776a5c754.local.]=120/119,192.168.1.22:8009] Failed to connect, retrying in 5.0s`

Using another device didn't work either.
Connecting with the Spotify app works fine.

**Comment by moejetz** [comment]
Same here! This keeps happening over and over again. Sometimes it works fine, sometimes it doesn't.
It's just not stable reproducible. Unfortunately I believe this is a "bug" on the Spotify side because they do not support the official Chromecast APIs but instead do their own thing called Spotify Connect...
Very annoying.
@fondberg do you have any further information about that?

**Comment by tobimori** [comment]
@moejetz It never worked for me tho.

**Comment by alignus-abe** [comment]
Same issue - When I use my phone to select Living Room Speakers then the spotify-card shows Living Room Speakers as a Spotify Connect option and everything works great. Unfortunately, as soon as I select local playback from my phone (headphones, etc) I lose the Living Room Speakers in Spotify Connect and can no longer initiate playback from the card.

Error is ```
[record[a,in-unique,a0f395f4-1635-f3e6-f560-ac4b91393dd8.local.]=120/119,192.168.86.37:8009] Failed to connect, retrying in 5.0s
Connection lost. Reconnecting…
```

**Comment by netrene** [comment]
I have the same problem. It always worked fine and since I updated HA to 104 it stopped working.

I get the same error message.

**Comment by fondberg** [comment]
Can you try downgrading zeroconf to the previous version as it was before 1.0.4?

**Comment by fondberg** [comment]
https://github.com/balloob/pychromecast/issues/332

**Comment by tobimori** [comment]
@fondberg How do I downgrade zeroconf on Home Assistant?

**Comment by fondberg** [comment]
I'm not sure about hass.io, sorry

**Comment by fondberg** [comment]
Just released v.2.6.0 which pins the zero conf version to 0.24.3 which should make it work again. 0.24.4 didn't contain that much so I think it is safe to use 0.24.3.
It is kind of a rewrite so please help test it.

**Comment by tobimori** [comment]
Seems like my hass.io instance crashes as soon as I execute spotcast.start.

**Comment by netrene** [comment]
For me on hass.io it crashes also very hard. I have to reboot my NAS to make it work again. Nothing in the logs after reboot.

**Comment by fondberg** [comment]
Try the new one 2.6.1 and if it fails, please send logs with debug=true

**Comment by moejetz** [comment]
@fondberg can confirm 2.6.1 works again! thanks a lot for your effort!

**Comment by tobimori** [comment]
Can confirm that too. Thanks!

**Comment by wso277** [comment]
> 
> 
> Seems like my hass.io instance crashes as soon as I execute spotcast.start. @fondberg

Sorry for commenting on the closed issue @fondberg , but I still have this problem

Using homeassistant 0.105.4 in hasio with spotcast 2.7.2.

Plugin seems to work perfectly for a few hours, but after a while when I call spotcast.start from an automation it completely shuts down my homeassistant instance.

I have a similar Failed to connect log immediately before it crashes as well

**Comment by moejetz** [comment]
@fondberg @wso277 I experience the same problem.
It seems like the spotcast service is executed synchronously which causes the complete home assistant setup to wait until the service has finished. From time to time, the service fails to start and never finishes, leaving home assistant in a completely unresponsive state.

**Comment by fondberg** [comment]
There was an issue up to 2.7.1 whi could cause a freeze. Can you try the newest version?

**Comment by wso277** [comment]
Just updated, i'll report back if it still causes freezes during my automations

**Comment by minideezel** [comment]
I'm running 2.8 and can confirm this is still happening for me. For me it seems to be tied with not requesting things or playing music for a while, so the first time I try to cast after sitting for a while HA will crash.

**Comment by wso277** [comment]
@fondberg @minideezel can confirm, issue remains in the same scenario.

Works a few hours after restart but crashes everything after a while of not happening. Logs remain the same but I also see during the day some Heartbeat timeout errors From pychromecast related with the chromecast/minis.

**Comment by fondberg** [comment]
Please open a new issue and be sure to include HA version, spotcast version, logs when spotcast level is debug.

The issue this issue is describing was solved which means new issues need further investigation!
