### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by OrbitMan92** [fondberg/spotcast#440]
# Bug Ticket

## Describe the bug

Hello I've installed HAS and got that working then I installed spotcast.
 
I added the config as per the instructions and added the keys from the Spotify cookies into the secrets file as requested.

I restarted HA but spotcast is not showing in integrations or services and when I use the Spotify card that uses spotcast it says it's not installed.

I've checked the spotcast files on the server and they look correct and checked that my configs and secrets have saved and they are fine.

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [ X] Using latest version of spotcast
* [ X] Using latest stable version of Home Assistant
* [ X] I have setup the Spotify integration in Home Assistant
* [ X] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ X] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type:  HAS on a HA Green
 - HA version: latest
 - spotcast version: latest

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
<insert configuration here>

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
<insert the yaml of the service call here>
````

## Logs

* normal|debug

````log
<please insert any relevent logs here>
````

## Additional context

<Add any other context about the problem here.>

**Comment by fcusson** [comment]
Hi @OrbitMan92 We will need a bit more information to help you.

- Do you have any error logs related to spotcast at boot?
- Can you provide your config for spotcast?

If you don't have error logs something went wrong during the installation, you should at least get either home assistant telling you spotcast doesn't exist or spotcast saying your configuration is wrong.

**Comment by OrbitMan92** [comment]
![Screenshot 2024-04-20 133815](https://github.com/fondberg/spotcast/assets/109963823/c4b5fc58-1fe4-475c-9565-1681aad2bce6)

Please see the screenshot of config above.

Secrets I won't share but i've definitely using the right keys from the inspector in Chrome with spotify.

In terms of logs am I looking at Settings > System > Logs? If so when I search for spotcast i'm not seeing antything.

**Comment by fcusson** [comment]
@OrbitMan92 

so something is clearly wrong in your configuration. if you provided wrong credentials we would have sent an error log. Also, you should at least have a warning log saying spotcast is a custom_component and untested by the HASS project.

````log
2024-03-19 09:18:32.420 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
````

if you don't have that, then Home Assistant isn't even loading custom_component. Can you validate if at least you have a warning for HACS?

Also, you marked latest for spotcast and home assitant version, please provide actual versions. It might look dumb, but everyone believes they are on the latest version until they actually check.

Finally, spotcast, will not show in integration, since we didn't make the integration native to the UI yet, but you should have a service called `spotcast.start` once the setup goes through successfully.

**Comment by fcusson** [comment]
@OrbitMan92.... just a dumb validation to make sure, can you confirm in what folder `hacs` and `spotcast` are?

**Comment by OrbitMan92** [comment]
Yes I get this in the log:

2024-04-20 10:49:56.790 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant


Versions is 3.7.3

Noted about the integration but still no service is showing and the Spotify card is throwing an error saying I need spotcast.

HACS and spotcast are in custom_components

**Comment by OrbitMan92** [comment]
I rebooted a few more times and now the service is working, weirdly the spotify card is half broken (keeps saying loading) but guess that's something to chat to the card developer about.

**Comment by fcusson** [comment]
Closing due to problem resolves
