### ISSUE TITLE
Manifest still reporting version 3.6.30

### ISSUE THREAD

**Issue by tsvi** [fondberg/spotcast#447]
# Bug Ticket

## Describe the bug

The next version of home assistant (2024.8) brings with it the capability to see YAML based configs in the UI.
It shows spotcast being at 3.6.30.

I see the manifest.json is showing that version number in the master branch.

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [ ] Using latest version of spotcast
* [ ] Using latest stable version of Home Assistant
* [ ] I have setup the Spotify integration in Home Assistant
* [ ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core]
 - HA version: [ ]
 - spotcast version: [ ]

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
<insert configuration here>

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
<insert the yaml of the service call here>
````

## Logs

* normal|debug

````log
<please insert any relevent logs here>
````

## Additional context

<Add any other context about the problem here.>

**Comment by fcusson** [comment]
thanks for the report, found the bug in bumpversion configuration. Version will be aligned on all files with next release
