### ISSUE TITLE
Icon Update

### ISSUE THREAD

**Issue by milandzuris** [fondberg/spotcast#449]
Hi please add Icon to Update (Spotify Icon)

![image](https://github.com/user-attachments/assets/56b45fa0-1f54-4b08-b491-365786ba1036)

**Comment by fcusson** [comment]
Hi @milandzuris Spotcast doesn't have an official icon and Spotify icon is trademarked by spotify, we have no right to use it. If you have a proposition for an icon for the project i would be interested in making the necessary step with hacs to add the icon.

Just to provide additional information, this icon must be made part of the [https://github.com/home-assistant/brands](https://github.com/home-assistant/brands) project in order to show up in home assistant

**Comment by n00bcodr** [comment]
Is that a hard rule that we cannot include the Spotify icon in the spotcast icon?

https://github.com/home-assistant/brands has many official icons that are owned by corporations?

A quick whip in chat GPT spits out![image](https://github.com/user-attachments/assets/52107dca-302d-49b5-a0e1-43d729f5d877)

I am no designer, probably someone can do something :)

**Comment by fcusson** [comment]
> Is that a hard rule that we cannot include the Spotify icon in the spotcast icon?

Multiple home assistant plugins were taken down for "stupid/legal" reason, I would prefer to not take the risk, If we can at the same time get our own brand identity I wouldn't be against it.

**Comment by ironcrafter54** [comment]
I don't think it is something you need to worry about as the home assistant integration uses the spotify logo, as well as the official spotify connect addon.

**Comment by ironcrafter54** [comment]
how about this
![lgog](https://github.com/user-attachments/assets/fe27f8dd-5c50-49d0-832b-89b5577d8880)

**Comment by milandzuris** [comment]
![Spotcast](https://github.com/user-attachments/assets/0765d02f-25c0-46a6-8659-3e6c681c032c)

**Comment by Select446** [comment]
![icon](https://github.com/user-attachments/assets/b3efafd7-f0e5-4bda-9538-acd71e0c9f01)

**Comment by fcusson** [comment]
Just to mention to everyone, I'll release a logo with the release of v4 (I like the idea of a new fresh logo with a fresh new major version).

I'll try to involve the community at this point to check which logo is prefered

**Comment by fcusson** [comment]
@milandzuris, @Select446, @ironcrafter54 @hmmbob (mentionning a few that interacted in this post plus frequent contributors). I have tken the different ideas for logo and tested a few variant with the help of my partner and we came up with this design:

# Icon
## Standard Resolution
![icon](https://github.com/user-attachments/assets/672c569e-d88d-4597-ba50-4b764fc39462)

## hDPI
![icon@2x](https://github.com/user-attachments/assets/2d9b3f8a-232e-41dc-816b-ec16804f7bc0)

# Logo
## Standard resolution
![logo](https://github.com/user-attachments/assets/fcfea2aa-b1c7-4693-8ba7-c16d73331ef8)

## hDPI
![logo@2x](https://github.com/user-attachments/assets/b2e997f5-5eb6-41f6-87dc-902ffaac6bd0)

# Dark Logo
## Standard Resolution
![dark_logo](https://github.com/user-attachments/assets/3dd35e87-1e1d-4b8c-af91-418ad0715281)

## hDPI
![dark_logo@2x](https://github.com/user-attachments/assets/46f5695d-caf8-4e97-a1bb-81687785a401)

I'm really looking for feedback at this point to see if people are:
1. Liking the idea
2. Have any improvement they would like to offer

**Comment by ironcrafter54** [comment]
Yeah that is definitly the way to go this looks much better.
<img width="1486" alt="image" src="https://github.com/user-attachments/assets/1ad38a07-a82d-4551-ae9b-79366582ddbe">
<img width="1486" alt="image" src="https://github.com/user-attachments/assets/4beb8a95-6628-4771-b541-479b077789ee">

**Comment by fcusson** [comment]
really likes the idea of also coloring the text, I'll just check if the contrast ratio is enough with the white background. Also, this will probably have very little effect, but the default home assistant theme is using `#111111` for dark background and `#FAFAFA` for light. I'll use those for checking the contrast

**Comment by fcusson** [comment]
Just checked and We'll have to figure out an accessible solution. These are the constrast ration, usually, its recommanded too have minimum a `4.5:1` to ensure accessible color constrat:

| Foreground | Background | Ratio |
| :---: | :---: | :---: |
| `#00ff84` | `#fafafa` | `1.28:1` | 
| `#00ff84` | `#111111` | `14.06:1` |

**Comment by ironcrafter54** [comment]
It looks like a darker green of `#17A649` will pass the WCAG AA requirement for large text while still looking quite spotify-y.

**Comment by fcusson** [comment]
I reworked the logo (in a real vector graphic editor this time) and have a few more variant. The casting frame now uses rounded edges and the inner logo is a cutout of the circle letting the background colour through

# Spotify Green
![logo](https://github.com/user-attachments/assets/ccf94fac-cc3b-4c56-a81a-838dfe111f19)

# With a Capital C
![logo_cc](https://github.com/user-attachments/assets/79e3231c-cd7b-41e6-b885-b6e01dd48657)

# White Variant
![logo_w](https://github.com/user-attachments/assets/f8f57288-3f80-4e1c-a783-3177d005abaa)
![logo_w_cc](https://github.com/user-attachments/assets/11b98511-d027-4b06-82cd-8197572e4db2)

# Black Variant
![logo_b](https://github.com/user-attachments/assets/0824bdfa-6410-450a-855f-f8667c0eec42)
![logo_b_cc](https://github.com/user-attachments/assets/1ea7ef74-0660-4a6a-a50d-4c2924bfe1d3)

# Dark Gray Variant
![logo_dg](https://github.com/user-attachments/assets/64b7e140-658a-4f58-99f6-f50c688cd41f)
![logo_dg_cc](https://github.com/user-attachments/assets/e4537e6a-1264-4db6-b647-70470c515a97)

The RGB codes for the different variants are:
- **Spotify Green:** `#1eb760`
- **Black:** `#111111`
- **White:** `#fafafa`
- **Dark Gray:** `#232323`

**Comment by fcusson** [comment]
so the logo will only be part of the repository. I opened the request to add the spotcast logo to the main `ha-brands` and they wanted to maintain the Spotify logo specifically for that. The PR has been approved and the logo is already available in HACS. Should become available shortly for the Devices & Services section
