### ISSUE TITLE
Add ability to control volume calling a HA service.

### ISSUE THREAD

**Issue by polmonta** [fondberg/spotcast#454]
# Bug Ticket

## Describe the bug

This is more of a suggestion rather than a bug, but I was unable to create a bug ticket.
I am using Spotcast to cast music to my Alexas through Airplay. Currently, I have an automation that changes the Echo's volume when a volume change is detected in the Airplay player. However, this takes long because the Alexa Media Player has some delay when it changes the device's volume. That's why I would love to have the ability to control my device's volume straight from Spotify (Spotcast). I have found in the Spotify docs that you can achieve this with a [PUT request](https://developer.spotify.com/documentation/web-api/reference/set-volume-for-users-playback) and there is no delay at all. 

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [ x] Using latest version of spotcast
* [ x] Using latest stable version of Home Assistant
* [ x] I have setup the Spotify integration in Home Assistant
* [ x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x ] (optional) I have Spotify Premium
* [ x] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ x] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core]
 - HA version: 2024.8.2
 - spotcast version: 3.8.1

## Configuration

````yaml
-
````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
-
````

## Logs

* normal|debug

````log
-
````

## Additional context

Nothing else. I really appreciate your work as this integration is very useful :)

**Comment by fcusson** [comment]
could be part of the data packet in v4. But would cfeate too much additional settings in the current version. I'll keep it in the log for When I'll be in that section in the refactor.

**Comment by polmonta** [comment]
No, there is no problem at all. I just thought it might be a nice feature to have if it's not too hard to implement.

**Comment by fcusson** [comment]
No it is

![Screenshot 2024-10-31 073928](https://github.com/user-attachments/assets/75ca1c97-c593-4d81-8251-78565928dd18)

**Comment by fcusson** [comment]
@polmonta can you confirm if you can see the Start Volume option after reinstalling Spotcast?

**Comment by polmonta** [comment]
> @polmonta can you confirm if you can see the Start Volume option after reinstalling Spotcast?

I can confirm I can see it now. I had to update HA to 2024.11.1 to be able to able to reinstall Spotcast (v4.0.0), as it wouldn't let me install it unless I was in HA 2024.11.x. Thank you.
