### ISSUE TITLE
Impossible to install Spotcast 3.9.1

### ISSUE THREAD

**Issue by Fatalmose** [fondberg/spotcast#467]
# Bug Ticket
![IMG_0651](https://github.com/user-attachments/assets/74370ddf-a824-45e2-b077-b7db997e0c05)

## Describe the bug
Error statement saying you need HA 2024.11.0 or newer.
<A clear and concise description of what the bug is.>

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [ ] Using latest version of spotcast
* [x] Using latest stable version of Home Assistant
* [x] I have setup the Spotify integration in Home Assistant
* [x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core]
 - HA version: [2024.10.4]
 - spotcast version: [3.9.0 ]

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
<insert configuration here>

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
<insert the yaml of the service call here>
````

## Logs

* normal|debug

````log
<please insert any relevent logs here>
````

## Additional context

<Add any other context about the problem here.>

**Comment by fcusson** [comment]
Hi @Fatalmose, as mentioned in the changelog, this update is to make spotcast compatible with 2024.11 because of a change in library. This is completely normal and you shouldn't try to install it on 2024.10 or older.

Closing for not being a bug

**Comment by Fatalmose** [comment]
Ok, thanks for the clarification.
Sorry for the misunderstanding.
My mistake.

Le lun. 4 nov. 2024 à 14:53, Felix Cusson ***@***.***> a
écrit :
