### ISSUE TITLE
Unable to install Spotcast v3.9.0

### ISSUE THREAD

**Issue by bt-beardedtechie** [fondberg/spotcast#468]
# Bug Ticket
![Screenshot](https://github.com/user-attachments/assets/4826818f-39fd-4d6b-8c46-af8370a98cfb)

## Describe the bug

Unable to download v3.9.0 (latest compatible with HA v2024.10) via HACS

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [ ] Using latest version of spotcast
* [x] Using latest stable version of Home Assistant
* [x] I have setup the Spotify integration in Home Assistant
* [x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x] (optional) I have Spotify Premium
* [x] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: Container
 - HA version: 2024.10.4
 - spotcast version: 3.9.0

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
<insert configuration here>

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
<insert the yaml of the service call here>
````

## Logs

* normal|debug

````log
<please insert any relevent logs here>
````

## Additional context

<Add any other context about the problem here.>

**Comment by Pr0mises** [comment]
Maybe I'm misreading the release but it states:
`This version of Spotcast isn't compatible with Home Assistant 2024.10 or older due to a change in the core library used by the Spotify Integration. v3.9.0 is the newest compatible version for older Home Assistant installation.`

Therefore this version is NOT compatible with any HASS version? That's confusing xD

**Comment by fcusson** [comment]
@bt-beardedtechie, very weird, v3.9.0 was se to 2022.3 at the time. Loonking into

![image](https://github.com/user-attachments/assets/aa3a5ffb-9879-4e36-a3a4-fff58f8490d4)

**Comment by bt-beardedtechie** [comment]
Yeah v3.9.2 has this stated but I'm trying to download v3.9.0 which is supposed to be compatible with HA 2024.10.4 as per release notes.

**Comment by fcusson** [comment]
something is weird in hacs, the error message isn't even the expected one

`v3.9.0`:
![image](https://github.com/user-attachments/assets/6ad060ac-7d52-425d-9581-583b63473f35)

`v3.9.2`:
![image](https://github.com/user-attachments/assets/87b46724-3b22-4746-8632-9d6ade9b0f92)

**Comment by bt-beardedtechie** [comment]
So something up with HACS then?

**Comment by fcusson** [comment]
@bt-beardedtechie not ready to point fingers yet, but this is clearly a different error raised by HACS than the first one. I'll check what the debug logs from HACS are saying

**Comment by bt-beardedtechie** [comment]
> @bt-beardedtechie not ready to point fingers yet, but this is clearly a different error raised by HACS than the first one. I'll check what the debug logs from HACS are saying

Of course!

**Comment by rhasselbusch** [comment]
Same problem here with same versions, can provide logs if necessary.

**Comment by fcusson** [comment]
@rhasselbusch waiting on HACS to provide more information, there are no reason that updating the minimal version of a new release should break an old one people have been able to confirm was working

**Comment by fcusson** [comment]
so its fixed now, HACS decided that it cares about your master branch only when you add `b0` in your minimal version and can even break older release when that happens. You will be able to install spotcast up to 3.9.0 now

**Comment by rhasselbusch** [comment]
Works perfect, thx! :-)

**Comment by fcusson** [comment]
created [issue ticket](https://github.com/hacs/integration/issues/4183) for HACS. In the meantime, closing the ticket
