### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Turac0** [fondberg/spotcast#470]
# Bug Ticket

## Describe the bug

<A clear and concise description of what the bug is.>

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [ No, 3.9.0 ] Using latest version of spotcast
* [ Yes, 2024.10.4 ] Using latest stable version of Home Assistant
* [ Yes ] I have setup the Spotify integration in Home Assistant
* [ No ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ Y ] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ Y ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [ HA_OS ]
 - HA version: [ 2024.10.4 ]
 - spotcast version: [ 3.9.0 or ANY other ]

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
<insert configuration here>

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
<insert the yaml of the service call here>
````

## Logs

* normal|debug

````log
2024-11-05 19:07:46.749 DEBUG (MainThread) [custom_components.hacs] <Integration fondberg/spotcast> Getting hacs.json for version=v3.9.0
2024-11-05 19:07:46.749 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/fondberg/spotcast/v3.9.0/hacs.json
2024-11-05 19:07:47.128 INFO (MainThread) [custom_components.hacs] Starting download, v3.9.0
2024-11-05 19:07:47.128 INFO (MainThread) [custom_components.hacs] <Integration fondberg/spotcast> Running pre installation steps
2024-11-05 19:07:47.129 INFO (MainThread) [custom_components.hacs] <Integration fondberg/spotcast> Pre installation steps completed
2024-11-05 19:07:47.129 INFO (MainThread) [custom_components.hacs] <Integration fondberg/spotcast> Running installation steps
2024-11-05 19:07:47.129 DEBUG (MainThread) [custom_components.hacs] <Integration fondberg/spotcast> Getting repository information
2024-11-05 19:07:47.366 DEBUG (MainThread) [custom_components.hacs] <Integration fondberg/spotcast> Did not update, content was not modified
2024-11-05 19:07:47.367 ERROR (MainThread) [custom_components.hacs] <Integration fondberg/spotcast> Downloading fondberg/spotcast with version v3.9.0 failed with (The version of Home Assistant is not compatible with this version)
2024-11-05 19:14:38.397 ERROR (MainThread) [custom_components.hacs] <Integration fondberg/spotcast> Downloading fondberg/spotcast with version v3.9.0 failed with (The version of Home Assistant is not compatible with this version)
````

## Additional context

I am trying to install Spotcast for the first time. It seems like a came at a bad timing since i understand there are major changes in compatability right now. But essentially im trying to install the version compatible with my HA (see details above). Im getting the error version v3.9.0 not compatible with this version of HA. From what I have read 3.9.0 is the version I should use, I have also tried earlier and later versions but get similar response.

**Comment by Turac0** [comment]
> @Turac0, just tested and unable to reproduce your bug

Strange, tried at the same timepoint as I published the issue. Any way to get more logs?

**Comment by fcusson** [comment]
@Turac0 saddly no, that's the highest level of verbosity for HACS. I decreased the minimal version in master, it strangely seems to help with the bug, even if the minimal version in the release is unchanged. Can you retry?

**Comment by Turac0** [comment]
@fcusson Still same error unfortunately.

**Comment by fcusson** [comment]
@Turac0, and what if you click on `update information` first? Trying different things at this point

![image](https://github.com/user-attachments/assets/c24d4fdd-8f25-487d-9fdc-7c3c9cd9c8c2)

**Comment by Turac0** [comment]
@fcusson No difference. Im sorry to bother you but happy to continue troubleshooting, tomorrow.

**Comment by fcusson** [comment]
@Turac0 no that's fine, I'm here to help. I must say I have no idea what's breaking for your specific case

**Comment by johnoldiges** [comment]
I am unable to update as well. I have tried clicking update information in Hacs. Trying to redownload to 3.9.1 give the message "This version requires Home Assistant 2024.11.0 or newer." Trying to update to 3.9.2 give this message "This version requires Home Assistant 2024.11.0b0 or newer." I am however able to redownload (downgrade) to 3.9.0.....

This is my current system versions if that will help.

Core: **2024.10.4**
Supervisor: **2024.10.3**
Operating System: **13.2**
Frontend: **20241002.4**

**Comment by fcusson** [comment]
@johnoldiges, that is completely normal `v3.9.1` and later are for tomorrows release of `2024.11`. The other user is having issues installing `v3.9.0`. This is a different issue

**Comment by johnoldiges** [comment]
Ah, my bad was unaware of the immanent release of 2024.11.

**Comment by NicoOosterwijk** [comment]
Bad idea to release this version prior to HA 2024.11

**Comment by fcusson** [comment]
@NicoOosterwijk next time i will release after HomeAssistant and point to comments like that when people open tickets that Spotcast is broken. Learned my lesson, better to have a broken spotcast on new Home Assistant release then trying to be proactive and helpful.

Didn't think having to wait 2 days for an update was an hassle, guess I was wrong, very sorry to everyone that got annoyed by it.

**Comment by fcusson** [comment]
`v3.9.2` was removed for the high level of annoyance it was causing. Will be rereleased when I have the time

**Comment by Turac0** [comment]
Closing this issue with hope that it will solve itself with the release of v4 and HA update.
