### ISSUE TITLE
Sorry for the botch release

### ISSUE THREAD

**Issue by fcusson** [fondberg/spotcast#471]
Just wanted to create this post due to the flood of comments and message I'm receiving with the proactive release `v3.9.2`.

First off, sorry for everyone that didn't like the release. That release was yes rushed because I'm really trying to be more proactive and present on this project than I have been in the past and wanted to not let down people this time like I did in the past by taking weeks to solve issues because of a change in Home Assistant. Saying that I manage the release badly is an f'ing understatement.

I tried to juggle my dayjob where we have one person missing causing a lot of work to fall on my plate, my personal life and maintaining this project. The last few years have been taking a toll on my mental health and my motivation as a programmer in general, but I was finally in a spot where I started to be motivated again to code by doing the full rewrite of the integration.

I was kind of blindsided by the library change that the main Spotify Integration decided to do. Seeing the eminent release of `2024.11`. Lesson learned, you can stop saying how annoyed you were by the release, I get it. `v3.9.2` and `v3.9.1` have been removed from the repo. As suggested, this release will be rebranded `v4.0.0` due to the breaking change.

Hope this appease everyone, sorry again for everything

**Comment by rdenis1** [comment]
All good my man - looking forward to v4.0.0 once its all sorted.  Appreciate your work and listening to the community feedback!

**Comment by mikekay1** [comment]
All good dude, the amount of things that people expect for free nowadays it abysmal! Don't be sorry at all, really it's a matter of maybe more people helping out. I'll message you directly about some resources I might be able to help out with! 

Cheers mate!

**Comment by XalaTheShepard** [comment]
I noticed the remark in the update that it was a breaking change as from 2024.11.0 and waited with the update untill the new HA Core come out. Was just checking why I didn't see the update anymore and noticed this comment. First of all I want to thank you for keeping this project alive and can only admire your dedication to provide a solution of the upcoming change in advance. There is nothing to blame, as it was clearly stated to be a breaking change as from HA Core 2024.11.0 . Having some health issues myself and some family members, I can understand your situation very well and how difficult it can be. 🙂

**Comment by pabloromeo** [comment]
Completely understandable! I've been there myself, juggling the day job with an open source project.
Thank you for the hard work!
I'll happily install the update once you believe it's ready.

**Comment by kafka0** [comment]
No worries, take your time ;-)

**Comment by madAndroid** [comment]
This is the sad truth of the matter:

![IMG_9802](https://github.com/user-attachments/assets/282fcc84-3a72-4639-853e-bc435804e40d)

**Comment by mordonez** [comment]
Don’t worry! Thanks to your hard work, we can play music however and wherever we want and that’s priceless. 

Take your time, keep going, and **make sure to take care of yourself too**. The releases can wait.

**Comment by gjincy88** [comment]
I saw the braking change in the notes and didn't update until the 2024.11 release of ha. Now the update has been remove but I can wait. Thank you for the update and all your hard work take care of yourself too.

**Comment by fcusson** [comment]
[v4.0.0](https://github.com/fondberg/spotcast/releases/tag/v4.0.0) released

**Comment by michaelarnauts** [comment]
Don't feel sorry. You did what was best, making sure a fixed spotcast release was ready before the actual Home Assistant release came out. Try to ignore the comments from people who can't stand to see an update icon they can't click yet. I really don't see the problem.

Thanks a lot for you work on this! Personal life always comes first. Take care!

**Comment by n00bcodr** [comment]
@fcusson You should not or need not apologise to anyone for anything! People tend to forget FOSS developers also have a life apart from this.

Spotcast was one of the first custom integrations I installed when I set up HomeAssistant 5 years ago.

I am grateful someone took over after @fondberg (R.I.P.) 

Thank you for that!

**Comment by mdieperink** [comment]
Dude, you don't have to be sorry about anything. It's not your fault people don't f'ing read the releasenotes.

Thanks for all the work you put into this. Take care!

**Comment by tnt944445** [comment]
It's hard work. I really appreciate the work you put into this. Thank you!
