### ISSUE TITLE
Entities Improvement

### ISSUE THREAD

**Issue by milandzuris** [fondberg/spotcast#481]
### The problem

Please add before every entity spotcast, now looks like entities from Spotify integration not from Spotcast.

![image](https://github.com/user-attachments/assets/31f400c8-0fa4-45ef-a830-95e5fa7c6e31)

### System Health details

*

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

*

**Comment by fcusson** [comment]
good point, didn't think of that

**Comment by fcusson** [comment]
tested some change, but since I create unique ids for each sensors, a reinstall will be required to take effect (technically, you can also rename them. The id change would survive a restart of Home Assistant because of the unique id. I'll add it in next build

**Comment by fcusson** [comment]
release [`v5.0.0-b3`](https://github.com/fondberg/spotcast/releases/tag/v5.0.0-b3) with entity names and id improvements
