### ISSUE TITLE
v5: Calling `spotcast.play_music` without `spotify_uri`

### ISSUE THREAD

**Issue by syphernl** [fondberg/spotcast#482]
### The problem

Not specifically a problem, more a question (or perhaps a feature request ;-))

With Spotcast < v5 you were able to do:

```yaml
      - service: spotcast.start
        data:
            entity_id: media_player.downstairs
```

This would resume the paused playback on my Google speaker group. 

With v5 `spotcast.play_music` now requires a `spotify_uri`. 

Switching to `spotcast.transfer_playback` seems to make most sense in this case, but according to the docs this requires an active playback. 
This would mean I have to the playback (at the original speakers) and then transfer, which is not a seemless/smooth as `spotcast.start` without an `uri`.

What would be the v5 equivalent of doing `spotcast.start` with just an `entity_id`?

### System Health details

Version | 5.0.0-b4
<redacted> Is Default | true
<redacted> Public Endpoint | ok
<redacted> Public Token | healthy
<redacted> Private Endpoint | ok
<redacted> Private Token | healthy

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

-

### Example YAML snippet

```yaml
- service: spotcast.play_media
        data:
          media_player:
            entity_id: media_player.downstairs
```

### Anything in the logs that might be useful for us?

```txt
Error: required key not provided @ data['spotify_uri']
```

**Comment by fcusson** [comment]
Hi @syphernl  thanks for the ticket. The documentation might not be clear in this case. `spotcast.transfer_playback` is the equivalent of `spotcast.start` without a URI. It should function the same and is the goal. By active playback, I only meant that there is a playback state provided by the [API](https://developer.spotify.com/documentation/web-api/reference/get-information-about-the-users-current-playback). Even if paused, it is an "active" playback in the sense of the Spotify API, just in a paused state.

Please test it out. If it doesn't work exactly like the pre `v5` start without uri, please update this ticket with the issue in the behavior so I can modify the service.

I'll also update the documentation to make this clearer.

**Comment by fcusson** [comment]
removed bug label until confirmation of issue in service behavior

**Comment by syphernl** [comment]
Hi @fcusson Thanks for your quick reply :)

As a test I paused Spotify (on my laptop), then triggered:

```yaml
action: spotcast.transfer_playback
data:
  media_player:
    entity_id: media_player.mini_office
```

This results in getting the following errors 

```Failed to perform the action spotcast.transfer_playback. Unknown error```

The logs state:

```txt
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/services/service_handler.py", line 59, in async_relay_service_call
    await handler(self.hass, call)
  File "/config/custom_components/spotcast/services/transfer_playback.py", line 40, in async_transfer_playback
    await async_play_media(hass, call)
  File "/config/custom_components/spotcast/services/play_media.py", line 62, in async_play_media
    if uri.startswith("spotify:track:"):
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by fcusson** [comment]
@syphernl perfect, thanks for the report, I know exactly what error I did. I'll be able to fix that after work

**Comment by fcusson** [comment]
@syphernl actually, that was far easier to fix then expected. Its done, I'll send the next build for you to try

**Comment by fcusson** [comment]
`v5.0.0-b5` pushed, please confirm if working properly now. I tested on my end and was able to transfer playback from a paused state to a Chromecast player without issue

**Comment by syphernl** [comment]
Works like a charm! Thanks for your quick fix!

**Comment by antonio1475** [comment]
Hi,

`spotcast.transfer_playback` only works for me if music was recently playing (minutes, <1 hour). Otherwise it doesn't actually start playing or I get errors like `Failed to perform the action spotcast.transfer_playback. https://api.spotify.com/v1/me/player/play?device_id=ef86dc42ada21exxx: Can't have offset for context type: ARTIST`

`spotcast.start` without URI used to work even if 24 hours had passed and it would resume whatever Spotify had in queue.

Am I doing something wrong? Thank you!

**Comment by fcusson** [comment]
@antonio1475, no Spotify changed how long they are reporting playback_state. They pretty much report an empty playback state as soon as the active application is closed. They also stop reporting when the application is active for a while. As mentionned in other tickets. I'm working on a way to save and resume playback from the last known state.
