### ISSUE TITLE
v5: Very high integration start up time with many playlists in account

### ISSUE THREAD

**Issue by syphernl** [fondberg/spotcast#484]
### The problem

After updating (to 5.0.0-b5, but the initial setup on 5.0.0-b4 also took quite some time) HASS is showing that it is starting up Spotcast for a (very) long time: "Starting Spotcast, not everything will be available until it is finished."
In System > Repairs > Integration Startup Times it shows it took 501.56 s (nearly 8,5 minutes) to start up the Spotcast integration.

![image](https://github.com/user-attachments/assets/6f5d961c-669e-4923-882a-0f95c63b89c4)

Doing a manual reload of the service is also stuck on "Initializing" for a very long time.

During initializing I noticed that the playlists sensor became unavailable. 
This is likely the cause of the problem since I have about 2000 playlists. If I disable this sensor and reload the integration manually it executes within a second or two.

However, restarting still takes a lot of time.

As a result, it seems that I may be hitting some ratelimits on the Spotify API since the official Spotify integration of HASS now fails to start or reload.

### System Health details

Version | 5.0.0-b5

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

-

### Anything in the logs that might be useful for us?

After a manual reload:

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:635
First occurred: 14:20:56 (1 occurrences)
Last logged: 14:20:56

Error setting up entry Spotify for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 133, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 197, in async_setup_entry
    return await self._platforms[key].async_setup_entry(config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 332, in async_setup_entry
    return await self._async_setup_platform(async_create_setup_awaitable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 373, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 648, in async_add_entities
    await add_func(coros, entities, timeout)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 557, in _async_add_and_update_entities
    results = await asyncio.gather(*tasks, return_exceptions=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError
```

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:635
First occurred: 14:20:56 (1 occurrences)
Last logged: 14:20:56

Error setting up entry Spotify for spotcast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/__init__.py", line 75, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2255, in async_forward_entry_setups
    await self._async_forward_entry_setups_locked(entry, platforms)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2266, in _async_forward_entry_setups_locked
    await asyncio.gather(
asyncio.exceptions.CancelledError
```

**Comment by fcusson** [comment]
yeah, 2,000 might create a problem, I'll set a soft limit for the playlist pager. I'll make it a configurable option.

With my very noobie count of 60 I wasn't having that issue. I'll probably integrate the same thing for liked songs. I was able to test that its working fine for up to around a thousand liked songs, but might start to become a problem down the line if someone has much more than that

**Comment by syphernl** [comment]
I have disabled all entities relating to playlists or liked songs but it doesn't seem to help much unfortunately. 
Interestingly it showed the same startup time (501.76). Something must've timed out allowing the setup to complete.

**Comment by fcusson** [comment]
I would be interested in checking your debug log at start up. See where the issue in startup is. Potentially that due to the number of pages the spotify handler has to go through, Spotify is throttling the API and forcing you on low performance tier. Could you also share your Spotify Dev App endpoints graph. It looks like this:

![image](https://github.com/user-attachments/assets/62a8d6fd-8a9e-45ce-9549-462d64527642)

**Comment by syphernl** [comment]
My graph:

![image](https://github.com/user-attachments/assets/00134bd0-857a-4925-96cd-2962011dcb1b)

Interestingly, my number of requests is far less than can be seen in your graph.

**Comment by fcusson** [comment]
> It seems to me Spotcast is doing a lot of redundant things?

Not really, if you look, you have a lot of `2024-11-26 14:51:11.392 DEBUG (MainThread) [custom_components.spotcast.spotify.account] Using cached profile dataset`. I'm using a cache system with variable expirations for all the datasets, things like profile, only expires after around 10 minutes, while things like devices expire around every 30 seconds. But when ever anything wants to retrieve a dataset a debug log will be created, that just means something in Home Assistant requested the information, but if the cache is still fresh, it just uses the cached data. Also, there is an async lock on the refresh process meaning even if multiple entities try to refresh the data, only one will be able to and the rest must wait on the single refresh to complete before getting the newly created cached data. Also the refreshing API tokens doesn't mean its actually getting new tokens, it simply means the `async_ensure_tokens_valid` method was called.

You can find the refresh factors in the [`SpotifyAccount` class](https://github.com/fondberg/spotcast/blob/dev/custom_components/spotcast/spotify/account.py)

```python
    DATASETS = {
        "devices": {
            "refresh_factor": 1,
            "can_expire": False,
        },
        "liked_songs": {
            "refresh_factor": 4,
            "can_expire": False,
        },
        "playlists": {
            "refresh_factor": 2,
            "can_expire": False,
        },
        "profile": {
            "refresh_factor": 10,
            "can_expire": True,
        },
        "categories": {
            "refresh_factor": 10,
            "can_expire": False,
        },
        "playback_state": {
            "refresh_factor": 1/2,
            "can_expire": False,
        }
    }
```

The `refresh_factor` is multiplied with the `base_refresh_rate` you can set in the `Configure` menu. The factors I've used are very much placeholders and I needed more use cases and types of users to better tweek them. In this case, the liked songs and playlists could probably benefit from a bigger refresh factor. If I implement a soft limit that can be configured, that would also decrease the number of API calls being made. I could then simply switch the sensor to `1000+` state as an example.

> Interestingly, my number of requests is far less than can be seen in your graph.
> 
> Those stats are not realtime and only seem to go back to last Sunday.

I'm not too worried about pure number, its more about bursts that could be a problem. The hump you can see in my graph around the 10th of November caused the Spotify API to stop replying to me. I was playing with the cache system around that time and stress-tested the system during a full day.

**Comment by syphernl** [comment]
It might not (just) be the playlists / liked tracks. 
I disabled all `media_player` devices the integration created (not sure what this does, perhaps it should be possible to disable these?). 

As soon as I enabled one of them again (my laptop) the integration got stuck again at "Initializing" and the actions disappeared from the developer tools. When I disabled the entity again things went back to normal.

**Comment by fcusson** [comment]
Found a better solution for this specific problem. Instead of forcing a limit, I'm going to introduce a count_only flag for any function using a pager. That way sensors will only look for the total returned in the first API call. This way we'll be able to track any amount of playlists or liked songs with the same amount of API calls and reserve the full data_refresh for specific use cases like websocket calls

**Comment by fcusson** [comment]
just tested the change and my current setup time for spotcast is 2.79 sec. Number of API calls should be the same regardless of playlist or liked songs count

**Comment by fcusson** [comment]
@syphernl just released `build 9` can you confirm if that solves the start-up time. There are still issues with the playlist sensor. Its seems to be very unstable in working, but now at least its not blocking startup. I'll have to dig further why its hanging like that now. I never had that behavior in the past

**Comment by fcusson** [comment]
Great closing as resolved, the issue seems to be with the spotify library hanging for ever when it can't receive a reply from the spotify Api.

Eventually we'll need to move to spotifyaio, but that library is not quite ready its missing a few api endpoints.

I'll check to maybe add them myself to help bring the project along
