### ISSUE TITLE
Spotcast v5 playlist styles

### ISSUE THREAD

**Issue by mikevanes** [fondberg/spotcast#485]
### Summary

First of all, nice work on the new version. Looks good and the code is way more readable! 

I am working on a completely new spotify-card called: _spotcast-spotify-card_ which aims to work with the v5 version of spotcast.

However I have noticed a few limitations already. The new playlist websocket endpoint uses categories, where as before we used playlist names. I can't get my recently-played list now for example. Which is a shame, as these are very useful and most likely contains the playlists the user wants to see or listen to. 

Right now we are limited to categories or the playlists of the user. 

It would be nice if we could define a set of playlist I would like to include in the list as well or search for a playlist. 

Second points as we discussed is the chromecast devices seemingly not appearing. I found out that this was an issue with me using the devcontainer for development and it doesn't see any devices on my network - My bad.  

### Use Case

Have useful playlist showing.

**Comment by fcusson** [comment]
@mikevanes 

> I can't get my recently-played list now for example

I can probably add another special case (just like I did for `user`) Do you know of the specific endpoint in the API to get the recently-played ones. I'll add it in the account class

**Comment by mikevanes** [comment]
Sadly I dont. Tried looking into the old code but that is almost unreadable for me with limited Python knowledge

**Comment by fcusson** [comment]
ok, no problem, if it was a feature of the old code, I can parse through it. I never used this specific feature, so I never realised it was there

**Comment by fcusson** [comment]
@mikevanes could you confirm the playlist-type you were using was `recently-played`?

**Comment by mikevanes** [comment]
I was using that one indeed, but the complete supported list was:

```
Method: spotcast/playlist supporting different playlist_types.

    user, or default for user chosen saved playlists
    featured for spotify "featured" playlists (not personalized)
    discover-weekly for personalized "Made for _____" (includes daily mixes)
    recently-played for "Recently Played"
```

**Comment by fcusson** [comment]
ok, so featured, that's an additional API endpoint, I'll be able to check that. The recently-played will require to make the Spotify API think the web player is requesting a view. That's what the old code was doing and I tried to remove it to realign with the public API processes. I can add it as an additional function

**Comment by mfabiani53** [comment]
> I am working on a completely new spotify-card called: _spotcast-spotify-card_ which aims to work with the v5 version of spotcast.


Where to find this card?

**Comment by fcusson** [comment]
submitted [PR](https://github.com/mikevanes/spotcast/pull/1) to @mikevanes fork to help finalize #489. When PR approved and documentation written for new websocket endpoints and service, will be able to merge into the dev branch

**Comment by mikevanes** [comment]
@mfabiani53 This card is still in development should be ready somewhere next month I hope. Until than if you want to use the spotify-card do not upgrade spotcast.

**Comment by fcusson** [comment]
closing since we merged your PR. If you have any additional changes that you would like, lets add it to the [V5 project](https://github.com/users/fcusson/projects/1).
