### ISSUE TITLE
Failed to call service spotcast/start 'NoneType' object has no attribute 'host'

### ISSUE THREAD

**Issue by pixiandreas** [fondberg/spotcast#49]
Hi when i try to call spotcast/start with this service:
`
entity_id: media_player.vardagsrum_speaker
uri: 'spotify:playlist:XXXXXXXXXXXXXXX'
`
I got this error:
`
2020-02-06 17:47:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.XXXXXXXXXXXXX] 'NoneType' object has no attribute 'host'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/spotcast/__init__.py", line 156, in start_casting
    spotify_cast_device = SpotifyCastDevice(hass, call.data.get(CONF_DEVICE_NAME), call.data.get(CONF_ENTITY_ID))
  File "/config/custom_components/spotcast/__init__.py", line 207, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/config/custom_components/spotcast/__init__.py", line 218, in getChromecastDevice
    host = str(cast_info.host)
AttributeError: 'NoneType' object has no attribute 'host'
`

**Comment by fondberg** [comment]
Can you enable debug logs and send the log? This error suggests that something has gone wrong finding your device.
Also, is this something which happens all the time or just once in a while?

**Comment by pixiandreas** [comment]
It happens all the time, have try with 5 different GM mini include 1 GM  (normal)
I can play mp3 songs on the within Hass so they are all reachable from hass.

How can i enable the debug log for this ?

**Comment by fondberg** [comment]
Something is indeed wrong. First off is that you need a premium account for spotify. If that is case I want you to send logs for the complete call until the error.

To enable debug for spotcast you add 
```
logger:
  default: info
  logs:
    custom_components.spotcast: debug
```
to configuration.yaml and restart home-assistant.

**Comment by fondberg** [comment]
I believe I know what is wrong. The device is not found and there is not enough checks in the code to return good error message.

**Comment by fondberg** [comment]
Try using https://github.com/fondberg/spotcast/releases/tag/v2.7.0 which has better error message

**Comment by pixiandreas** [comment]
![image](https://user-images.githubusercontent.com/4090221/74148708-5a7ede00-4c06-11ea-931c-2d6036703af4.png)

**Comment by fondberg** [comment]
I'll change it 0.105 tomorrow

**Comment by pixiandreas** [comment]
Still the same issue with 2.7.1 :-(
![image](https://user-images.githubusercontent.com/4090221/74233443-f4a85a00-4cca-11ea-9691-dd301fc4f722.png)

**Comment by fondberg** [comment]
See other closed issue which states restart and wait is needed

**Comment by pixiandreas** [comment]
Hi.
During the problem to install 2.7.0 i try to remove the google cast integration from hass and enable it again.
And now i can play use spotcast on all units :-)

**Comment by fondberg** [comment]
Please upgrade again to avoid diffs in spotipy versions
https://github.com/fondberg/spotcast/releases/tag/v2.7.2
