### ISSUE TITLE
Spotify Logo

### ISSUE THREAD

**Issue by milandzuris** [fondberg/spotcast#491]
### The problem

There is some problem... but i like it

![image](https://github.com/user-attachments/assets/25cb5f3e-89c6-405f-98d6-5d6e697b53f7)

### System Health details

*

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

*

**Comment by fcusson** [comment]
Hi @milandzuris, not sure I understand the ticket

**Comment by milandzuris** [comment]
> Hi @milandzuris, not sure I understand the ticket

Spotcast has the Spotify Logo

**Comment by fcusson** [comment]
@milandzuris yeah [didn't have a choice](https://github.com/home-assistant/brands/pull/6137).

**Comment by milandzuris** [comment]
ochh...................
