### ISSUE TITLE
Two spotify accounts, not configurable

### ISSUE THREAD

**Issue by Diegocampy** [fondberg/spotcast#495]
### The problem

I have two different Spotify Premium accounts,
I tried with the beta of version 5 to configure two accounts, as I did before with versions up to 4, but when I try to associate the second account, the data overwrites the first, so I can't use two different ones

## System Information

version | core-2024.12.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.63-haos
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4993
Installed Version | 2.0.1
Stage | running
Available Repositories | 1489
Downloaded Repositories | 43

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 48.5 GB
disk_used | 16.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.15.0), Studio Code Server (5.17.3), File editor (5.8.0), Samba share (12.3.2), Home Assistant Google Drive Backup (0.112.1), Glances (0.21.1), Mosquitto broker (6.4.1), Zigbee2MQTT (1.42.0-2), Samba Backup (5.2.0), Cloudflared (5.2.2), Advanced SSH & Web Terminal (19.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 31
views | 30
mode | storage

</details>

<details><summary>Miele</summary>

component_version | 2024.11.1
-- | --
reach_miele_cloud | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24 novembre 2024 17:23
-- | --
current_recorder_run | 5 dicembre 2024 12:07
estimated_db_size | 1113.32 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Bose SoundTouch Plus</summary>

integration_version | v1.0.73
-- | --
devices_configured | 1: Bose (SoundTouch 30)

</details>

<details><summary>Spotcast</summary>

Version | 5.0.0-b14
-- | --
Paintervale Is Default | false
Paintervale Public Endpoint | ok
Paintervale Public Token | failed to load: unhealthy
Paintervale Private Endpoint | ok
Paintervale Private Token | healthy

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>SpotifyPlus</summary>

integration_version | v1.0.67
-- | --
clients_configured | 2: Diegocampy (premium), paintervale (premium)
api_endpoint_reachable | ok

</details>

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_spotcast_2024-12-05T11-25-03.883Z.log](https://github.com/user-attachments/files/18022413/home-assistant_spotcast_2024-12-05T11-25-03.883Z.log)

**Comment by fcusson** [comment]
Hi @Diegocampy that us very unusual, I have setup both my partner and mine without issues.

Are you setting the second account from browser where the second account is connected?

If not, then you are associating your oauth credentials for the profile which will overwrite your old profile since I take the profile from the oauth client for unique ID of the entry.

**Comment by Diegocampy** [comment]
I'm not very good, actually yes, same pc with spotify logged in to the first account. Now to add the second account I logged out of the pc browser, and then logged in with the second account, and only after that I was able to insert the second account without problems. Thank you for specifying this to me. A guide or a request for confirmation in the procedure could help those who are not very practical like me

**Comment by fcusson** [comment]
@Diegocampy I'll keep the ticket open for the moment. As you mentionned, the fact that its using the account of the logged in Spotify Account in the browser is not very clear. I'll add some error handling arround mismatch accounts and pre-existing profiles to help guide the user.

Also, don't sell yourself short. It seemed evident for me, but I also developped the integration, so its easy for me to know, that one was clearly a blindspot for me, so thank you for bringing it up. That will help improve a lot the first (or second I should say) time experience for the users and help guide to the correct solution.

**Comment by fcusson** [comment]
next build will include the improved workflow. Tested locally and is able to abort when the entry already exist and when the public and private tokens do not point to the same account.

**Comment by fcusson** [comment]
Build 16 release with improvement to configuration flow
