### ISSUE TITLE
Liked songs playlist

### ISSUE THREAD

**Issue by Hollywood25201** [fondberg/spotcast#497]
### Summary

Hi there! Would love to help make this happen if you'd like. I'm a software engineer that has never really used github, just git. So may need to help teach me some stuff, but would love to learn.
Anywhey...

I'd love it if there was a way to use the spotcast.start service and have it play my liked songs playlist. I have another app I use called true shuffle (https://github.com/kartikk221/spotify-true-shuffle)
It uses the spotify api to get the list of liked songs playlist and will shuffle them without spotify's "influenced" shuffle.
I cannot find a way to even play the liked songs playlist with Spotcast. I was wondering if this would be possible/reasonable to have added to spotcast. I know another app that is able to play a shuffle of the liked songs is SpotifyPlus (https://github.com/thlucas1/homeassistantcomponent_spotifyplus)

Let me know what I could do to help support this as I have a little too much time on my hands.
Thanks!
Scott

### Use Case

I want to be able to play my liked songs playlist via Spotcast

### Benefits

This would be super useful as sometimes I enjoy the whiplash of my liked songs playlist from death metal to jazz. It's also my biggest playlist and enjoy the variety. And maybe while we're at it we could add a true shuffle to ensure we don't hear the same 30 songs spotify has been paid to show us over and over....

### Potential Solutions

I've found 2 other projects that leverage the spotify api to either retrieve or play the liked songs playlist.

SpotifyPlus (https://github.com/thlucas1/homeassistantcomponent_spotifyplus)
- spotifyplus.player_media_play_track_favorites is used to play the playlist but I can't get it to start up my google home speakers as well as Spotcast can.

Spotify true shuffle (https://github.com/kartikk221/spotify-true-shuffle)
- It's an interface that gets all of your playlists and at a click of a button will actually shuffle them randomly to ensure the same songs don't play over and over.

**Comment by fcusson** [comment]
@Hollywood25201 this is already possible to do. You simply need to provide the URI `spotify:user:<your-user-id>:collection`. Even better, the new beta has a custom service just for that. But if you want to help on the project, please do so, there are a couple of improvements we are working on before the release of the beta in production for `V5`. One of them I haven't been able to tackle is improving management of podcast.

As for working with Guthub vs git, you'll see its very similar, the inly difference with the more basic git workflow is that you will have to create a fork of the project and then make a pull request to get the change integrated.

**Comment by Hollywood25201** [comment]
That worked wonders! Would you be open to connecting on Discord at some point about me helping out?
Thanks,
Scott
Discord: Hollywood2520#4138

**Comment by fcusson** [comment]
of course. Also, since there seems to be more people interested in working on the project, I created a project board for Spotcast V5. I saddly don't have acces to create it under fondberg's project (he only gave me maintainer access, not admin), but its under my fork [fcusson/spotcast](https://github.com/fcusson/spotcast/projects?query=is%3Aopen)
