### ISSUE TITLE
Draw order

### ISSUE THREAD

**Issue by Cassock** [fondberg/spotcast#5]
Maybe this is a greater issue with HA, but I haven't seen it before. When hovering to select a mediaplayer, the menu is shown under the adjacent card. 
![image](https://user-images.githubusercontent.com/15901832/57816538-a8cf8100-7749-11e9-87b8-351d704979f8.png)

**Comment by fondberg** [comment]
Hi @Cassock I think you mean to report this in https://github.com/custom-cards/spotify-card right?
