### ISSUE TITLE
Conflict of python package version with homeassistant core

### ISSUE THREAD

**Issue by oncleben31** [fondberg/spotcast#50]
After upgrading to homeassistant core 0.105.2 the restart is very long compared to 0.104.x.
The logs shows that `spotipy` and `zeroconf` are installed every restart due to difference with homeassistant core version.

**Comment by jes1417** [comment]
Seeing this as well, checking config and server restarts are extremely slow compared to the seconds it would normally take. I was trying to figure out what I installed recently that would cause this and it's pointing me here. I just setup Spotify and spotcast the day 105 launched.

**Comment by fondberg** [comment]
I'll see if I have time to bump the versions and make a release tomorrow. One thing that is the great thing with open source is that anyone can help out through creating a PR. That way it would go way faster

**Comment by jes1417** [comment]
I wish I knew how, I definitely would. Guess it's time to start learning...

**Comment by fondberg** [comment]
Released https://github.com/fondberg/spotcast/releases/tag/v2.7.0 which fixes this. Closing

**Comment by oncleben31** [comment]
There is still a difference with spotypy module:

- 2.6.3 for spotcast
- 2.7.1 for Home Assistant spotify integration

Impact on each HA restart, first the version 2.6.3 is install and then 2.7.1. It takes useless long time.
I've quickly look at the release note of spotipy module. It seems to have breaking changes between the two version. I'm not confortable to work on a PR yet.

**Comment by fondberg** [comment]
Right. I saw that it finally is maintained. I did a test before when it was released and it works good but I'll give it another test before bumping to a new release of spotcast
