### ISSUE TITLE
Bad logger message

### ISSUE THREAD

**Issue by breakthestatic** [fondberg/spotcast#501]
### The problem

I've started seeing errors in the Home Assistant logs noting a `Bad logger message` related to the `play_from_search` call. I pasted the condensed log viewer message because the raw debug logs don't actually output it. I'm guessing it has something to do with the actual payload of the log not conforming to the required structure for display by the front-end.

## System Information

version | core-2024.12.1
-- | --
installation_type | Unsupported Third Party Container
dev | false
hassio | false
docker | true
user | homeassistant
virtualenv | true
python_version | 3.13.0
os_name | Linux
os_version | 6.1.0-28-amd64
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1486
Downloaded Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 19
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 2, 2024 at 6:53 PM
-- | --
current_recorder_run | December 10, 2024 at 1:09 PM
estimated_db_size | 509.06 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotcast</summary>

Version | 5.0.0-b16
-- | --
Breakthestatic Is Default | true
Breakthestatic Public Endpoint | ok
Breakthestatic Public Token | healthy
Breakthestatic Private Endpoint | ok
Breakthestatic Private Token | healthy

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

This error originated from a custom integration.

Logger: custom_components.spotcast.services.play_from_search
Source: custom_components/spotcast/services/play_from_search.py:147
integration: Spotcast (documentation, issues)
First occurred: 8:42:46 AM (4 occurrences)
Last logged: 8:42:46 AM

Bad logger message: artists (([{'external_urls': {'spotify': 'https://open.spotify.com/artist/1b4QIYWHRjtt6kbssFDTRj'}, 'followers': {'href': None, 'total': 572}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/1b4QIYWHRjtt6kbssFDTRj', 'id': '1b4QIYWHRjtt6kbssFDTRj', 'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5ebc49b138227b6e58c2094ee9b', 'height': 640, 'width': 640}, {'url': 'https://i.scdn.co/image/ab67616100005174c49b138227b6e58c2094ee9b', 'height': 320, 'width': 320}, {'url': 'https://i.scdn.co/image/ab6761610000f178c49b138227b6e58c2094ee9b', 'height': 160, 'width': 160}], 'name': 'Insomniac', 'popularity': 0, 'type': 'artist', 'uri': 'spotify:artist:1b4QIYWHRjtt6kbssFDTRj'}],))
Bad logger message: tracks (([{'album': {'album_type': 'album', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/2jwC7uml6QVgLBfx1Hbtek'}, 'href': 'https://api.spotify.com/v1/artists/2jwC7uml6QVgLBfx1Hbtek', 'id': '2jwC7uml6QVgLBfx1Hbtek', 'name': 'Memo Boy', 'type': 'artist', 'uri': 'spotify:artist:2jwC7uml6QVgLBfx1Hbtek'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/0a0ftVkZr4K1QoOXcZF0V1'}, 'href': 'https://api.spotify.com/v1/albums/0a0ftVkZr4K1QoOXcZF0V1', 'id': '0a0ftVkZr4K1QoOXcZF0V1', 'images': [{'height': 640, 'width': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273fd062989b0b63b82f5949524'}, {'height': 300, 'width': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02fd062989b0b63b82f5949524'}, {'height': 64, 'width': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851fd062989b0b63b82f5949524'}], 'is_playable': True, 'name': 'Songs & Demos 2015-2017', 'release_date': '2021-06-04', 'release_date_precision': 'day', 'total_tracks': 33, 'type': 'album', 'uri': 'spotify:album:0a0ftVkZr4K1QoOXcZF0V1'}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/2jwC7uml6QVgLBfx1Hbtek'}, 'href': 'https://api.spotify.com/v1/artists/2jwC7uml6QVgLBfx1Hbtek', 'id': '2jwC7uml6QVgLBfx1Hbtek', 'name': 'Memo Boy', 'type': 'artist', 'uri': 'spotify:artist:2jwC7uml6QVgLBfx1Hbtek'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3pFSlKAoVnaEycgIcPDctw'}, 'href': 'https://api.spotify.com/v1/artists/3pFSlKAoVnaEycgIcPDctw', 'id': '3pFSlKAoVnaEycgIcPDctw', 'name': 'Chakra Efendi', 'type': 'artist', 'uri': 'spotify:artist:3pFSlKAoVnaEycgIcPDctw'}], 'disc_number': 1, 'duration_ms': 212307, 'explicit': False, 'external_ids': {'isrc': 'AUNUK1700026'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/2klj0StczYde6WUHBJo5F6'}, 'href': 'https://api.spotify.com/v1/tracks/2klj0StczYde6WUHBJo5F6', 'id': '2klj0StczYde6WUHBJo5F6', 'is_local': False, 'is_playable': True, 'name': 'Insomniac', 'popularity': 68, 'preview_url': 'https://p.scdn.co/mp3-preview/42a1409835d917e775b022ada1aa1af3ada0a607?cid=d8a5ed958d274c2e8ee717e6a4b0971d', 'track_number': 26, 'type': 'track', 'uri': 'spotify:track:2klj0StczYde6WUHBJo5F6'}],))
Bad logger message: albums (([{'album_type': 'album', 'total_tracks': 14, 'is_playable': True, 'external_urls': {'spotify': 'https://open.spotify.com/album/7d3nOmFvL51roNElAdpi9d'}, 'href': 'https://api.spotify.com/v1/albums/7d3nOmFvL51roNElAdpi9d', 'id': '7d3nOmFvL51roNElAdpi9d', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273ac9a652335cf34de9a65292a', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02ac9a652335cf34de9a65292a', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851ac9a652335cf34de9a65292a', 'width': 64}], 'name': 'Insomniac', 'release_date': '1995-10-10', 'release_date_precision': 'day', 'type': 'album', 'uri': 'spotify:album:7d3nOmFvL51roNElAdpi9d', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7oPftvlwr6VrsViSDV7fJY'}, 'href': 'https://api.spotify.com/v1/artists/7oPftvlwr6VrsViSDV7fJY', 'id': '7oPftvlwr6VrsViSDV7fJY', 'name': 'Green Day', 'type': 'artist', 'uri': 'spotify:artist:7oPftvlwr6VrsViSDV7fJY'}]}],))
Bad logger message: playlists (([{'collaborative': False, 'description': '', 'external_urls': {'spotify': 'https://open.spotify.com/playlist/53mnf8Ui2yMVBbbpIggx4e'}, 'href': 'https://api.spotify.com/v1/playlists/53mnf8Ui2yMVBbbpIggx4e', 'id': '53mnf8Ui2yMVBbbpIggx4e', 'images': [{'height': None, 'url': 'https://i.scdn.co/image/ab67616d00001e02fd062989b0b63b82f5949524', 'width': None}], 'name': '1 hour insomniac', 'owner': {'display_name': 'MrPapaXD', 'external_urls': {'spotify': 'https://open.spotify.com/user/31wud76fwhzbsq3beohlbvkgtjui'}, 'href': 'https://api.spotify.com/v1/users/31wud76fwhzbsq3beohlbvkgtjui', 'id': '31wud76fwhzbsq3beohlbvkgtjui', 'type': 'user', 'uri': 'spotify:user:31wud76fwhzbsq3beohlbvkgtjui'}, 'primary_color': None, 'public': True, 'snapshot_id': 'AAAAFs6Br8x1QjPEKeuihx4eHfsNGE0n', 'tracks': {'href': 'https://api.spotify.com/v1/playlists/53mnf8Ui2yMVBbbpIggx4e/tracks', 'total': 17}, 'type': 'playlist', 'uri': 'spotify:playlist:53mnf8Ui2yMVBbbpIggx4e'}],))

**Comment by fcusson** [comment]
I think I forgot a debug print I've put while stress-testing something

**Comment by fcusson** [comment]
> I think it's likely related to https://github.com/fondberg/spotcast/commit/8c25eb6595bbe8c632489e26a7e524176bb9983f

Yeah you found exactly my dirty log I didn't remove from the code. 🤣 Should probably add a test to make sure all `LOGGER.warn()` are removed before pushing. Actual warnings will use `LOGGER.warning`

**Comment by fcusson** [comment]
Relationship based a fix in build 17 please reopen if other issue appear
