### ISSUE TITLE
Failure when trying to update

### ISSUE THREAD

**Issue by Ysbrand** [fondberg/spotcast#53]
You are running Home Assistant version '0.105.2', but this repository requires minimum version 'null' to be installed.

**Comment by fondberg** [comment]
Has the parameter in the manifest for HA components changed?

**Comment by JurajNyiri** [comment]
Yes, it was changed here https://github.com/fondberg/spotcast/commit/525924d1d526d544b0697bab76f6d2355fafc028#diff-2e3e1e64419442cae5f4ad942f145d5cL11

Along with that this line https://github.com/fondberg/spotcast/commit/525924d1d526d544b0697bab76f6d2355fafc028#diff-04c6e90faac2675aa89e2176d2eec7d8L18 in README should be updated as well.

Latest version of HASS currently is 0.105.2 https://www.home-assistant.io/blog/2020/02/05/release-105/

**Comment by Ysbrand** [comment]
Thanks!

**Comment by totti4ever** [comment]
So, what do I have to do to update?

I am on 0.105.2 and 2.7.0 and can't install 2.7.1 because of

> You are running Home Assistant version '0.105.2', but this repository requires minimum version 'null' to be installed.

**Comment by Ysbrand** [comment]
I saw the same initially. After a restart of HA and some patience (30 mins) I was able to update.

Not sure if it was the patience or the reboot (or both...)

**Comment by totti4ever** [comment]
Yip, restart fixed it for me as well
