### ISSUE TITLE
Could not find device with name [friendly_name]

### ISSUE THREAD

**Issue by watermarkhu** [fondberg/spotcast#57]
Hello, 

I've been having difficulties to get this component to start for a while now. 
Whenever I call the service, 
```
service: spotcast.start 
   uri: 'spotify:user:spotify:playlist:37i9dQZF1DX2FsCLsHeMrM'
   entity_id: media_player.bedroom_speaker
```
it seems to search for the friendly_name of the chromecast device, but fails to find it. 
```
Could not find device Google Home Mini from hass.data, falling back to pychromecast scan
```

```
Could not find device with name Google Home Mini
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/spotcast/__init__.py", line 156, in start_casting
    spotify_cast_device = SpotifyCastDevice(hass, call.data.get(CONF_DEVICE_NAME), call.data.get(CONF_ENTITY_ID))
  File "/config/custom_components/spotcast/__init__.py", line 207, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/config/custom_components/spotcast/__init__.py", line 233, in getChromecastDevice
    raise HomeAssistantError('Could not find device with name {}'.format(device_name))
homeassistant.exceptions.HomeAssistantError: Could not find device with name Google Home Mini
```

This has been going on for me since V2 onwards.

**Comment by fondberg** [comment]
Have you upgraded to latest 2.7.2 and home assiatant > 1.05? There has been issues with different dependencies. 

If that doesn't solve it I would make sure the devices are really discovered correctly in HA and make sure they have the friendly name set as attributes on their state

**Comment by watermarkhu** [comment]
Yes I'm currently on latest Spotcast 2.7.2 and Home Assistant 1.05.3. 
And the friendly name is indeed a state attribute. I'll try changing a few things a bit more.

**Comment by fondberg** [comment]
How did it go?

**Comment by watermarkhu** [comment]
I discovered that I can't start Spotify playback neither from my phone. I think that this has nothing to do with HA or spotcast. There seems to be some people with this casting issue on the Spotify community forum.

Anyhow, thanks for your responses.

**Comment by fondberg** [comment]
Ok. Closing this. Feel free to open a new issue if you encounter one

**Comment by Sholofly** [comment]
@watermarkhu Did you manage to fix this? If yes, how?
