### ISSUE TITLE
Random song won't work with albums

### ISSUE THREAD

**Issue by kleinc80** [fondberg/spotcast#58]
When using the `random_song` parameter the current implementation will always call `user_playlist_tracks(uri)` regardless if a playlist or an album was provided using `uri`. Consequently the call will fail for album uris like ` 'spotify:album:5wuthq3XXmrpwlowdNxsBf'` and execution will stop.

Quick fix I did for myself:
``` 
           if random_song:
                if uri.find('album') > 0:
                    results = client.album_tracks(uri)
                if uri.find('playlist') > 0:
                    results = client.playlist_tracks(uri)
                position = random.randint(0, results['total'] - 1)
                _LOGGER.debug('Start playback at random position: %s', position)
                kwargs['offset'] = {'position': position}
```

Btw, `user_playlist_tracks()` is deprecated, that's why I changed it to `playlist_tracks()`.

Thank's for your great component!

**Comment by fondberg** [comment]
nice find. If you don't want to wait you can create a PR.

**Comment by kleinc80** [comment]
It is not urgent for me. I did a whole bunch of changes and if I got time and mood I'll clearly separate them into branches for individual PRs:
- add shuffle param
- add offset param
- find Spotify Connect devices, too (in addition to Cast devices)
- transfer playback and continue playing
- the fix for this issue

Is anything of this of interest?

**Comment by fondberg** [comment]
Sounds interesting. I'm not sure about the spotify connect one though as
that is covered by the builtin spotify integration

**Comment by kleinc80** [comment]
I totally get your point!

The reasons I implemented the Spotify Connect thing were:
1. In my Spotify app I see my Spotify Connect and Chromcast devices and it came handy to just target them in the very same way using the very same component.
2. But even more important: The builtin Spotify integration doesn't cover this/my use case. There is no way to get the builtin integration to do a play-request including device_id against the Spotify web api. The only way to do that is doing more than one call: Transfer playback + play. In my scenario this causes horrible delays or I run into race conditions as my Spotify Connect device needs time to wake up from standby before further commands are accepted.

**Comment by fondberg** [comment]
Ok, Fair enough. I've been hoping since I first published this component
that HA would add a way to get a more powerful token and then this
component could move the functionality to the builtin one..

But that doesn't seem to happen so I'm fine with adding connect devices.
I'm pretty sure it will take around 1 day before sonos users will come
screaming to add that as well ;-)

**Comment by kleinc80** [comment]
It's actually pretty easy to get a more powerful token. The only reason why the builtin integration gets a "weak" token, is, because it asks for just as much as it needs (which is good, actually):
```
    def extra_authorize_data(self) -> dict:
        """Extra data that needs to be appended to the authorize url."""
        scopes = [
            # Needed to be able to control playback
            "user-modify-playback-state",
            # Needed in order to read available devices
            "user-read-playback-state",
            # Needed to determine if the user has Spotify Premium
            "user-read-private",
        ]
        return {"scope": ",".join(scopes)}
```
By adding more scopes you can get a token as powerful as you need it.

That leads me to a question: What is the reason for the "Webbrowser-simulated username/password" login to Spotify instead of using the API to get a more powerful token? Can we change that, too? :-)

**Comment by fondberg** [comment]
Fixed through your PR in v2.8.0 🎆 🍾

**Comment by fondberg** [comment]
And for the more powerful token it is not possible. I have worked at Spotify and the public tokens will fail if you ask for the extra scopes required. You can try if you want with using spotipy standalone and requiring the scopes required for chromecast

**Comment by fondberg** [comment]
What is required is that they add the client id as an official integration and then configure that client id with this possibility. Paulus tried and they denied home assistant due to it not being a commercial application

**Comment by kleinc80** [comment]
I'd like to better understand the restriction with Spotify auth here.
I tried the Authorization Code flow using Postman (providing client id and client secret which I had previously created in my Spotify dashboard) and performing the oauth steps by hand in a browser - and I got a powerful token plus refresh token. Same did the old spotify integration, I just added more scopes to that one (and some code using the power) and it worked well.

But that's not a "public token" then, I guess? Which flow from https://developer.spotify.com/documentation/general/guides/authorization-guide/ does HA use?

**Comment by fondberg** [comment]
First, the flow that HA is using doesn't matter as all flows can get you a token with the selected scopes.

The token you receive using any of the flows lacks a scope to start chromecast on an idle chromecast device. It will be powerful enough for connect devices as well as play something on an already started spotify app on chromecast given the app was started in the same account (by for instance an official spotify app)

You can try this yourself if you want by using your token you received and a standalone pychromecast checkout. In pychromcast there is a spotify example. Modify it so it takes your token instead of the scraped token and make sure your chromecast device doesn't have spotify running. 

You will hear the bloink when spotify starts on the device but it will fail after the token is sent to the device.

**Comment by kleinc80** [comment]
Thank's for pointing me into the right direction! I'll have a look, however, after your explanation it seems pretty clear anyway...
