### ISSUE TITLE
Support transfer ongoing playback.

### ISSUE THREAD

**Issue by phr0z** [fondberg/spotcast#6]
Spotifys API has support for transferring ongoing playback to other known devices.
This can be implemented into spotcast with the help of spotipys method transfer_playback() as I've done to my fork which makes up for some pretty smooth automation possibilites.

I have for instance automated so that IF Im listening to Spotify when I come home spotcast will transfer my ongoing playback to my Chromecast Group.

https://github.com/phr0z/spotcast

I saw your suggestion on automatically transfer playback but I can't come up with any good solutions to this as you might want to actually have control over this and switch playlists/tracks in some cases. Don't really know how this logic would go. Maybe you have some ideas? :-)

**Comment by fondberg** [comment]
@phr0z I played with this today and I have something which will automatically transfer the playback if something is playing. I'm not enterily happy so if you can 👀 at it it would be gr8
https://github.com/fondberg/spotcast/pull/7

**Comment by phr0z** [comment]
I've looked at it but haven't tried it yet. What do we gain from using the Spotify component in HASS vs using spotipy besides an additional layer? :-) 

Also we still have to define a dummy URI in SERVICE_START_COMMAND right? Maybe changing it to optional is a bit cleaner? 

Maybe Im misinterpreting the code but to me it only seems to check and handle transfers between already playing Chromecast devices? The cool thing with transfer is that it allows you to transfer the playback from any of your Spotify capable devices. So I'll check if Spotify is playing on my phone for example with the help of the logic from the Spotify component. Altought transferring between Chromecasts is nice as well! :-)

Im a bit of noob when it comes to python so maybe I got the code wrong tho. :-)

**Comment by fondberg** [comment]
We don't gain anything actually with using HASS media player listing over spotify rest api which can check more devices.... you are completly right....

Maybe make the URI optional and if that is empty try a transfer if something is playing?
That would be quite simple and reduce the logic a lot.

**Comment by phr0z** [comment]
Yes I like that idea! Make URI optional and a condition check for it to start transfer playback. Also perhaps an additional condition, like check if Spotify is actually playing something. spotipy should have this available most certainly? :-)

**Comment by fondberg** [comment]
Sure. I have my own python package of spotipy because the official one hasn't been updated since 2017. I think it has this functionality though so it will be easy to add this conditional chk

**Comment by fondberg** [comment]
Added all possible supports for it (empty URI as well as your suggested parameter) in #12
