### ISSUE TITLE
cast group issue

### ISSUE THREAD

**Issue by neomvll** [fondberg/spotcast#66]
> That is weird... unless you have a cast group you have created which you cast to...
> 
> Which version of HA and the component are you running? It might be related to a dependency.

Hi, I have a cast group in my google home(3 for now) and everytime I try change the playback to group, the music pauses. 
So changing between google home devices is working very well, but not in a group.
Any tip?
EDIT:
Using mini-media-player w/ transfer_playback: true in all devices:

          - type: entities
            entities:
              - type: custom:mini-media-player
                entity: media_player.spotify
                group: true
                hide:
                  power: true
                shortcuts:
                  columns: 4 
                  buttons:
                    - name: All
                      type: service
                      id: spotcast.start
                      data:
                        device_name: All
                        transfer_playback: true
                    - name: Dovakin
                      type: service
                      id: spotcast.start
                      data:
                        transfer_playback: true
                        entity_id: media_player.dovakin
                    - name: Jorgin
                      type: service
                      id: spotcast.start
                      data:
                        transfer_playback: true
                        device_name: Jorgin
                    - name: Enzo
                      type: service
                      id: spotcast.start
                      data:
                        transfer_playback: true
                        device_name: Enzo

_Originally posted by @neomvll in https://github.com/fondberg/spotcast/issues/25#issuecomment-596804709_

**Comment by fondberg** [comment]
I'm afraid there seem to be limitations that many people have reported (around the internet) regarding groups and how they are treated with regards to casting and how spotify works on them.
For instance Spotify will choose one device in the group as the "master device" when playing in that group. If you try to do anything on another device in the group or transfer playback it seems like it fails.

What could be worth trying is the upcoming release of spotcast which treats transfer playback differently. See the PR that is accepted but not merged yet (I have been busy with family and work and will not have time to do a release in a while)

**Comment by neomvll** [comment]
Ok, while we wating your fixed release, I'm testing a workaround with scripts and for now is working.
Maybe can help others too.

ui-lovelace.yaml-------
              - type: custom:mini-media-player
                entity: media_player.spotify
                artwork: cover
                source: icon
                group: true
                hide:
                  power: true
                shortcuts:
                  columns: 4
                  buttons:
                    - name: All
                      type: script
                      id: script.googlehome_all
                    - name: Dovakin
                      type: script
                      id: script.googlehome_dovakin
                    - name: Enzo
                      type: script
                      id: script.googlehome_enzo
                    - name: Jorgin
                      type: script
                      id: script.googlehome_jorgin

scripts.yaml------
googlehome_all:
  sequence:
    - service: spotcast.start
      data:
        entity_id: media_player.all
    - delay: "00:00:01"
    - service: media_player.media_play
      data:
        entity_id: media_player.spotify
googlehome_dovakin:
  sequence:
    - service: spotcast.start
      data:
        entity_id: media_player.dovakin
    - delay: "00:00:01"
    - service: media_player.media_play
      data:
        entity_id: media_player.spotify
googlehome_enzo:
  sequence:
    - service: spotcast.start
      data:
        entity_id: media_player.enzo
    - delay: "00:00:01"
    - service: media_player.media_play
      data:
        entity_id: media_player.spotify
googlehome_jorgin:
  sequence:
    - service: spotcast.start
      data:
        entity_id: media_player.jorgin
    - delay: "00:00:01"
    - service: media_player.media_play
      data:
        entity_id: media_player.spotify
-----

So why the "delay" option?. Well, I have no idea haha, but only works with 1 sec delay or more :)

**Comment by fondberg** [comment]
Please don't post home assistant scripts here. Use the forum for that,

This is not a spotcast issue, this is a spotify and chromecast issue. There is nothing spotcast can do to fix cast groups is notoriously buggy (my spotify app quite often can't cast to my groups at home)

**Comment by neomvll** [comment]
> Please don't post home assistant scripts here. Use the forum for that,
> 
> This is not a spotcast issue, this is a spotify and chromecast issue. There is nothing spotcast can do to fix cast groups is notoriously buggy (my spotify app quite often can't cast to my groups at home)

Sorry if I've tried help you and others too, and I've only keep issue opened because you said: 
"What could be worth trying is the upcoming release of spotcast which treats transfer playback differently. See the PR that is accepted but not merged yet (I have been busy with family and work and will not have time to do a release in a while)"

But whatever, thanks anyway

**Comment by fondberg** [comment]
Sorry if I was short in the reply. I'm just so fed up with Googles buggy chromecast group implementation and Spotify's even buggier aps that I need to front just becasue I have a tool that uses them.
I will release a new version today which has a force option. Try that out with the following info:
```
The parameter transfer_playback does not exist anymore and if you use it, you need to update your configuration. Use an empty uri and optionally the new parameter force_playback instead.
```

**Comment by fondberg** [comment]
Try this Fixed in https://github.com/fondberg/spotcast/releases/tag/v2.9.0 with force_playback true and then false to see if it helps

**Comment by neomvll** [comment]
I think its working!!! Changing between groups and devices and music dont stops! Thanks!

**Comment by fondberg** [comment]
closing
