### ISSUE TITLE
Random volumes when starting spotcast

### ISSUE THREAD

**Issue by ASNNetworks** [fondberg/spotcast#72]
I noticed a bug with the latest .9 update. When I start a spotcast service call, the volume is randomized every time. This happens on all speakers and groups (also between speakers inside the same group). This behaviour is not present when casting using Google Assistant or the Spotify apps (official). 

Note: this occurs when using either force_playback: true or false. Both give the same result, so can’t say if the issue lies there or with something else that has changed.

**Comment by fondberg** [comment]
It might be because I wanted to remove the beep at startup. I will have a look at it to see if I made something wrong

**Comment by fondberg** [comment]
It reads the volume level right before muting it and  starting the spotify app on the device and then resets it to whatever it was.
Are you sure it is random?

**Comment by ASNNetworks** [comment]
Thanks for your quick response! I have tested some more and I think I see what the issue is. Indeed it sets the volume to 0 and then restores it, however this bugs out sometimes which results in muted audio. 

The random volumes I encountered happen when using group speakers. I think this happens due to how the group cast operates with volume. So I firgure this is not something to easily fix. Is it possible for me to remove some code so the volume muting does not occur? I have no problems with the beeping sound personally. 

I have found some lines where the volume is stated. But I’m not a programmer so I don’t know if removing those lines will break the entire integration.

**Comment by soldag** [comment]
The beeping can also be disabled at all in the device settings in the Google Home app. At least for the Chromecast Audio that I have at my home.

**Comment by ASNNetworks** [comment]
> It reads the volume level right before muting it and starting the spotify app on the device and then resets it to whatever it was.
> Are you sure it is random?

Any way for me to remove some code to disable that feature? It sometimes doesn’t unmute and causes volume issues 100% of the time when casting to group speakers...

**Comment by fondberg** [comment]
Yes, you can comment out the following lines
https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/__init__.py#L261
https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/__init__.py#L262
https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/__init__.py#L269

**Comment by ASNNetworks** [comment]
> Yes, you can comment out the following lines
> https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/__init__.py#L261
> https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/__init__.py#L262
> https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/__init__.py#L269

Thanks, this works great!
