### ISSUE TITLE
Entity for daily mix playlists?

### ISSUE THREAD

**Issue by rako77** [fondberg/spotcast#79]
I want to create a script in home assistant that plays daily mix's. In order to do so it would be useful if there was a spotcast entity with the daily mixes and the relevant playlist ID's. I can do the work of creating it but I wanted to get your input on how you would like it to be structured in your code base.

**Comment by fondberg** [comment]
are you looking to have the daily mixes URIs as entities in some sort of sensor ?

**Comment by bendikrb** [comment]
I'd love this aswell!
Perhaps a `spotcast_playlists_made_for_[account_name|you]` playlist sensor with the last played playlist URI as the state (for example), and the actual data stored as an attribute?

```json
{
  "playlists": {
    "Discover Weekly": "spotify:playlist:xxxxxxxxxxxxxx",
    "Daily Mix 1": "spotify:playlist:xxxxxxxxxxxx",
    "Daily Mix 2": "spotify:playlist:xxxxxxxxxxxx",
    " .... "
  }
}
```

**Comment by fondberg** [comment]
This kind of sensor should not  be in spotcast 
The reason for spotcasts existence is that it requires a more powerful token to start playback on chromecast devices. Growing it more would then make the existing spotify mediaplayer kind of obsolete which is the opposite of what we in the community want

**Comment by fondberg** [comment]
What you can do is to retrieve the daily mix playlists using the websocket api in spotcast.

It is not ok though do poll this api more than max once per hour, preferably more seldom

**Comment by bendikrb** [comment]
Kudos! That sounds reasonable.. :+1:

**Comment by fondberg** [comment]
Closing this
