### ISSUE TITLE
Spotcast turns all cast devices unavailable after upgrading to 0.109.0b

### ISSUE THREAD

**Issue by SeanPM5** [fondberg/spotcast#81]
I opened a bug report on core repo https://github.com/home-assistant/core/issues/34620 about Google Homes all going unavailable after upgrading to Home Assistant 0.109.0b0 (beta).

With the help of Paulus, found out that Spotcast was causing it because it bundles an older version of pychromecast or something. After removing `pychromecast==4.1.1` line from the `/custom_components/spotcast/manifest.json` file and restarting, all of my Google Cast devices returned again.

So this is just a heads up that this component requires a change to be compatible with upcoming 0.109. Thanks.

**Comment by jes1417** [comment]
There is a PR #80 to address this issue

**Comment by jes1417** [comment]
If spotipy and pychromecast are both included in the HA repo couldn't we just remove them from this component?

**Comment by SeanPM5** [comment]
I checked the issues but didn't notice there was already a PR submitted. That's great, thank you @jes1417! 👍
