### ISSUE TITLE
Unable update to latest spotcast while being on 109b3.

### ISSUE THREAD

**Issue by rosenius** [fondberg/spotcast#82]
I think the attached image and header says it all.

![IMG_0242](https://user-images.githubusercontent.com/18368372/80303299-a7a73080-87af-11ea-8ab8-830226006e9f.png)

**Comment by jes1417** [comment]
PR #83 should address this

**Comment by fondberg** [comment]
I made a comment question in #83.

**Comment by fondberg** [comment]
Closing this now
