### ISSUE TITLE
Music stops after about an hour of playback

### ISSUE THREAD

**Issue by astone123** [fondberg/spotcast#85]
I'm using this component to trigger a white noise playlist that plays on the Google Home by my bed while I sleep. The initial casting works well, but whenever I trigger the playback with spotcast, my Google Home stops playing about an hour later. This doesn't happen when I cast Spotify directly from the app on my phone.

Has anyone else run into this issue or have an idea about why that might be happening? Thanks!

**Comment by FuzzyMistborn** [comment]
Known issue with no workaround: https://community.home-assistant.io/t/spotcast-custom-component-to-start-playback-on-an-idle-chromecast-device/114232/164

**Comment by astone123** [comment]
Oh okay, thanks! I'll close this now
