### ISSUE TITLE
pychromecast.quick_play

### ISSUE THREAD

**Issue by davidrustingha** [fondberg/spotcast#89]
After upgrading to v3.0 this error is still showing

Component error: spotcast - No module named 'pychromecast.quick_play'

**Comment by fondberg** [comment]
Must be something in your setup. I didnt see it on mine.

**Comment by davidrustingha** [comment]
Seems to be fixed in HA-core version 0.110.3.

I'll let myself out ;)

**Comment by fondberg** [comment]
:+1:
