### ISSUE TITLE
Exceeded 30 redirects.

### ISSUE THREAD

**Issue by notpurum** [fondberg/spotcast#92]
The following error appears in the log when I try to launch the service:

> Logger: homeassistant.components.websocket_api.http.connection.1663781648
> Source: custom_components/spotcast/__init__.py:85
> Integration: Home Assistant WebSocket API (documentation, issues)
> 
> Exceeded 30 redirects.
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
>     connection.context(msg),
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1292, in _execute_service
>     await self._hass.async_add_executor_job(handler.func, service_call)
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/spotcast/__init__.py", line 166, in start_casting
>     access_token, expires = get_spotify_token(sp_dc=dc, sp_key=key)
>   File "/config/custom_components/spotcast/__init__.py", line 85, in get_spotify_token
>     data = st.start_session(sp_dc, sp_key)
>   File "/usr/local/lib/python3.7/site-packages/spotify_token.py", line 19, in start_session
>     headers=headers, cookies=cookies)
>   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
>     return self.request('GET', url, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 665, in send
>     history = [resp for resp in gen] if allow_redirects else []
>   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 665, in <listcomp>
>     history = [resp for resp in gen] if allow_redirects else []
>   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 166, in resolve_redirects
>     raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
> requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

This doesn't happen with any other components.
I probably must mention that I live in Russia and Spotify doesn't officially work here. However it works great in apps or in browser when I open links like open.spotify.com/track... 
But if I would open spotify.com in the incognito mode I get the "Not available in your country" page.

**Comment by jacobswe** [comment]
You likely copied sp_key incorrectly. Try generating new keys and ensuring you copy them in their entirety. You will be able to see the devices with the key faulty, but not be able to call the service. This is a relatively common issue and should maybe be added as an FAQ.

**Comment by notpurum** [comment]
Damn it. It was the sp_dc that was copied incorrectly.
