### ISSUE TITLE
Configuration check and HA restart time issue

### ISSUE THREAD

**Issue by rtirelli** [fondberg/spotcast#93]
Hi, has anybody noticed that too long time to restart HA is needed? Restart on my Pi 3b+ takes 8 min time. Today I tried to comment the spotcast configuration lines and the restart time dropped to 2min down! Please check what’s going on. Thank you!

**Comment by fondberg** [comment]
Please include relevant configuration lines (do you have the sensor enabled?), relevevant log lines, HA version, spotcast version

**Comment by rtirelli** [comment]
Sorry, you're right. 
I have only this in the configuration.yaml
spotcast:
  sp_dc: xxxxxxxxx
  sp_key: xxxxxxxxxxx

Onlly warning Spotcast related:
2020-06-03 22:21:06 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

 and after some minute I get this

2020-06-03 22:27:28 WARNING (MainThread) [homeassistant.setup] Setup of default_config is taking over 10 seconds

I know, this last warning is not spotcast related but if I remove the two lines in the config file, the warnig has gone and the HA is faster.

Home Assistant version is 0.110.4

**Comment by fondberg** [comment]
Hi

Spotcast doesn't do anything on startup. What could be wrong is the version differences of dependencies. 
Which spotcast version and HA version are you running?

**Comment by rtirelli** [comment]
Hi

Spotcast version v3.0.0
Home Assistant version is 0.110.4

**Comment by fondberg** [comment]
I see they updated pychromecast in 0.110.4. I will make an update to spotcast this weekend

**Comment by fondberg** [comment]
Try the new release (requires HA 0.111)

**Comment by provinzio** [comment]
I still have the same issue with HA 0.111 and spotcast 3.1.0.

Bumping spotipy to 2.12.0 solves the problem for me.

**Comment by fondberg** [comment]
Right, didn't see that before. Released 3.1.1, try that,.

**Comment by fondberg** [comment]
Is it working? If so I will close

**Comment by provinzio** [comment]
For me it is. I am not sure about @rtirelli

**Comment by banolka** [comment]
I think i have se problem when I add spotcast to config and try to check the config before restart it cannot complete. When I check config with spocast commented out it takes 5 sec to check config

With spotcast i cant restart HA - I'm on 0.111 and latest spotcast from hacs

**Comment by rtirelli** [comment]
> Try the new release (requires HA 0.111)

Now it works perfectly, thanks!!!

**Comment by provinzio** [comment]
@bendikrb this sounds like a different problem. Can you show us your config entry which you add to the working config. 

What is the error message of HA after the check?

**Comment by bendikrb** [comment]
> @bendikrb this sounds like a different problem.
I guess you ment tagging @banolka :)

**Comment by fondberg** [comment]
Closing as per successful comments ^^
