### ISSUE TITLE
Default repeat value triggers `turning repeat on`

### ISSUE THREAD

**Issue by provinzio** [fondberg/spotcast#98]
Debugging the code in #94, I realized that
```
if repeat:
  _LOGGER.debug('Turning repeat on %s', repeat)
```
gets triggered, even though I have not turned it on.

This might be because of the default value `'off'` which is a boolean True.

I have not looked deeper into the code, but this could solve the issue.
```
if repeat and repeat != 'off':
  _LOGGER.debug('Turning repeat on %s', repeat)
```

**Comment by fondberg** [comment]
repeat only takes true or false as per json and yaml specs

**Comment by provinzio** [comment]
I can not confirm your statement.

When repeat isn't specified, it takes the value `'off'`.
(see `vol.Optional(CONF_REPEAT, default='off'): cv.string,`)

Running the follow does not activate repeat, because it's passed as string to the function
```
entity_id: media_player.wohnzimmer
uri: spotify:playlist:2dchkbrA3FbjoJ4dYpNDAQ
repeat: true
```

**Comment by fondberg** [comment]
Hmmm. Ok. I will have a look at it tomorrow
