### ISSUE TITLE
Play to multiple Spotify devices and sync playback

### ISSUE THREAD

**Issue by marrobHD** [fondberg/spotcast#99]
My idea is to sync playback with different Spotify accounts that stream to different devices. 
Idea: master streams to virtual Spotify device created by spotcast. Spotcast trys to stream that from the master to the others.
Would that be possible to integrate?

**Comment by fondberg** [comment]
Can you describe in more detail what you mean?

**Comment by marrobHD** [comment]
Multiroom playback like from sonos

**Comment by fondberg** [comment]
That is already supported with chromecast groups.
Spotcast does not have detailed knowledge about the playback. It only starts it on a device
